# database.sh - Dynamically loaded database module
# Generated by extract-modules-v2.sh
# DO NOT EDIT - This file is auto-generated

#@help __bootstrap1
# @command bootstrap <path> <profile>
# @summary Create a new database at <path> with the named profile
# @group   setup
# @param   path     directory to create the database in
# @param   profile  environment profile (minimal or all)
# @returns shell commands (create structure, copy defaults, stamp version)
# @example vpn-switch bootstrap ~/.vpn-switch/db minimal
#@end
__bootstrap1() {
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" bootstrap \"$1\" minimal"
}

#@help ___bootstrap2
# @internal bootstrap chain step (create dir, then init)
#@end
___bootstrap2() {
  local basedir="$1"
  local profile="$2"

  # Validation (generation time)
  if [ -z "$basedir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error 'bootstrap requires basedir argument'"
    return 0
  fi
  if [ -z "$profile" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error 'bootstrap requires profile argument'"
    return 0
  fi

  # Create target directory with minimal structure for batch execution
  # This solves the chicken-and-egg problem: ___batch2 needs .tmp/batch-exits/
  # Note: init is also a batch combinator, so it needs this structure to exist
  # Extract permissions from VPN_SWITCH_INIT_DIR_CONFIG
  local tmp_mode=$(echo "$VPN_SWITCH_INIT_DIR_CONFIG" | grep '^\.tmp:' | cut -d: -f2)
  local batch_exits_mode=$(echo "$VPN_SWITCH_INIT_DIR_CONFIG" | grep '^\.tmp/batch-exits:' | cut -d: -f2)

  # Create base directory if needed
  if [ ! -d "$basedir" ]; then
    $MODIFY_DIR_CREATE "$basedir"
    $MODIFY_FILE_PERMS 0700 "$basedir"
  fi

  # Create .tmp if needed (operational directory - may have content)
  if [ ! -d "$basedir/.tmp" ]; then
    $MODIFY_DIR_CREATE "$basedir/.tmp"
    $MODIFY_FILE_PERMS "$tmp_mode" "$basedir/.tmp"
  fi

  # Create .tmp/batch-exits if needed (operational directory - may have content)
  if [ ! -d "$basedir/.tmp/batch-exits" ]; then
    $MODIFY_DIR_CREATE "$basedir/.tmp/batch-exits"
    $MODIFY_FILE_PERMS "$batch_exits_mode" "$basedir/.tmp/batch-exits"
  fi

  # Command 1: init with minimal environment overrides
  # Use simple interpreters for bootstrap (sh instead of complex pipelines)
  # VPN_SWITCH_CONTEXT_BOOTSTRAPPED=1 tells the script to use CACHE_ENV_ARGS
  echo "VPN_SWITCH_BASE=\"$basedir\" VPN_SWITCH_CONTEXT_BOOTSTRAPPED=1 VPN_SWITCH_CACHE_ENV_ARGS=\"PATH=/bin:/usr/bin:/usr/local/bin VPN_SWITCH_BATCH_KEEP_GOING=0 VPN_SWITCH_TERMINAL_INTERPRETER=/bin/sh VPN_SWITCH_COMBINATOR_INTERPRETER=/bin/sh VPN_SWITCH_BATCH_COMBINATOR_INTERPRETER=/bin/sh VPN_SWITCH_INTERPRETER_lift1=cat\" \"\$VPN_SWITCH_CONTEXT_SCRIPT\" init $profile"

  # Command 2: stamp .version from source so future drift can be detected.
  # 'version sync' is not in COMMANDS_WITHOUT_DATABASE, so CACHE_ENV_ARGS is
  # not eval'd before lookup_interpreter runs. Export interpreters directly.
  echo "VPN_SWITCH_BASE=\"$basedir\" VPN_SWITCH_CONTEXT_BOOTSTRAPPED=1 PATH=/bin:/usr/bin:/usr/local/bin VPN_SWITCH_TERMINAL_INTERPRETER=/bin/sh VPN_SWITCH_COMBINATOR_INTERPRETER=/bin/sh VPN_SWITCH_BATCH_COMBINATOR_INTERPRETER=/bin/sh \"\$VPN_SWITCH_CONTEXT_SCRIPT\" version sync"

  # Command 3: success log
  # Need same environment variables for log command
  echo "VPN_SWITCH_BASE=\"$basedir\" VPN_SWITCH_CONTEXT_BOOTSTRAPPED=1 VPN_SWITCH_CACHE_ENV_ARGS=\"PATH=/bin:/usr/bin:/usr/local/bin VPN_SWITCH_TERMINAL_INTERPRETER=/bin/sh\" \"\$VPN_SWITCH_CONTEXT_SCRIPT\" log 'Bootstrap complete: $basedir ($profile)'"
}

#@help _lift1
# @internal phase-lifting helper (plain shell -> terminal function)
#@end
_lift1() {
  local phase_name="$1"

  if [ -z "$phase_name" ]; then
    display error "lift requires phase name argument"
    display plain "Usage: cat input.sh | vpn-switch lift <phase>"
    return 1
  fi

  # Read input from stdin, skip shebang if present
  local input_content=$(cat)
  local commands=$(echo "$input_content" | tail -n +2)

  # If input didn't have shebang, use all content
  if ! echo "$input_content" | head -1 | grep -q '^#!/'; then
    commands="$input_content"
  fi

  # Escape runtime variables so they survive heredoc expansion
  # Variables like $?, $@, $*, $1, $2, etc. need to be escaped
  local escaped=$(echo "$commands" | sed 's/\$?/\\$?/g; s/\$@/\\$@/g; s/\$\*/\\$*/g; s/\$\([0-9]\)/\\$\1/g')

  # Output lifted template to stdout
  cat <<LIFT_OUTER
#!/bin/sh
# Auto-generated phase template (lifted from simple format)

# Unpack context variables (for generation-time expansion)
eval "\$VPN_SWITCH_CONTEXT_CONNECT"

case "\$1" in
    verify)
        cat <<'EOF'
# Verify function for $phase_name phase
verify_${phase_name}() {
    local step="\$1"
    local exit_code="\$2"

    case "\$step" in
        prepare)
            if [ "\$exit_code" -ne 0 ]; then
                echo "# ERROR: $phase_name prepare failed" >&2
                exit 1
            fi
            echo "# ✓ $phase_name prerequisites met" >&2
            ;;
        execute)
            if [ "\$exit_code" -ne 0 ]; then
                echo "# ERROR: $phase_name configuration failed" >&2
                exit 1
            fi
            echo "# ✓ $phase_name configured successfully" >&2
            ;;
    esac
}
EOF
        ;;

    prepare)
        cat <<'EOF'
echo "# ==> Phase: $phase_name (prepare)" >&2
verify_${phase_name} prepare 0
EOF
        ;;

    execute)
        cat <<EOF
echo "# ==> Phase: $phase_name (execute)" >&2

$escaped
verify_${phase_name} execute \\\$?
EOF
        ;;

    inspect)
        cat <<EOF
echo "### $phase_name Phase"
echo "Context: interface=\$interface"
EOF
        ;;

    *)
        echo "# Usage: \\\$0 {verify|prepare|execute|inspect}" >&2
        exit 1
        ;;
esac
LIFT_OUTER
}

#@help _database_init0
# @internal database-structure init chain step
#@end
_database_init0() {
  local base="$VPN_SWITCH_BASE"

  echo "# Initialize VPN switch database: $base"
  echo "PATH=/bin:/usr/bin:/usr/local/bin"

  # Generation time: iterate config, check state, emit concrete commands
  echo "$VPN_SWITCH_INIT_DIR_CONFIG" | while IFS=: read -r dir mode exec_flag content_policy; do
    [ -z "$dir" ] && continue
    local full_path="$base/$dir"

    if [ -e "$full_path" ]; then
      # Directory exists - validate at generation time

      # 1. Must be a directory
      if [ ! -d "$full_path" ]; then
        echo "echo '# Error: Path exists but is not a directory: $dir' >&2"
        echo "echo '# Please remove the file and run init again.' >&2"
        echo "exit 1"
        continue
      fi

      # 2. Check content policy
      case "$content_policy" in
        operational)
          # Allow existing content
          ;;
        exclusive|*)
          # Must be empty for security
          if [ -n "$(ls -A "$full_path" 2>/dev/null)" ]; then
            echo "echo '# Error: Directory $dir exists but is not empty' >&2"
            echo "echo '# Exclusive hierarchy required for security.' >&2"
            echo "exit 1"
            continue
          fi
          ;;
      esac

      # 3. Check permissions (warn only)
      local actual_mode=$($CMD_STAT_PERMS "$full_path" 2>/dev/null)
      local normalized_expected=$(echo "$mode" | sed 's/^0*//')
      local normalized_actual=$(echo "$actual_mode" | sed 's/^0*//')
      if [ "$normalized_actual" != "$normalized_expected" ]; then
        echo "echo '# Warning: Directory $dir has mode $actual_mode, expected $mode' >&2"
      fi

      # 4. Exec flag check
      if [ "$exec_flag" = "exec" ]; then
        local test_script="$full_path/.init_exec_test_$$"
        echo "#!/bin/sh" > "$test_script"
        echo "exit 0" >> "$test_script"
        $MODIFY_FILE_PERMS 0700 "$test_script"
        if ! "$test_script" 2>/dev/null; then
          $MODIFY_FILE_REMOVE "$test_script"
          echo "echo '# Error: Directory $dir requires exec mount but is mounted noexec' >&2"
          echo "exit 1"
          continue
        fi
        $MODIFY_FILE_REMOVE "$test_script"
      fi

      echo "echo '# Validated: $dir' >&2"
    else
      # Directory doesn't exist - emit create commands
      echo "$MODIFY_DIR_CREATE '$full_path'"
      echo "$MODIFY_FILE_PERMS $mode '$full_path'"
      echo "echo '# Created: $dir (mode $mode)' >&2"
    fi
  done

  # Protocol extension links
  echo "cd '$base' || exit 1"
  [ -L "$base/conf" ] || echo "$MODIFY_LINK_FORCE wireguard conf"
  [ -L "$base/ovpn" ] || echo "$MODIFY_LINK_FORCE openvpn ovpn"
  echo "echo '# Database ready: $base' >&2"
}

#@help _environment_init1
# @internal environment-defaults init helper (copy profile to .env/default)
#@end
_environment_init1() {
  local profile="${1:-minimal}"
  local base="$VPN_SWITCH_BASE"
  local cache_file="$base/.env/local/VPN_SWITCH_CACHE_ENV_ARGS"
  local profile_upper
  profile_upper=$(echo "$profile" | tr '[:lower:]' '[:upper:]')
  local profile_var="VPN_SWITCH_PROFILE_${profile_upper}"
  local profile_file="$VPN_SWITCH_TEMPLATE_DIR/environment/$profile_var"

  # Validation at generation time
  if [ ! -f "$profile_file" ]; then
    echo "echo '# Error: Unknown profile: $profile' >&2"
    echo "echo '# Looking for: $profile_file' >&2"
    echo "exit 1"
    return 1
  fi

  if [ ! -d "$VPN_SWITCH_TEMPLATE_DIR/environment" ]; then
    echo "echo '# Error: Template directory not found' >&2"
    echo "exit 1"
    return 1
  fi

  echo "# Install environment templates for profile: $profile"

  # Generation time: iterate templates, emit concrete commands
  local var_list
  var_list=$(head -1 "$profile_file")
  for varname in $var_list; do
    local template="$VPN_SWITCH_TEMPLATE_DIR/environment/$varname"
    if [ -f "$template" ]; then
      echo "$MODIFY_FILE_COPY_FORCE '$template' '$base/.env/default/$varname'"
      echo "$MODIFY_FILE_PERMS 0600 '$base/.env/default/$varname'"
    else
      echo "echo '# Warning: Template not found: $varname' >&2"
    fi
  done

  # Profile marker
  echo "$MODIFY_FILE_COPY_FORCE '$profile_file' '$base/.env/default/$profile_var'"
  echo "$MODIFY_FILE_PERMS 0600 '$base/.env/default/$profile_var'"

  # Invalidate cache if exists
  if [ -f "$cache_file" ]; then
    echo "$MODIFY_FILE_REMOVE '$cache_file'"
    echo "echo '# Cache invalidated' >&2"
  fi

  echo "echo '# Installed $profile profile' >&2"
}

#@help __environment_cache0
# @command environment cache [on|off|status]
# @summary Manage the cached-environment optimisation
# @group   configuration
# @param   on|off|status  enable, disable, or report the cache (default: status)
# @returns shell commands / cache status
# @example vpn-switch environment cache status
#@end
__environment_cache0() {
  # Combinator - delegate to status display
  echo '"$VPN_SWITCH_CONTEXT_SCRIPT" environment cache status'
}

#@help _environment_cache1
# @internal arity-1 sibling of 'environment cache' (on|off|status)
#@end
_environment_cache1() {
  local cmd="$1"
  local cache_file="$VPN_SWITCH_BASE/.env/local/VPN_SWITCH_CACHE_ENV_ARGS"

  case "$cmd" in
    on)
      # Generation time: write cache directly (ESSENCE).
      # Force a fresh disk scan: build_env_args_full short-circuits on an
      # in-memory VPN_SWITCH_CACHE_ENV_ARGS (inherited via env -), so without
      # unsetting it here a rebuild would just rewrite the stale value it is
      # meant to replace. Unset in a subshell so the scan reads .env/ afresh.
      ( unset VPN_SWITCH_CACHE_ENV_ARGS; build_env_args_full ) > "$cache_file"
      $MODIFY_FILE_PERMS 0600 "$cache_file"
      local var_count
      var_count=$(wc -w < "$cache_file" | tr -d ' ')

      echo "echo '# Environment cache ENABLED' >&2"
      echo "echo '# Cached $var_count variables' >&2"
      ;;

    off)
      # Generation time: check and act
      if [ -f "$cache_file" ]; then
        echo "$MODIFY_FILE_REMOVE '$cache_file'"
        echo "echo '# Environment cache DISABLED' >&2"
      else
        echo "echo '# Environment cache already disabled' >&2"
      fi
      ;;

    status|"")
      # Generation time: examine and report
      if [ -f "$cache_file" ]; then
        local var_count
        var_count=$(wc -w < "$cache_file" | tr -d ' ')
        echo "echo '# Environment cache: ENABLED ($var_count vars)' >&2"
      else
        echo "echo '# Environment cache: DISABLED' >&2"
      fi
      ;;

    *)
      echo "echo '# Error: Unknown cache command: $cmd' >&2"
      echo "exit 1"
      ;;
  esac
}

#@help _lift3
# @internal phase-lifting helper (3-arg form)
#@end
_lift3() {
  local phase_name="$1"
  local input_file="$2"
  local output_file="$3"

  # Security: Require absolute paths to prevent writing outside database
  case "$output_file" in
    /*)
      # Absolute path - OK
      ;;
    *)
      generate_error "lift requires absolute output path" "Got relative path: $output_file"
      return 0
      ;;
  esac

  case "$input_file" in
    /*)
      # Absolute path - OK
      ;;
    *)
      generate_error "lift requires absolute input path" "Got relative path: $input_file"
      return 0
      ;;
  esac

  local output_dir=$(dirname "$output_file")

  # Generation time: create directory and write file
  $MODIFY_DIR_CREATE "$output_dir"
  lift_phase_simple "$input_file" "$phase_name" "$output_file"
  $MODIFY_FILE_PERMS +x "$output_file"

  # Output: status message for execution time
  echo "echo '# ✓ Lifted: $phase_name' >&2"
}

#@help __phases_lift1
# @internal phase-lifting chain step
#@end
__phases_lift1() {
  local phase_backend="$1"

  if [ -z "$phase_backend" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error 'phases lift requires phase:backend argument'"
    return 0
  fi

  # Split phase:backend
  local phase_name=$(echo "$phase_backend" | cut -d: -f1)
  local backend_name=$(echo "$phase_backend" | cut -d: -f2)

  if [ -z "$phase_name" ] || [ -z "$backend_name" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error 'Invalid format: $phase_backend - expected phase:backend'"
    return 0
  fi

  # Resolve profile name from template/phase/default symlink
  local profile_name="base"
  if [ -L "$VPN_SWITCH_TEMPLATE_DIR/phase/default" ]; then
    profile_name=$(basename "$(readlink "$VPN_SWITCH_TEMPLATE_DIR/phase/default")")
  fi

  local input_file="$VPN_SWITCH_TEMPLATE_DIR/phase/$profile_name/$phase_name/${backend_name}.sh"
  local output_file="$VPN_SWITCH_BASE/.include/phase/$profile_name/$phase_name/${backend_name}.sh"

  # Validation at generation time
  if [ ! -f "$input_file" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error 'Backend template not found: $input_file'"
    return 0
  fi

  # Delegate to lift terminal function
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" lift '$phase_name' '$input_file' '$output_file'"
}

#@help ___init1
# @internal arity-1 sibling of 'init' (with profile argument)
#@end
___init1() {
  local profile="${1:-minimal}"

  # Emit commands for batch execution
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" database init"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" environment init \"$profile\""
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" phases sync"

  # Emit final status message as comment
  cat <<EOF
# Database initialization complete: \$VPN_SWITCH_BASE
# Profile: $profile
EOF
}

#@help __init0
# @internal low-level database init — complex to call directly; use 'bootstrap'
#@end
__init0() {
  # Bootstrap: passthrough interpreter variables for init command
  # Since init creates the .env files, we need to provide defaults via CACHE_ENV_ARGS
  echo "VPN_SWITCH_CACHE_ENV_ARGS=\"VPN_SWITCH_COMBINATOR_INTERPRETER=sh VPN_SWITCH_TERMINAL_INTERPRETER=sh VPN_SWITCH_BATCH_COMBINATOR_INTERPRETER='while IFS= read -r line; do echo \\\"\\\$line\\\" | \\\$VPN_SWITCH_COMBINATOR_INTERPRETER; done'\" \"\$VPN_SWITCH_CONTEXT_SCRIPT\" init minimal"
}

#@help _setenv2
# @command setenv <VAR> <VALUE>
# @summary Set a vpn-switch environment variable (writes to .env/local/)
# @group   configuration
# @param   VAR    variable name
# @param   VALUE  value to set
# @returns shell commands (write the variable)
# @example vpn-switch setenv VPN_SWITCH_DISPLAY_ANSI 1
# @see     getenv
# @see     unsetenv
#@end
_setenv2() {
  local var_name="$1"
  local value="$2"
  local base="$VPN_SWITCH_BASE"
  local local_file="$base/.env/local/$var_name"
  local cache_file="$base/.env/local/VPN_SWITCH_CACHE_ENV_ARGS"

  # Validate variable name (only allow letters, numbers, and underscores)
  case "$var_name" in
    *[!A-Za-z0-9_]*)
      cat <<EOF
echo "# Error: Invalid variable name '$var_name'" >&2
echo "# Variable names must contain only letters, numbers, and underscores" >&2
exit 1
EOF
      return 1
      ;;
  esac

  # Check database ownership
  local current_user=$(id -u)
  local db_default_dir="$base/.env/default"
  if [ -d "$db_default_dir" ]; then
    local db_owner=$($EXAMINE_FILE_OWNER "$db_default_dir" 2>>"$LOG_FILE" | cut -d: -f1)
    if [ -n "$db_owner" ] && [ "$current_user" != "$db_owner" ]; then
      echo "# Warning: Database owned by UID $db_owner, running as UID $current_user" >&2
      echo "# Files created will have mismatched ownership. Consider:" >&2
      echo "#   - Running with correct user: sudo -u #$db_owner vpn-switch setenv ..." >&2
      echo "#   - Configuring MODIFY_FILE_OWNER with sudo in platform config" >&2
    fi
  fi

  # Set the variable (generation time - direct execution)
  $MODIFY_DIR_CREATE "$base/.env/local"
  $MODIFY_FILE_PERMS 0700 "$base/.env/local"
  printf '%s\n' "$value" > "$local_file"
  $MODIFY_FILE_PERMS 0640 "$local_file"

  # Try to set owner to match database (may fail without sudo, that's OK)
  if [ -d "$db_default_dir" ]; then
    local db_ownership=$($EXAMINE_FILE_OWNER "$db_default_dir" 2>>"$LOG_FILE" || echo "")
    if [ -n "$db_ownership" ]; then
      $MODIFY_FILE_OWNER "$db_ownership" "$local_file" 2>>"$LOG_FILE" || true
    fi
  fi

  # Rebuild caches (generation time)
  VPN_SWITCH_CACHE_ENV_ARGS=""
  local new_cache=$(build_env_args_full)
  VPN_SWITCH_CACHE_ENV_ARGS="$new_cache"
  if [ -f "$cache_file" ]; then
    printf '%s' "$new_cache" > "$cache_file"
    $MODIFY_FILE_PERMS 0600 "$cache_file"
  fi

  echo "# Set $var_name (effective next command)" >&2
}

#@help _getenv1
# @command getenv <VAR>
# @summary Print the effective value of a variable with its source
# @group   configuration
# @param   VAR  variable name
# @returns the variable's value and source (default vs local)
# @example vpn-switch getenv VPN_SWITCH_BASE
# @see     setenv
# @see     printenv
#@end
_getenv1() {
  local var_name="$1"
  local resolved layer path label

  # Generation time: find and read value (cascade via the shared resolver)
  if ! resolved=$(_env_resolve_file "$var_name"); then
    echo "echo '# Variable $var_name not found' >&2"
    echo "exit 1"
    return 0
  fi
  layer=$(printf '%s\n' "$resolved" | sed -n 1p)
  path=$(printf '%s\n' "$resolved" | sed -n 2p)
  case "$layer" in
    local)    label=".env/local/$var_name (override)" ;;
    default)  label=".env/default/$var_name (default)" ;;
    template) label="template/environment/$var_name (template)" ;;
  esac
  echo "echo '# Source: $label' >&2"
  echo "cat <<'EOF'"
  head -n 1 "$path"
  echo "EOF"
}

# NOTE: _env_resolve_file (the shared local->default->template resolver used by
# both _getenv1 above and the helpenv.sh env-var help commands) lives in the
# always-loaded core (vpn-switch.sh), so it is available no matter which module
# is lazy-loaded for a given command.

#@help _unsetenv1
# @command unsetenv <VAR>
# @summary Remove a variable from .env/local/
# @group   configuration
# @param   VAR  variable name
# @returns shell commands (remove the local override)
# @example vpn-switch unsetenv VPN_SWITCH_DISPLAY_ANSI
# @see     setenv
#@end
_unsetenv1() {
  local var_name="$1"
  local base="$VPN_SWITCH_BASE"
  local local_file="$base/.env/local/$var_name"
  local cache_file="$base/.env/local/VPN_SWITCH_CACHE_ENV_ARGS"

  # Generation time: check existence and unset
  if [ -f "$local_file" ]; then
    $MODIFY_FILE_REMOVE "$local_file"

    # Rebuild caches (generation time)
    VPN_SWITCH_CACHE_ENV_ARGS=""
    local new_cache=$(build_env_args_full)
    VPN_SWITCH_CACHE_ENV_ARGS="$new_cache"
    if [ -f "$cache_file" ]; then
      printf '%s' "$new_cache" > "$cache_file"
      $MODIFY_FILE_PERMS 0600 "$cache_file"
    fi

    echo "# Unset $var_name" >&2
  else
    echo "# Variable $var_name not set (nothing to unset)" >&2
  fi
}

#@help ___dumpenv1
# @internal environment portion of 'dump'
#@end
___dumpenv1() {
  local profile_name="$1"
  local base="$VPN_SWITCH_BASE"
  local profile_var="VPN_SWITCH_PROFILE_$(echo "$profile_name" | tr '[:lower:]' '[:upper:]')"
  local profile_file="$VPN_SWITCH_TEMPLATE_DIR/environment/$profile_var"
  local cache_file="$base/.env/local/VPN_SWITCH_CACHE_ENV_ARGS"

  # Validate profile exists
  if [ ! -f "$profile_file" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Profile not found: $profile_var at $profile_file\""
    return 0
  fi

  # Read profile variable list (first line)
  local profile_vars=$(head -n 1 "$profile_file" 2>>"$LOG_FILE")

  # Prologue vs Epilogue behavior:
  # - prologue: Only profile variables (safe minimal set for restore)
  # - epilogue: ALL variables from .env/local/ (complete user environment)
  if [ "$profile_name" = "epilogue" ]; then
    # Epilogue: Output ALL variables from .env/local/ (including function-specific interpreters)
    for local_file in "$base/.env/local/"*; do
      [ -f "$local_file" ] || continue
      varname=$(basename "$local_file")

      # Skip cache file - it's regenerated via "environment cache on" in dump
      if [ "$varname" = "VPN_SWITCH_CACHE_ENV_ARGS" ]; then
        continue
      fi

      local value=$(head -n 1 "$local_file" 2>>"$LOG_FILE")

      if [ -n "$value" ]; then
        # Output setenv command (will be in dump output)
        # Use escaped dollar sign to output literal "$VPN_SWITCH_CONTEXT_SCRIPT"
        echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" setenv $varname \"$value\""
      fi
    done
  else
    # Prologue: Only output variables in profile (prevents function-specific interpreters from breaking restore)
    for varname in $profile_vars; do
      local local_file="$base/.env/local/$varname"

      # Skip cache file - it's regenerated via "environment cache on" in dump
      if [ "$varname" = "VPN_SWITCH_CACHE_ENV_ARGS" ]; then
        continue
      fi

      if [ -f "$local_file" ]; then
        local value=$(head -n 1 "$local_file" 2>>"$LOG_FILE")

        if [ -n "$value" ]; then
          # Output setenv command (will be in dump output)
          # Use escaped dollar sign to output literal "$VPN_SWITCH_CONTEXT_SCRIPT"
          echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" setenv $varname \"$value\""
        fi
      fi
    done
  fi

  # After prologue/epilogue setenv commands, output cache enablement if cache is enabled
  # This enables cache for fast import operations (prologue) and regenerates it after setenv (epilogue)
  if [ "$profile_name" = "prologue" ] || [ "$profile_name" = "epilogue" ]; then
    # Only include cache commands if cache is actually enabled in source database
    if [ -f "$cache_file" ]; then
      echo ""
      if [ "$profile_name" = "prologue" ]; then
        echo "# Enable environment cache (makes imports 89-95% faster)"
      else
        echo "# Restore environment cache (VPN_SWITCH_CACHE_ENV_ARGS)"
      fi
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" environment cache on"
    fi
  fi
}

#@help ___dump0
# @command dump
# @summary Export the database as an executable shell script
# @group   database
# @returns shell commands (a restorable dump; pipe to a file)
# @example vpn-switch dump > backup.sh
# @see     restore
# @see     batch
#@end
___dump0() {
  local base="$VPN_SWITCH_BASE"

  # Header
  echo "# vpn-switch database dump"
  echo "# Generated: $(date '+%Y-%m-%d %H:%M:%S')"
  echo ""

  # Prologue - Transfer OLD database settings from .env/local/ (safe minimal set)
  echo "# Prologue - Transfer OLD database settings (safe minimal set for restore)"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" dumpenv prologue"
  echo ""

  # Body - Discover protocols dynamically and delegate to each (like ___list0, ___validate0)
  # NOTE: init command is NOT included in dump - it's implicit in restore
  for dir in "$base"/*; do
    # Skip symlinks (extension links like conf→wireguard/)
    [ -L "$dir" ] && continue
    [ -d "$dir" ] || continue
    proto=$(basename "$dir")

    # Skip pseudo-protocols (session/.session/.env/etc)
    is_pseudo_protocol "$proto" && continue

    # Delegate to protocol-specific dump
    echo "# ${proto} protocol dump"
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $proto dump"
    echo ""
  done

  # Session dump (special case - pseudo-protocol but included for named sessions)
  echo "# Session dump"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session dump"
  echo ""

  # Epilogue - Restore complete user environment (all customizations)
  echo "# Epilogue - Restore complete user environment from OLD database"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" dumpenv epilogue"
}

# _cat1 - Write stdin to file
#
# Args: $1 - filepath to write
#
# Reads stdin and writes to file with secure permissions
#
#@help _cat1
# @internal cat helper (emit a file under the terminal interpreter)
#@end
_cat1() {
  local filepath="$1"
  cat > "$filepath"
  $MODIFY_FILE_PERMS 0600 "$filepath"
}

# ___batch0 - Read stdin and execute as batch
#
# Output: vpn-switch commands to cat stdin to temp file, then execute batch
#
# Batch combinator - outputs multiple vpn-switch commands
#
#@help ___batch0
# @internal arity-0 sibling of 'batch' (reads commands from stdin)
#@end
___batch0() {
  local tempfile="$VPN_SWITCH_BASE/.tmp/batch.$$"

  cat <<EOF
"\$VPN_SWITCH_CONTEXT_SCRIPT" cat "$tempfile"
"\$VPN_SWITCH_CONTEXT_SCRIPT" batch "$tempfile" true
EOF
}

#@help __batch1
# @command batch <file>
# @summary Execute a file of vpn-switch commands line by line
# @group   database
# @param   file  file of commands to execute
# @returns shell commands (run each line)
# @example vpn-switch batch commands.txt
# @see     restore
#@end
__batch1() {
  local filepath="$1"

  # Validate file argument
  if [ -z "$filepath" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Usage: vpn-switch batch <filepath>\""
    return
  fi

  if [ ! -f "$filepath" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Batch file not found: $filepath\""
    return
  fi

  if [ ! -r "$filepath" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Batch file not readable: $filepath\""
    return
  fi

  # Output command to execute batch with filepath and no cleanup
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" batch \"$filepath\" false"
}

#@help _batch2
# @internal batch execution chain step
#@end
_batch2() {
  local filepath="$1"
  local cleanup="${2:-false}"
  local keep_going="${VPN_SWITCH_BATCH_KEEP_GOING:-0}"
  local base="$VPN_SWITCH_BASE"
  local success_count=0
  local fail_count=0

  # Save current batch2 interpreter to prevent nested batch double-cutting
  # Nested batches (e.g., phases sync -> phases lift) should use "cat" interpreter
  # to avoid applying cut -b3- multiple times, which causes truncated output
  local saved_batch_interpreter="${VPN_SWITCH_INTERPRETER_batch2:-cat}"
  export VPN_SWITCH_INTERPRETER_batch2="cat"

  # Get batch ID for exit code storage
  local batch_id
  batch_id=$(get_batch_id)
  if [ -z "$batch_id" ]; then
    trace_log "!" "_batch2" "Failed to allocate batch ID"
    export VPN_SWITCH_INTERPRETER_batch2="$saved_batch_interpreter"
    set +e
    return 1
  fi

  # Extract producer bit from EXIT_BITS
  # Last character should be the producer bit we just set
  local exit_bits="${VPN_SWITCH_CONTEXT_EXIT_BITS:-0}"
  local p_bit="${exit_bits##* }"
  # Handle case where EXIT_BITS might just be "0" or "1" (not space-separated)
  case "$p_bit" in
    0|1) ;;  # Valid bit
    *) p_bit=0 ;;  # Default to 0 if unclear
  esac

  # Calculate batch exit code: 128 + (p << 6) + batch_id
  local batch_exit=$((128 + (p_bit << 6) + batch_id))

  # Create batch file with enhanced format
  local batch_file="$VPN_SWITCH_BASE/.tmp/batch-exits/$batch_id"
  # Truncate existing file or create new one (round-robin allocation)
  if ! : > "$batch_file" 2>>"$LOG_FILE"; then
    echo "# Error: Failed to create batch file: $batch_file" >&2
    export VPN_SWITCH_INTERPRETER_batch2="$saved_batch_interpreter"
    set +e
    return 1
  fi

  trace_log "|" "_batch2" "Batch execution (batch_id=$batch_id, producer_bit=$p_bit)"

  # Note: .tmp and .env/local directories created by init

  # Read commands from file and execute them
  # Note: || [ -n "$line" ] prevents set -e from triggering on EOF
  # and allows processing the last line even without trailing newline
  while IFS= read -r line || [ -n "$line" ]; do
    # Pass through empty lines (preserves dump formatting)
    if [ -z "$line" ]; then
      echo ""
      continue
    fi

    # Reproduce comments to stdout (for dump), then skip processing
    case "$line" in
      \#*)
        echo "$line"
        continue
        ;;
    esac

    # Validate line starts with vpn-switch script context variable reference
    # Batch/dump files use the LITERAL string "$VPN_SWITCH_CONTEXT_SCRIPT" for portability
    # This ensures the dump is independent of the specific vpn-switch.sh path that created it
    #
    # Expected format: "$VPN_SWITCH_CONTEXT_SCRIPT" <command> <args...>
    # Example:        "$VPN_SWITCH_CONTEXT_SCRIPT" wireguard import /path/to/config.conf
    case "$line" in
      \"\$VPN_SWITCH_CONTEXT_SCRIPT\"\ *)
        # Valid: quoted variable reference (portable format used in dump files)
        # Strip the literal "$VPN_SWITCH_CONTEXT_SCRIPT" and extract arguments
        remaining_args="${line#\"\$VPN_SWITCH_CONTEXT_SCRIPT\"}"
        remaining_args="${remaining_args# }"
        ;;
      *)
        # Invalid line - not a valid batch command
        echo "# ✗ Invalid batch file syntax: $line" >&2
        echo "#   Expected: \"\$VPN_SWITCH_CONTEXT_SCRIPT\" <command> <args...>" >&2
        echo "#   Example:  \"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard import config.conf" >&2
        fail_count=$((fail_count + 1))

        # Stop on error unless keep-going mode
        if [ "$keep_going" != "1" ]; then
          echo "" >&2
          echo "# Batch execution stopped due to error (fail-fast mode)" >&2
          echo "# Summary: $success_count succeeded, $fail_count failed" >&2
          export VPN_SWITCH_INTERPRETER_batch2="$saved_batch_interpreter"
          set +e
          return 1
        fi
        continue
        ;;
    esac

    # Skip if remaining_args is empty (malformed command)
    if [ -z "$remaining_args" ]; then
      echo "# ✗ Empty command after stripping script prefix" >&2
      fail_count=$((fail_count + 1))
      continue
    fi

    # Execute vpn-switch commands via process_arguments()
    # This ensures each command gets its proper interpreter (terminal, combinator, or batch_combinator)
    # and tracing continues if VPN_SWITCH_TRACE_FILE is set
    trace_log "|" "_batch2" "Executing: $line"

    # Get function call for recording (resolve arguments to function name)
    local function_call=$(to_function_call "$ANCHOR_FUNCTIONS" $remaining_args)

    # Execute command
    eval "process_arguments $remaining_args"
    local exit_code=$?

    # Record result in batch file
    # Format: EXIT_CODE|function args|BATCH_REF
    if [ $exit_code -ge 128 ]; then
      # Nested batch: extract batch_id from exit code
      local nested_batch_id=$(( (exit_code - 128) & 0x3F ))
      echo "${exit_code}|${function_call}|${nested_batch_id}" >> "$batch_file"
    else
      # Regular exit
      echo "${exit_code}|${function_call}|" >> "$batch_file"
    fi

    # Track success/failure using recursive batch checker
    if ! check_batch_success "$exit_code"; then
      trace_log "!" "_batch2" "Failed (exit code: $exit_code)"
      fail_count=$((fail_count + 1))

      # Stop on error unless keep-going mode
      if [ "$keep_going" != "1" ]; then
        echo "" >&2
        echo "# Batch execution stopped due to error (fail-fast mode)" >&2
        echo "# Summary: $success_count succeeded, $fail_count failed" >&2
        export VPN_SWITCH_INTERPRETER_batch2="$saved_batch_interpreter"
        set +e  # Ensure set +e before returning batch code
        return "$batch_exit"
      fi
    else
      trace_log "|" "_batch2" "Success"
      success_count=$((success_count + 1))
    fi
  done < "$filepath"

  trace_log "|" "_batch2" "While loop completed"

  # Summary
  trace_log "|" "_batch2" "Summary: $success_count succeeded, $fail_count failed"

  # Show EXIT_BITS structure
  if [ -n "${VPN_SWITCH_CONTEXT_EXIT_BITS:-}" ]; then
    trace_log "|" "_batch2" "EXIT_BITS structure: ${VPN_SWITCH_CONTEXT_EXIT_BITS}"
  fi

  trace_log "|" "_batch2" "========================================"

  # Clean up temp file only on success (keep on failure for debugging)
  if [ $fail_count -eq 0 ] && [ "$cleanup" = "true" ]; then
    $MODIFY_FILE_REMOVE "$filepath"
  fi

  # Note: batch-exits file NOT cleaned up - retained for diagnostics
  # Round-robin allocation naturally overwrites old batch files

  trace_log "|" "_batch2" "Returning batch_exit=$batch_exit"

  # Restore original batch2 interpreter before returning
  export VPN_SWITCH_INTERPRETER_batch2="$saved_batch_interpreter"

  # CRITICAL: Ensure set +e before returning batch code >= 128
  # This prevents shell exit when returning non-zero exit codes
  set +e

  # Return batch exit code (128 + (p << 6) + batch_id)
  # This allows the caller to decode results using: vpn-switch debug-exit $?
  return "$batch_exit"
}

#@help __restore1
# @command restore <file>
# @summary Restore the database from a previously-generated dump file
# @group   database
# @param   file  dump file produced by 'dump'
# @returns shell commands (replay the dump)
# @example vpn-switch restore backup.sh
# @see     dump
#@end
__restore1() {
  local filepath="$1"

  # Validate file argument
  if [ -z "$filepath" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Usage: vpn-switch restore <filepath>\""
    return
  fi

  if [ ! -f "$filepath" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Restore file not found: $filepath\""
    return
  fi

  if [ ! -r "$filepath" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Restore file not readable: $filepath\""
    return
  fi

  # Set keep-going mode for batch execution
  #
  # Keep-going mode ensures restore completes even if some commands fail.
  # Example: Duplicate imports fail, but categories/links/sessions still process.
  #
  export VPN_SWITCH_BATCH_KEEP_GOING=1

  # Output batch command for interpreter to execute
  #
  # Note: Database must already be initialized (via bootstrap/init)
  # If database doesn't exist, main() will error before reaching here
  #
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" batch \"$filepath\""
}

#@help _printenv0
# @command printenv [<VAR>]
# @summary Show all effective environment variables, or just one
# @group   configuration
# @param   VAR  restrict output to a single variable
# @returns the effective environment
# @example vpn-switch printenv
# @see     getenv
#@end
_printenv0() {
  cat <<EOF
echo "# =============================================================================="
echo "# Environment variables in isolated context:"
echo "# (sorted alphabetically)"
echo ""
printenv | sort
echo "# =============================================================================="
EOF
}

