# inspect.sh - Dynamically loaded inspect module
# Generated by extract-modules-v2.sh
# DO NOT EDIT - This file is auto-generated

#@help _database_enumerate0
# @internal database enumeration helper for 'inspect'
#@end
_database_enumerate0() {
  # Terminal function - Database Structure Enumeration
  # Generation-time pattern: discover now, output only concrete comments

  echo "# Database Structure"
  echo "#"

  # Base directory
  if [ -d "$VPN_SWITCH_BASE" ]; then
    local base_perms=$(ls -ld "$VPN_SWITCH_BASE" 2>>"$LOG_FILE" | awk '{print $1}')
    echo "# $VPN_SWITCH_BASE ($base_perms)"
  else
    echo "# $VPN_SWITCH_BASE (NOT FOUND)"
  fi

  # Enumerate configured directories
  echo "$VPN_SWITCH_INIT_DIR_CONFIG" | while IFS=: read -r dir mode exec_flag; do
    [ -z "$dir" ] && continue
    local full_path="$VPN_SWITCH_BASE/$dir"
    if [ -d "$full_path" ]; then
      local perms=$(ls -ld "$full_path" 2>>"$LOG_FILE" | awk '{print $1}')
      local count=$(ls -1 "$full_path" 2>>"$LOG_FILE" | wc -l | tr -d ' ')
      echo "#   $dir/ ($perms, $count items)"
    elif [ -e "$full_path" ]; then
      echo "#   $dir (exists but not a directory)"
    else
      echo "#   $dir/ (missing)"
    fi
  done
}

#@help ___environment_inspect0
# @command environment inspect
# @summary Show the environment resolution chain (default -> local -> cache)
# @group   configuration
# @returns the environment resolution report
# @example vpn-switch environment inspect
#@end
___environment_inspect0() {
  # Batch combinator - compose environment configuration inspection

  echo "# ## Environment Configuration"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" printenv"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" database enumerate"
}

#@help _system_inspect0
# @internal system portion of 'inspect'
#@end
_system_inspect0() {
  # Execute system inspection at generation time and capture results

  # System Info - execute now
  local uname_result="⚠ uname not available"
  if command -v uname >/dev/null 2>&1; then
    uname_result=$(uname -a)
  fi

  # Network Interfaces - execute platform-specific command now
  local netif_result
  netif_result=$($EXAMINE_NETWORK_INTERFACES 2>&1) || netif_result="⚠ Failed to retrieve network interfaces"

  # Routing Table - execute platform-specific command now
  local route_result
  route_result=$($EXAMINE_NETWORK_ROUTES 2>&1) || route_result="⚠ Failed to retrieve routing table"

  # DNS Configuration - read now
  local dns_result="⚠ Cannot read /etc/resolv.conf"
  if [ -r /etc/resolv.conf ]; then
    dns_result=$(cat /etc/resolv.conf)
  fi

  # Firewall Rules - execute now if available
  local firewall_result="⚠ pf not available"
  if command -v "${VPN_SWITCH_PFCTL}" >/dev/null 2>&1; then
    if "${VPN_SWITCH_PFCTL}" -sr >/dev/null 2>&1; then
      firewall_result=$("${VPN_SWITCH_PFCTL}" -sr 2>&1)
      local vpn_remotes_table=$("${VPN_SWITCH_PFCTL}" -t vpn_remotes -T show 2>&1) || vpn_remotes_table="⚠ vpn_remotes table not found"
      firewall_result="${firewall_result}

${vpn_remotes_table}"
    else
      firewall_result="⚠ pf available but permission denied (need root?)"
    fi
  fi

  # Kernel Modules - execute platform-specific command now
  local kmod_result
  kmod_result=$($EXAMINE_KMOD_LIST | grep -E '(wg|if_tun|if_tap)' 2>&1) || kmod_result="(no VPN modules loaded)"

  # Output complete system inspection document as comments
  # Prefix multi-line results with comment markers
  uname_result=$(echo "$uname_result" | sed 's/^/# /')
  netif_result=$(echo "$netif_result" | sed 's/^/# /')
  route_result=$(echo "$route_result" | sed 's/^/# /')
  dns_result=$(echo "$dns_result" | sed 's/^/# /')
  firewall_result=$(echo "$firewall_result" | sed 's/^/# /')
  kmod_result=$(echo "$kmod_result" | sed 's/^/# /')

  cat <<EOF
# ## System Configuration
#
# ### System Info
$uname_result
#
# ### Network Interfaces
$netif_result
#
# ### Routing Table
$route_result
#
# ### DNS Configuration
$dns_result
#
# ### Firewall Rules (pf)
$firewall_result
#
# ### Kernel Modules
$kmod_result
EOF
}

#@help _logs_inspect0
# @internal logs portion of 'inspect'
#@end
_logs_inspect0() {
  # Terminal function - inspect logs and traces
  # Generation-time pattern: discover now, output only concrete comments
  local today=$(date +%Y-%m-%d)
  local log_dir="$VPN_SWITCH_BASE/.log/$today"
  local trace_dir="$VPN_SWITCH_BASE/.trace/$today"

  echo "# Recent Logs and Traces"
  echo "#"
  echo "# Retention Settings:"
  echo "#   Log retention: ${VPN_SWITCH_RETENTION_DAYS_LOG:-disabled} days"
  echo "#   Trace retention: ${VPN_SWITCH_RETENTION_DAYS_TRACE:-disabled} days"
  echo "#"

  # Today's logs
  echo "# Today's Logs ($today):"
  if [ -d "$log_dir" ]; then
    echo "#   Directory: $log_dir"
    local log_count=$(ls -1 "$log_dir" 2>>"$LOG_FILE" | wc -l | tr -d ' ')
    echo "#   Files: $log_count"

    # Show recent log files
    local recent_logs=$(ls -1t "$log_dir" 2>>"$LOG_FILE" | head -5)
    if [ -n "$recent_logs" ]; then
      echo "#   Recent:"
      echo "$recent_logs" | while read -r logfile; do
        echo "#     $logfile"
      done
    fi

    # Check for errors in today's logs (only .log files, not .trace)
    local error_count=$(grep -h -c -E 'error|fail|cannot' "$log_dir"/*.log 2>>"$LOG_FILE" | awk '{s+=$1} END {print s+0}')
    if [ "$error_count" -gt 0 ]; then
      echo "#   Errors found: $error_count"
    fi
  else
    echo "#   (no logs for today)"
  fi
  echo "#"

  # Today's traces (stored in .log/$today/*.trace)
  echo "# Today's Traces ($today):"
  if [ -d "$log_dir" ]; then
    local trace_count=$(ls -1 "$log_dir"/*.trace 2>>"$LOG_FILE" | wc -l | tr -d ' ')
    if [ "$trace_count" -gt 0 ]; then
      echo "#   Directory: $log_dir"
      echo "#   Files: $trace_count"

      # Show recent trace files
      local recent_traces=$(ls -1t "$log_dir"/*.trace 2>>"$LOG_FILE" | head -5 | xargs -n1 basename)
      if [ -n "$recent_traces" ]; then
        echo "#   Recent:"
        echo "$recent_traces" | while read -r tracefile; do
          echo "#     $tracefile"
        done
      fi
    else
      echo "#   (no traces for today)"
    fi
  else
    echo "#   (no log directory for today)"
  fi
  echo "#"

  # Log history - last 7 days
  echo "# Log History (last 7 days):"
  local log_base="$VPN_SWITCH_BASE/.log"
  if [ -d "$log_base" ]; then
    local found=0
    for dir in $(find "$log_base" -maxdepth 1 -type d -name '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]' 2>>"$LOG_FILE" | sort -r | head -7); do
      found=1
      local date_dir=$(basename "$dir")
      local count=$(ls -1 "$dir" 2>>"$LOG_FILE" | wc -l | tr -d ' ')
      echo "#   $date_dir: $count files"
    done
    if [ "$found" -eq 0 ]; then
      echo "#   (no log history)"
    fi
  else
    echo "#   (no log directory)"
  fi
}

#@help _phases_inspect0
# @internal phases portion of 'inspect'
#@end
_phases_inspect0() {
  # Terminal function - Phase Configuration Inspection
  # Generation-time pattern: discover now, output only concrete comments

  echo "# Phase Configuration"
  echo "#"
  echo "# Inspect phases: ${VPN_SWITCH_PHASES_INSPECT:-<none>}"
  # Default phase-profile symlink (load-bearing for @-less phase specs)
  if [ -L "$VPN_SWITCH_BASE/.include/phase/default" ]; then
    echo "# Default profile: default -> $($EXAMINE_LINK_TARGET "$VPN_SWITCH_BASE/.include/phase/default" 2>/dev/null)"
  else
    echo "# Default profile: ⚠ MISSING symlink .include/phase/default"
  fi
  echo "#"

  # Try to find an active session to build context from
  local session_dir=""
  local session_protocol=""
  for session_candidate in "$VPN_SWITCH_BASE/.session"/*; do
    [ -d "$session_candidate" ] || continue
    if [ -f "$session_candidate/protocol" ] && [ -f "$session_candidate/interface" ]; then
      session_dir="$session_candidate"
      session_protocol=$(cat "$session_candidate/protocol" 2>>"$LOG_FILE")
      break
    fi
  done

  # Build context if we have a session
  if [ -n "$session_dir" ]; then
    local session_id=$(basename "$session_dir")
    local interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "")
    local config_file=$(cat "$session_dir/original" 2>>"$LOG_FILE" || echo "")

    # Find the actual config file in the session directory
    local session_config=""
    if [ "$session_protocol" = "wireguard" ]; then
      session_config="$session_dir/${interface}.conf"
    elif [ "$session_protocol" = "openvpn" ]; then
      session_config="$session_dir/config.ovpn"
    fi

    # Extract DNS and remote IPs from config
    local dns_server=""
    local remote_ips=""

    if [ -f "$session_config" ]; then
      if [ "$session_protocol" = "wireguard" ]; then
        # WireGuard: Extract DNS from config
        dns_server=$(grep '^DNS' "$session_config" | head -1 | awk -F= '{print $2}' | tr -d ' ')
        # Extract Endpoint IPs
        remote_ips=$(awk '/^\[Peer\]/,/^$/ {
          if ($1 == "Endpoint") {
            split($3, parts, ":")
            print parts[1]
          }
        }' "$session_config" | tr '\n' ' ')
      elif [ "$session_protocol" = "openvpn" ]; then
        # OpenVPN: Extract DNS from dhcp-option
        dns_server=$(grep -i '^dhcp-option DNS' "$session_config" | head -1 | awk '{print $3}')
        # Extract remote IPs
        remote_ips=$(awk '/^remote / { print $2 }' "$session_config" | tr '\n' ' ')
      fi
    fi

    # Build context similar to connect generation
    VPN_SWITCH_CONTEXT_CONNECT="
export VPN_SESSION_DIR=\"$session_dir\"
export VPN_SESSION_PID=\"$session_id\"
export VPN_CONFIG_FILE=\"$config_file\"
export VPN_ORIGINAL_CONFIG=\"$config_file\"
export VPN_ORIGINAL_CONFIG_RELATIVE=\"$config_file\"
export VPN_INTERFACE=\"$interface\"
export VPN_DNS_SERVER=\"$dns_server\"
export VPN_REMOTE_IPS=\"$remote_ips\"
export VPN_GATEWAY=\"\"
export VPN_PROTOCOL=\"$session_protocol\"
export VPN_PHASES_CONNECT=\"$VPN_SWITCH_PHASES_CONNECT\"
export VPN_PHASES_DISCONNECT=\"$VPN_SWITCH_PHASES_DISCONNECT\"
export VPN_PHASES_INSPECT=\"$VPN_SWITCH_PHASES_INSPECT\"
"
    export VPN_SWITCH_CONTEXT_CONNECT
  fi

  # Discover protocols from VPN_SWITCH_BASE (canonical source)
  local found_protocol=0
  for protocol_dir in "$VPN_SWITCH_BASE"/*; do
    [ -L "$protocol_dir" ] && continue
    [ -d "$protocol_dir" ] || continue
    local protocol=$(basename "$protocol_dir")

    # Skip pseudo-protocols using helper (consistent with other functions)
    is_pseudo_protocol "$protocol" && continue

    # If we have an active session, only inspect that protocol
    # This prevents showing wrong data (e.g., WireGuard data in OpenVPN section)
    if [ -n "$session_protocol" ] && [ "$protocol" != "$session_protocol" ]; then
      continue
    fi

    # Check if protocol has inspect phase directory
    local phase_dir="$VPN_SWITCH_BASE/.include/phase/$protocol"
    local inspect_dir="$phase_dir/inspect"
    [ ! -d "$inspect_dir" ] && continue

    found_protocol=1
    echo "# Protocol: $protocol"
    echo "#"

    # Inspect phases (single pass)
    if [ -n "$VPN_SWITCH_PHASES_INSPECT" ]; then
      # Generate shell code with prologue and phases
      local prologue_script="$inspect_dir/prologue.sh"
      if [ -f "$prologue_script" ]; then
        run_env -- sh "$prologue_script"
      fi

      for phase in $VPN_SWITCH_PHASES_INSPECT; do
        local phase_script="$inspect_dir/$phase.sh"
        if [ -f "$phase_script" ]; then
          run_env -- sh "$phase_script"
        else
          echo "#   $phase [template not found]"
        fi
      done
    else
      echo "#   (no inspect phases configured)"
    fi
    echo "#"
  done

  if [ "$found_protocol" -eq 0 ]; then
    echo "# (no protocols with inspect phase directories found)"
  fi
}

#@help _summary_inspect0
# @internal summary portion of 'inspect'
#@end
_summary_inspect0() {
  # Terminal function - Inspection Summary
  # Generation-time pattern: discover now, output only concrete comments

  # Discover available protocols at generation time
  local protocols=""
  for protocol_dir in "$VPN_SWITCH_BASE"/*; do
    [ -L "$protocol_dir" ] && continue
    [ -d "$protocol_dir" ] || continue
    local protocol=$(basename "$protocol_dir")
    is_pseudo_protocol "$protocol" && continue
    protocols="${protocols:+$protocols, }$protocol"
  done
  [ -z "$protocols" ] && protocols="none"

  # Count active sessions
  local session_count=0
  if [ -d "$VPN_SWITCH_BASE/.session" ]; then
    session_count=$(ls -1d "$VPN_SWITCH_BASE/.session"/*/ 2>>"$LOG_FILE" | wc -l | tr -d ' ') || session_count=0
  fi

  cat <<EOF
#
# ================================================================================
# Summary
# ================================================================================
#
# Complete diagnostic captured.
#
# Database: $VPN_SWITCH_BASE
# Protocols available: $protocols
# Active sessions: $session_count
#
# To share this diagnostic:
#   1. Save output: vpn-switch inspect > diagnostic.txt
#   2. Share diagnostic.txt with support or AI assistant
#
# For offline debugging:
#   - Session scripts are in .session/<PID>/
#   - Phase templates are in .include/phase/
#   - Logs are in .log/<date>/
#
EOF
}

#@help _prologue_inspect0
# @internal prologue portion of 'inspect'
#@end
_prologue_inspect0() {
  # Define command variables from environment (hardcoded at generation time)
  echo "pfctl=\"\${VPN_SWITCH_PFCTL:-pfctl}\""
  echo "wg_quick=\"\$VPN_SWITCH_BINARY_wireguard\""
  echo "openvpn=\"\$VPN_SWITCH_BINARY_openvpn\""

  # Standard utilities
  echo "cat_cmd=\"\${VPN_SWITCH_CAT:-cat}\""
  echo "echo_cmd=\"\${VPN_SWITCH_ECHO:-echo}\""
  echo "chmod_cmd=\"\${VPN_SWITCH_CHMOD:-chmod}\""
}

#@help ___inspect0
# @command inspect
# @summary Full descriptive state dump (sessions, configs, phases, system)
# @group   diagnostics
# @returns diagnostic snapshot (always exits 0)
# @example vpn-switch inspect
# @see     validate
#@end
___inspect0() {
  # Save current settings (at generation time)
  ansi_original="${VPN_SWITCH_DISPLAY_ANSI}"
  cache_was_on=""
  if [ -n "${VPN_SWITCH_INTERPRETER_environment_cache}" ]; then
    cache_was_on="1"
  fi

  # Disable ANSI if currently enabled
  if [ "${VPN_SWITCH_DISPLAY_ANSI}" != "0" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" setenv VPN_SWITCH_DISPLAY_ANSI 0"
  fi

  # Enable cache for inspect (performance optimization)
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" environment cache on"

  # Delegate to all inspection functions (prologue FIRST!)
  # Note: Nested batch combinators (environment/wireguard/openvpn inspect) handle their own interpreter overrides
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" prologue inspect"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" environment inspect"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" system inspect"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" status"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard inspect"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn inspect"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session inspect"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" phases inspect"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" logs inspect"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" summary inspect"

  # Restore ANSI to original value if we changed it
  if [ "${ansi_original}" != "0" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" setenv VPN_SWITCH_DISPLAY_ANSI ${ansi_original}"
  fi

  # Re-enable cache if it was enabled before
  if [ -n "$cache_was_on" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" environment cache on"
  fi
}

