# openvpn.sh - Dynamically loaded openvpn module
# Generated by extract-modules-v2.sh
# DO NOT EDIT - This file is auto-generated

#@help __openvpn_start0
# @internal arity-0 sibling of 'openvpn start'
#@end
__openvpn_start0() {
  local protocol_dir="$VPN_SWITCH_BASE/openvpn"

  # Use resolve_default_or_random to pick config
  # Pattern: "*.ovpn" to match OpenVPN configs
  local config
  config=$(resolve_default_or_random "$protocol_dir" "*.ovpn")

  # Check if any configs were found
  if [ -z "$config" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No OpenVPN configs found in openvpn/\""
    return
  fi

  # Delegate to start1 with selected config
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn start $config"
}

#@help __openvpn_start1
# @command openvpn start [<group>]
# @summary Start an OpenVPN tunnel; with no argument, use the default or a random config
# @group   openvpn
# @param   group  config group, config name or alias; omit for the default-or-random config
# @returns connect commands (run under the connect interpreter)
# @example vpn-switch openvpn start work
# @example vpn-switch openvpn start
# @see     openvpn stop
# @see     session save
#@end
__openvpn_start1() {
  local object="$1"
  local protocol_dir="$VPN_SWITCH_BASE/openvpn"
  local object_path="$protocol_dir/$object"
  local config=""
  local config_path=""

  # Case 1: Directory (category) - pick a config from it
  if [ -d "$object_path" ]; then
    local category="$object"
    local category_dir="$object_path"

    # Resolve config file from category
    config=$(resolve_default_or_random "$category_dir" "*")

    # Check if category is empty
    if [ -z "$config" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Category '$category' is empty (no configs found)\""
      return
    fi

    # Follow symlinks to get actual config file (with loop detection)
    if ! config=$(follow_symlinks_safe "$category_dir" "$config"); then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Symlink loop detected: $config\""
      return
    fi

    # Resolve to full path
    config_path="$protocol_dir/$config"

    # Validate config file exists
    if [ ! -f "$config_path" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Config file not found: $config_path\""
      return
    fi

  # Case 2: File or symlink - use directly
  elif [ -f "$object_path" ] || [ -L "$object_path" ]; then
    config="$object"

    # Follow symlinks if needed (with loop detection)
    if ! config=$(follow_symlinks_safe "$protocol_dir" "$config"); then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Symlink loop detected: $config\""
      return
    fi

    # Resolve to full path
    config_path="$protocol_dir/$config"

    # Validate config file exists
    if [ ! -f "$config_path" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Config file not found: $config_path\""
      return
    fi

  # Case 3: Try with extension if exact match failed
  elif [ -f "$object_path.ovpn" ] || [ -L "$object_path.ovpn" ]; then
    config="$object.ovpn"

    # Follow symlinks if needed (with loop detection)
    if ! config=$(follow_symlinks_safe "$protocol_dir" "$config"); then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Symlink loop detected: $config\""
      return
    fi

    # Resolve to full path
    config_path="$protocol_dir/$config"

    # Validate config file exists after following symlinks
    if [ ! -f "$config_path" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Config file not found: $config_path \\(after following symlinks\\)\""
      return
    fi

  else
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Not found in openvpn/: $object \\(must be a category, config file, or symlink\\)\""
    return
  fi

  # Delegate to create (no log - command inspection shows the resolved config!)
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn create \"$config\""
}

#@help ___openvpn_create1
# @internal session-create chain step for 'openvpn start'
#@end
___openvpn_create1() {
  local config="$1"
  local config_path="$VPN_SWITCH_BASE/openvpn/$config"

  # Check and create minimal session (PID only)
  check_and_create_session "$VPN_SWITCH_INTERFACE_openvpn" || return

  local session_pid="$$"

  # Output batch with comment + commands (KEEP_GOING=0)
  cat <<EOF
# Created session $session_pid
"\$VPN_SWITCH_CONTEXT_SCRIPT" session populate "$session_pid" "openvpn" "$VPN_SWITCH_INTERFACE_openvpn"
"\$VPN_SWITCH_CONTEXT_SCRIPT" openvpn patch "$session_pid" "$config_path"
"\$VPN_SWITCH_CONTEXT_SCRIPT" openvpn configure "$session_pid"
"\$VPN_SWITCH_CONTEXT_SCRIPT" openvpn connect "$session_pid"
EOF
}

#@help _openvpn_patch2
# @internal session-scoped patch variant (used during connect)
#@end
_openvpn_patch2() {
  local session_pid="$1"
  local config_path="$2"  # UNPATCHED original config
  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"
  local interface="$VPN_SWITCH_INTERFACE_openvpn"
  local patched_config="$session_dir/${interface}.ovpn"

  # Output shell commands (terminal function - normal form)
  cat <<EOF
# Record original config
echo "$config_path" > "$session_dir/original"
$MODIFY_FILE_PERMS 0640 "$session_dir/original"

# Copy and patch config
$MODIFY_FILE_COPY "$config_path" "$patched_config"
$MODIFY_FILE_PERMS 0640 "$patched_config"

# Remove existing up/down scripts (DNS handled by DNS phase)
$MODIFY_FILE_SED_INPLACE '/^up /d' "$patched_config"
$MODIFY_FILE_SED_INPLACE '/^down /d' "$patched_config"

# Patch OpenVPN config: add daemon mode, writepid, interface
echo >> "$patched_config"
echo "daemon" >> "$patched_config"
echo "writepid $session_dir/pid" >> "$patched_config"
echo "dev $interface" >> "$patched_config"

# Set read-only permissions
$MODIFY_FILE_PERMS 0640 "$patched_config"
EOF
}

#@help _openvpn_configure1
# @internal configure chain step (generates connect/disconnect scripts)
#@end
_openvpn_configure1() {
  local session_pid="$1"
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  # Output shell commands to configure session links
  cat <<EOF
# Create session protocol directory
$MODIFY_DIR_CREATE "$session_proto_dir"
$MODIFY_FILE_PERMS 0750 "$session_proto_dir"

# Update latest session link (for session save/resume)
# NOTE: Using ln -sfn instead of ln -sf because when the existing symlink
# points to a directory (which .session/<PID> is), POSIX ln -sf will
# dereference and create the new link inside the target directory instead
# of overwriting the symlink. The -n flag prevents dereferencing.
$MODIFY_LINK_FORCE "../.session/$session_pid" "$session_proto_dir/latest"
EOF
}
#@help _openvpn_connect1
# @internal connect chain step (emits the connect commands)
#@end
_openvpn_connect1() {
  local session_id="$1"
  local session_dir="$VPN_SWITCH_BASE/.session/$session_id"
  local interface="${VPN_SWITCH_INTERFACE_openvpn}"
  local patched_config="$session_dir/${interface}.ovpn"
  local connect_script="$session_dir/connect.sh"
  local disconnect_script="$session_dir/disconnect.sh"
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  # Validate session exists
  if [ ! -d "$session_dir" ]; then
    generate_error "Session not found: $session_id"
    return 0
  fi

  # Validate patched config exists
  if [ ! -f "$patched_config" ]; then
    generate_error "Patched config not found in session $session_id: $patched_config"
    return 0
  fi

  # Read original config path from session metadata
  local original_config=$(cat "$session_dir/original" 2>>"$LOG_FILE" || echo "unknown")

  # Compute relative path from session directory to original config
  # Session is at: $VPN_SWITCH_BASE/.session/$session_id/
  # Original is at: $VPN_SWITCH_BASE/openvpn/... or $VPN_SWITCH_BASE/openvpn/group/...
  # Relative path: ../../openvpn/... or ../../openvpn/group/...
  local original_config_relative="${original_config#$VPN_SWITCH_BASE/}"
  original_config_relative="../../$original_config_relative"

  # Extract DNS server for firewall table (from patched config)
  # OpenVPN configs may not have explicit DNS, so we extract from dhcp-option DNS directives
  local dns_server
  dns_server=$(grep -i '^dhcp-option DNS' "$patched_config" | head -1 | awk '{print $3}')
  dns_server="${dns_server:-${VPN_SWITCH_DNS_openvpn:-}}"  # No implicit default - must be configured

  # Extract remote server IPs for firewall table (from patched config)
  local remote_ips=$(get_openvpn_remotes "$patched_config")

  # Get phase lists
  local phases_connect="${VPN_SWITCH_PHASES_CONNECT:-firewall vpn dns}"
  local phases_disconnect="${VPN_SWITCH_PHASES_DISCONNECT:-dns vpn firewall}"

  # Phase script directory
  local phase_dir="$VPN_SWITCH_BASE/.include/phase/openvpn"

  # Strict phase resolution (least surprise): every phase in the list MUST
  # resolve to a script. A phase that does not resolve is a configuration error
  # and aborts generation — it is never silently dropped (which previously could
  # remove e.g. the firewall phase on a typo or a missing @profile). To skip a
  # phase on purpose, use the ':none' backend. Supports :variant@profile syntax.
  local protocol=$(basename -- "$phase_dir")  # Extract protocol from phase_dir
  for phase_spec in $phases_connect; do
    if ! resolve_phase_script "$phase_spec" "$protocol" "connect" "$VPN_SWITCH_BASE" >/dev/null 2>&1; then
      generate_error "Phase '$phase_spec' (connect) does not resolve" "Fix VPN_SWITCH_PHASES_CONNECT or add the backend; use ':none' to skip a phase"
      return 0
    fi
  done
  for phase_spec in $phases_disconnect; do
    if ! resolve_phase_script "$phase_spec" "$protocol" "disconnect" "$VPN_SWITCH_BASE" >/dev/null 2>&1; then
      generate_error "Phase '$phase_spec' (disconnect) does not resolve" "Fix VPN_SWITCH_PHASES_DISCONNECT or add the backend; use ':none' to skip a phase"
      return 0
    fi
  done

  # Build VPN_SWITCH_CONTEXT_CONNECT (new context variable system)
  # Gateway for OpenVPN is the DNS server
  local gateway="$dns_server"
  VPN_SWITCH_CONTEXT_CONNECT="
export VPN_SESSION_DIR=\"$session_dir\"
export VPN_SESSION_PID=\"$session_id\"
export VPN_CONFIG_FILE=\"$patched_config\"
export VPN_ORIGINAL_CONFIG=\"$original_config\"
export VPN_ORIGINAL_CONFIG_RELATIVE=\"$original_config_relative\"
export VPN_INTERFACE=\"$VPN_SWITCH_INTERFACE_openvpn\"
export VPN_DNS_SERVER=\"$dns_server\"
export VPN_REMOTE_IPS=\"$remote_ips\"
export VPN_GATEWAY=\"$gateway\"
export VPN_PROTOCOL=\"openvpn\"
export VPN_PHASES_CONNECT=\"$phases_connect\"
export VPN_PHASES_DISCONNECT=\"$phases_disconnect\"
"
  export VPN_SWITCH_CONTEXT_CONNECT

  # Generate connect.sh using phase-based approach
  {
    # Generate prologue
    if [ -f "$phase_dir/connect/prologue.sh" ]; then
      run_env -- sh "$phase_dir/connect/prologue.sh"
    else
      generate_error "Prologue not found: $phase_dir/connect/prologue.sh"
      return 0
    fi

    # Generate phases (verify → prepare → execute for each phase)
    for phase_spec in $phases_connect; do
      local phase_script=$(resolve_phase_script "$phase_spec" "$protocol" "connect" "$VPN_SWITCH_BASE")
      if [ -n "$phase_script" ] && [ -f "$phase_script" ]; then
        run_env -- sh "$phase_script" verify
        run_env -- sh "$phase_script" prepare
        run_env -- sh "$phase_script" execute
      fi
      # Pre-flight above guarantees every phase resolves (missing => error, not skip)
    done
  } > "$connect_script"

  $MODIFY_FILE_PERMS 0750 "$connect_script"

  # Mark interface ownership for is_session_alive(). Unlike WireGuard, OpenVPN
  # exposes no peer identity on the interface, so the claim cannot self-validate
  # against a loaded fingerprint here; drift is instead prevented by the
  # ownership release in disconnect.sh (below) and reconciled by is_session_alive's
  # process check plus 'vpn-switch session refresh'.
  {
    echo ""
    echo "# Update latest-interface symlink (marks interface ownership)"
    echo "$MODIFY_LINK_FORCE \"../.session/$session_id\" \"$session_proto_dir/latest-$interface\""
  } >> "$connect_script"

  # Generate disconnect.sh using phase-based approach
  {
    # Generate prologue
    if [ -f "$phase_dir/disconnect/prologue.sh" ]; then
      run_env -- sh "$phase_dir/disconnect/prologue.sh"
    else
      generate_error "Prologue not found: $phase_dir/disconnect/prologue.sh"
      return 0
    fi

    # Generate phases (verify → prepare → execute for each phase)
    for phase_spec in $phases_disconnect; do
      local phase_script=$(resolve_phase_script "$phase_spec" "$protocol" "disconnect" "$VPN_SWITCH_BASE")
      if [ -n "$phase_script" ] && [ -f "$phase_script" ]; then
        run_env -- sh "$phase_script" verify
        run_env -- sh "$phase_script" prepare
        run_env -- sh "$phase_script" execute
      fi
      # Pre-flight above guarantees every phase resolves (missing => error, not skip)
    done
  } > "$disconnect_script"

  # Release interface ownership: drop latest-$interface if it still points to
  # this session, so a stopped session never keeps claiming the interface.
  {
    echo ""
    echo "# Release interface ownership (only if still ours)"
    cat <<EOF
if [ -L "$session_proto_dir/latest-$interface" ] && [ "\$($EXAMINE_LINK_TARGET "$session_proto_dir/latest-$interface" 2>/dev/null)" = "../.session/$session_id" ]; then
  $MODIFY_LINK_REMOVE "$session_proto_dir/latest-$interface"
  echo "# Interface ownership released: $interface (was session $session_id)" >&2
fi
EOF
  } >> "$disconnect_script"

  $MODIFY_FILE_PERMS 0750 "$disconnect_script"

  # Output connect script for immediate execution
  cat "$connect_script"
}

#@help ___openvpn_stop0
# @internal batch sibling of 'openvpn stop' (stops all OpenVPN sessions)
#@end
___openvpn_stop0() {
  local session_base="$VPN_SWITCH_BASE/.session"

  if [ ! -d "$session_base" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"No OpenVPN sessions to stop\""
    return 0
  fi

  # Find all openvpn sessions
  local found_session=0
  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue

    local session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE")

    # Skip non-openvpn sessions
    [ "$session_protocol" != "openvpn" ] && continue

    # Skip inactive sessions (not running)
    is_session_alive "$session_dir" || continue

    local session_interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE")

    # Legacy: infer interface if missing
    if [ -z "$session_interface" ]; then
      session_interface="${VPN_SWITCH_INTERFACE_openvpn:-tun0}"
    fi

    # Script path uses literal variable reference for portability
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn disconnect $session_interface"
    found_session=1
  done

  # If no OpenVPN sessions were found, output log message
  if [ "$found_session" -eq 0 ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"No OpenVPN sessions to stop\""
  fi
}

#@help __openvpn_stop1
# @command openvpn stop [<interface>]
# @summary Stop OpenVPN sessions, or one specific interface
# @group   openvpn
# @param   interface  interface to stop (default: all OpenVPN sessions)
# @returns disconnect commands
# @example vpn-switch openvpn stop
# @see     openvpn start
#@end
__openvpn_stop1() {
  local interface="$1"

  # Validate session exists
  local session_pid=$(find_session_by_interface "$interface")

  if [ -z "$session_pid" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No openvpn session found for interface: $interface\""
    return
  fi

  # Output disconnect command
  # Script path uses literal variable reference for portability
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn disconnect $interface"
}

#@help _openvpn_disconnect1
# @internal disconnect chain step (emits the disconnect commands)
#@end
_openvpn_disconnect1() {
  local interface="$1"

  # Find session by interface name
  local session_pid=$(find_session_by_interface "$interface")

  if [ -z "$session_pid" ]; then
    generate_error "No vpn-switch session found for interface: $interface"
    return 0
  fi

  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"
  local disconnect_script="$session_dir/disconnect.sh"

  # Build VPN_SWITCH_CONTEXT_DISCONNECT (new context variable system)
  VPN_SWITCH_CONTEXT_DISCONNECT="
export VPN_SESSION_DIR='$session_dir'
export VPN_SESSION_PID='$session_pid'
export VPN_INTERFACE='$interface'
export VPN_PROTOCOL='openvpn'
"
  export VPN_SWITCH_CONTEXT_DISCONNECT

  # If disconnect.sh exists (phase-based sessions), use it
  if [ -f "$disconnect_script" ]; then
    cat "$disconnect_script"
  else
    # Legacy fallback for old sessions created before phase-based implementation
    local original_config=$(cat "$session_dir/original" 2>>"$LOG_FILE" || echo "unknown")
    local original_config_relative="${original_config#$VPN_SWITCH_BASE/}"
    original_config_relative="../../$original_config_relative"

    local pfctl="${VPN_SWITCH_PFCTL:-pfctl}"
    local vpn_dns_table="${VPN_SWITCH_VPN_DNS_TABLE:-vpn_dns}"
    local vpn_remotes_table="${VPN_SWITCH_VPN_REMOTES_TABLE:-vpn_remotes}"

    # Generate legacy cleanup commands
    cat <<EOF
# Disconnect OpenVPN interface: $interface (legacy mode - no disconnect.sh found)
# Session PID: $session_pid
# Original config: $original_config_relative

# Kill OpenVPN daemon process
if [ -f "$session_dir/openvpn.pid" ]; then
  openvpn_pid=\$(cat "$session_dir/openvpn.pid" 2>>"$LOG_FILE")
  if [ -n "\$openvpn_pid" ]; then
    echo "# Killing OpenVPN daemon (PID: \$openvpn_pid)..."
    kill -TERM "\$openvpn_pid" 2>>"$LOG_FILE" || true
    sleep 1
  fi
fi

# Destroy interface
echo "# Cleaning up interface: $interface"
$(printf "$MODIFY_INTERFACE_DESTROY_FMT" "$interface") 2>>"$LOG_FILE" || true

# Clean up firewall tables
echo "# Cleaning up firewall tables..."
$pfctl -t "$vpn_dns_table" -T flush 2>>"$LOG_FILE" || true
$pfctl -t "$vpn_remotes_table" -T flush 2>>"$LOG_FILE" || true

echo "# VPN disconnected: $interface"
echo "# Note: Session metadata will be cleaned up by 'session stop'"
EOF
  fi
}

#@help _openvpn_patch1
# @command openvpn patch <config>
# @summary Preview the patched config that would be used to connect
# @group   openvpn
# @param   config  config to preview
# @returns the patched configuration
# @example vpn-switch openvpn patch us-server.ovpn
#@end
_openvpn_patch1() {
  local config_name="$1"
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"

  # Resolve config path (handle both relative and absolute paths)
  local config_path=""
  case "$config_name" in
    /*)
      # Absolute path - use as-is
      config_path="$config_name"
      ;;
    *)
      # Relative path - resolve from openvpn directory
      config_path="$ovpn_dir/$config_name"
      ;;
  esac

  # Validate config exists
  if [ ! -f "$config_path" ]; then
    generate_error "Config file not found: $config_path"
    return 0
  fi

  # Validate it's readable
  if [ ! -r "$config_path" ]; then
    generate_error "Config file not readable: $config_path"
    return 0
  fi

  # Output patched config to stdout using patch_openvpn_config helper
  # Note: /dev/stdout is POSIX-compliant for output redirection
  patch_openvpn_config "$config_path" /dev/stdout
}

#@help ___openvpn_inspect0
# @internal OpenVPN portion of 'inspect'
#@end
___openvpn_inspect0() {
  # Batch combinator - compose multiple inspection commands
  # Note: openvpn_list, validate0, and enumerate0 have templates with appropriate interpreters

  echo "# OpenVPN Inspection Report"
  echo ""
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn list 2>>\"\$LOG_FILE\""
  echo ""
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn validate 2>>\"\$LOG_FILE\""
  echo ""
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn enumerate 2>>\"\$LOG_FILE\""
}

#@help _openvpn_enumerate0
# @internal OpenVPN enumeration helper
#@end
_openvpn_enumerate0() {
  # Process Table Analysis - enumerate running OpenVPN processes
  # Generates shell code that examines process table at execution time

  cat <<EOF
ps_output=\$(ps auxww 2>>"$LOG_FILE" | grep '[o]penvpn' || true)

if [ -z "\$ps_output" ]; then
  echo "# No openvpn processes found"
  exit 0
fi

echo "\$ps_output" | while IFS= read -r line; do
  pid=\$(echo "\$line" | awk '{print \$2}')
  cmd=\$(echo "\$line" | awk '{for(i=11;i<=NF;i++) printf \$i " "; print ""}')
  config=\$(echo "\$cmd" | sed -n 's/.*--config[[:space:]]*\([^[:space:]]*\).*/\1/p')

  if [ -z "\$config" ]; then
    config='(inline configuration)'
  fi

  if echo "\$config" | grep -q "^$VPN_SWITCH_BASE/.session/"; then
    session_id=\$(echo "\$config" | sed "s|^$VPN_SWITCH_BASE/.session/\([^/]*\)/.*|\1|")
    echo "#"
    echo "# ✓ openvpn (PID \$pid) [managed by this instance]"
    echo "#   Config: \$config"
    echo "#   Session: \$session_id"
  elif echo "\$config" | grep -q '/.session/'; then
    other_base=\$(echo "\$config" | sed 's|\(.*\)/.session/.*|\1|')
    echo "#"
    echo "# ⚠ openvpn (PID \$pid) [different vpn-switch instance]"
    echo "#   Config: \$config"
    echo "#   Instance: \$other_base"
  else
    echo "#"
    echo "# ⚠ openvpn (PID \$pid) [NOT managed by vpn-switch]"
    echo "#   Config: \$config"
  fi
done
EOF
}

#@help _openvpn_import1
# @command openvpn import <path>
# @summary Import an OpenVPN .ovpn file into the database
# @group   openvpn
# @param   path  path to a .ovpn file to import
# @returns shell commands (copy config into the database)
# @example vpn-switch openvpn import ~/vpn/us-server.ovpn
# @see     openvpn list
#@end
_openvpn_import1() {
  local source_path="$1"
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"

  # Validate source file
  if [ ! -f "$source_path" ]; then
    generate_error "File not found: $source_path"
    return 0
  fi

  # Extract filename
  local filename=$(basename -- "$source_path")

  # Validate file extension
  case "$filename" in
    *.ovpn) ;;
    *)
      generate_error "Not an OpenVPN config - must end in .ovpn: $filename"
      return 0
      ;;
  esac

  local dest_path="$ovpn_dir/$filename"

  # Check if already exists
  if [ -e "$dest_path" ]; then
    generate_error "Config already exists: openvpn/$filename"
    return 0
  fi

  # Output commands to copy file
  cat <<EOF
# Import OpenVPN config: $filename
$MODIFY_FILE_COPY "$source_path" "$dest_path"
$MODIFY_FILE_PERMS 0400 "$dest_path"
echo "# Imported: openvpn/$filename" >&2
EOF
}

#@help _openvpn_list0
# @command openvpn list [<group>]
# @summary List OpenVPN configs and groups
# @group   openvpn
# @param   group  restrict the listing to one group
# @returns config / group listing
# @example vpn-switch openvpn list
#@end
_openvpn_list0() {
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"

  # Validate openvpn directory exists
  if [ ! -d "$ovpn_dir" ]; then
    generate_error "OpenVPN directory not found: $ovpn_dir"
    return 0
  fi

  # Output listing with hierarchy prefixes and comment headers
  echo "# === OpenVPN Configurations ==="
  echo "#"
  echo "# Configuration files:"
  scan_openvpn_configs

  # Check if there are protocol-level links (aliases) to show
  local links=$(scan_openvpn_links)
  if [ -n "$links" ]; then
    echo "#"
    echo "# Protocol-level links:"
    echo "$links"
  fi

  echo "#"
  echo "# Groups: (use 'openvpn list <group>' to see contents)"
  scan_openvpn_groups
}

#@help _openvpn_list1
# @internal arity-1 sibling of 'openvpn list' (single group)
#@end
_openvpn_list1() {
  local group="$1"
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"
  local group_dir="$ovpn_dir/$group"

  # Validate group exists
  if [ ! -d "$group_dir" ]; then
    generate_error "Group not found: $group"
    return 0
  fi

  echo "# Group: $group"

  # Iterate over all items in group directory
  for item in "$group_dir"/*; do
    # Skip if no items found
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    local item_name=$(basename -- "$item")

    # Show symlink target if it's a link
    if [ -L "$item" ]; then
      local target=$(readlink "$item")
      echo "openvpn/$group/$item_name -> $target"
    else
      # Regular file/directory (shouldn't happen in groups, but be safe)
      echo "openvpn/$group/$item_name"
    fi
  done | sort
}

#@help _openvpn_add1
# @command openvpn add <group> [<config> [<alias>]]
# @summary Create a group, or link a config into one
# @group   openvpn
# @param   group   group to create or add to
# @param   config  config to link into the group
# @param   alias   custom link name (default: derived)
# @returns shell commands (create group / create symlink)
# @example vpn-switch openvpn add work us-server.ovpn office
# @see     openvpn link
#@end
_openvpn_add1() {
  local group="$1"
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"
  local group_dir="$ovpn_dir/$group"

  # Validate group name (no slashes, dots, etc)
  case "$group" in
    */*|*.*|*.*)
      generate_error "Invalid group name - no slashes or dots allowed: $group"
      return 0
      ;;
  esac

  # Check if already exists
  if [ -e "$group_dir" ]; then
    generate_error "Group already exists: $group"
    return 0
  fi

  # Output commands to create directory
  cat <<EOF
# Create group: $group
$MODIFY_DIR_CREATE "$group_dir"
$MODIFY_FILE_PERMS 0700 "$group_dir"
echo "# Created group: openvpn/$group/" >&2
EOF
}

#@help __openvpn_add2
# @internal arity-2 sibling of 'openvpn add' (config into group)
#@end
__openvpn_add2() {
  local group="$1"
  local target="$2"
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"
  local group_dir="$ovpn_dir/$group"
  local target_path="$ovpn_dir/$target"

  # Validate group exists
  if [ ! -d "$group_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Group not found: $group\""
    return
  fi

  # Validate target exists
  if [ ! -f "$target_path" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Config not found: openvpn/$target\""
    return
  fi

  # Derive link name from target (remove .ovpn extension)
  local alias=$(basename -- "$target" .ovpn)
  local link_path="$group_dir/$alias"

  # Check if link already exists
  if [ -e "$link_path" ] || [ -L "$link_path" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Alias already exists in group $group: $alias\""
    return
  fi

  # Delegate to add3 with derived alias
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn add \"$group\" \"$target\" \"$alias\""
}

#@help _openvpn_add3
# @internal arity-3 sibling of 'openvpn add' (config + custom alias)
#@end
_openvpn_add3() {
  local group="$1"
  local target="$2"
  local alias="$3"
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"
  local group_dir="$ovpn_dir/$group"
  local target_path="$ovpn_dir/$target"
  local link_path="$group_dir/$alias"

  # Validate group exists
  if [ ! -d "$group_dir" ]; then
    generate_error "Group not found: $group"
    display plain "Use: openvpn add $group"
    return 0
  fi

  # Validate target exists
  if [ ! -f "$target_path" ]; then
    generate_error "Config not found: openvpn/$target"
    return 0
  fi

  # Validate alias doesn't contain slashes
  case "$alias" in
    */*)
      generate_error "Invalid alias - no slashes allowed: $alias"
      return 0
      ;;
  esac

  # Check if link already exists
  if [ -e "$link_path" ] || [ -L "$link_path" ]; then
    generate_error "Alias already exists in group $group: $alias"
    return 0
  fi

  # Output commands to create symlink (relative path)
  cat <<EOF
# Add link to group: openvpn/$group/$alias -> $target
$MODIFY_LINK_CREATE "../$target" "$group_dir/$alias"
echo "# Added to group $group: $alias -> $target" >&2
EOF
}

#@help _openvpn_link2
# @command openvpn link <alias> <target>
# @summary Create a protocol-level alias to a config
# @group   openvpn
# @param   alias   new alias name
# @param   target  config the alias points to
# @returns shell commands (create symlink)
# @example vpn-switch openvpn link quick us-server.ovpn
# @see     openvpn add
#@end
_openvpn_link2() {
  local alias="$1"
  local target="$2"
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"
  local alias_path="$ovpn_dir/$alias"
  local target_path="$ovpn_dir/$target"

  # Validate target exists
  if [ ! -f "$target_path" ]; then
    generate_error "Config not found: openvpn/$target"
    return 0
  fi

  # Check if alias already exists
  if [ -e "$alias_path" ] || [ -L "$alias_path" ]; then
    generate_error "Alias already exists: $alias"
    return 0
  fi

  # Output commands to create symlink (relative path for same directory)
  cat <<EOF
# Create link in openvpn/: $alias -> $target
$MODIFY_LINK_CREATE "./$target" "$alias_path"
echo "# Created link: openvpn/$alias -> $target" >&2
EOF
}

#@help _openvpn_remove1
# @command openvpn remove <name>
# @summary Remove a config or link (with safety checks)
# @group   openvpn
# @param   name  config or link to remove
# @returns shell commands (remove the target)
# @example vpn-switch openvpn remove old-server
#@end
_openvpn_remove1() {
  local name="$1"
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"
  local target_path="$ovpn_dir/$name"

  # Validate exists
  if [ ! -e "$target_path" ] && [ ! -L "$target_path" ]; then
    generate_error "Not found: openvpn/$name"
    return 0
  fi

  # If it's a directory (group), refuse
  if [ -d "$target_path" ]; then
    generate_error "Cannot remove group this way"
    display plain "Use: openvpn remove <group> <link>"
    return 0
  fi

  # Check if referenced by any group symlinks
  for group_dir in "$ovpn_dir"/*/; do
    [ ! -d "$group_dir" ] && continue

    for link in "$group_dir"/*; do
      [ ! -L "$link" ] && continue
      local target=$(readlink "$link")
      # Normalize paths for comparison
      local target_basename=$(basename -- "$target")
      if [ "$target_basename" = "$name" ] || [ "$target" = "../$name" ]; then
        local group=$(basename -- "$group_dir")
        generate_error "Config referenced by group link: $group/$(basename -- "$link") -> $name"
        return 0
      fi
    done
  done

  # Output commands to remove
  cat <<EOF
# Remove: openvpn/$name
$MODIFY_FILE_REMOVE "$target_path"
echo "# Removed: openvpn/$name" >&2
EOF
}

#@help _openvpn_remove2
# @internal arity-2 variant of 'openvpn remove' (remove link from a group)
#@end
_openvpn_remove2() {
  local group="$1"
  local link="$2"
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"
  local group_dir="$ovpn_dir/$group"
  local link_path="$group_dir/$link"

  # Validate group exists
  if [ ! -d "$group_dir" ]; then
    generate_error "Group not found: $group"
    return 1
  fi

  # Validate link exists
  if [ ! -L "$link_path" ]; then
    generate_error "Link not found: openvpn/$group/$link"
    return 1
  fi

  # Output commands to remove
  cat <<EOF
# Remove group link: openvpn/$group/$link
$MODIFY_FILE_REMOVE "$link_path"
echo "# Removed: openvpn/$group/$link" >&2
EOF
}

#@help _openvpn_validate0
# @command openvpn validate
# @summary Check OpenVPN symlink integrity in the database
# @group   openvpn
# @returns validation report
# @example vpn-switch openvpn validate
# @see     openvpn clean
#@end
_openvpn_validate0() {
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"
  local has_errors=0
  local has_warnings=0

  # Check if openvpn directory exists
  if [ ! -d "$ovpn_dir" ]; then
    echo "# [ERROR] OpenVPN directory not found: $ovpn_dir"
    return 1
  fi

  echo "# === OpenVPN Configuration Validation ==="
  echo "#"

  # Check for broken symlinks in protocol directory
  echo "# Checking protocol directory for broken symlinks..."
  for item in "$ovpn_dir"/*; do
    # Skip if no items
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    # Check if symlink and broken
    if [ -L "$item" ] && [ ! -e "$item" ]; then
      local item_name=$(basename -- "$item")
      echo "# [ERROR] Broken symlink: openvpn/$item_name"
      has_errors=1
    fi
  done

  # Check for broken symlinks in groups
  echo "#"
  echo "# Checking groups for broken symlinks..."
  for group_dir in "$ovpn_dir"/*/; do
    [ ! -d "$group_dir" ] && continue
    local group=$(basename -- "$group_dir")

    for item in "$group_dir"/*; do
      # Skip if no items
      [ ! -e "$item" ] && [ ! -L "$item" ] && continue

      # Check if symlink and broken
      if [ -L "$item" ] && [ ! -e "$item" ]; then
        local item_name=$(basename -- "$item")
        echo "# [ERROR] Broken symlink: $group/$item_name"
        has_errors=1
      fi
    done
  done

  # Check for naming conflicts (file and directory with same name)
  echo "#"
  echo "# Checking for naming conflicts..."
  for item in "$ovpn_dir"/*; do
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    local base_name=$(basename -- "$item")

    # Skip directories and non-ovpn files for this check
    [ -d "$item" ] && continue
    [ ! -f "$item" ] && [ ! -L "$item" ] && continue

    # Check if there's also a directory with the same name (without .ovpn)
    local name_without_ext="${base_name%.ovpn}"
    if [ -d "$ovpn_dir/$name_without_ext" ]; then
      echo "# [WARNING] Naming conflict: openvpn/$base_name (file) and openvpn/$name_without_ext/ (directory)"
      has_warnings=1
    fi
  done

  # Check for basic config file validity (just check if readable and non-empty)
  echo "#"
  echo "# Checking config file validity..."
  for item in "$ovpn_dir"/*.ovpn; do
    # Skip if glob didn't match any files
    [ ! -e "$item" ] && continue

    local config_name=$(basename -- "$item")

    # Check if readable
    if [ ! -r "$item" ]; then
      echo "# [ERROR] Config not readable: openvpn/$config_name"
      has_errors=1
      continue
    fi

    # Check if non-empty
    if [ ! -s "$item" ]; then
      echo "# [WARNING] Config file is empty: openvpn/$config_name"
      has_warnings=1
      continue
    fi

    # Check for basic OpenVPN directives (client or remote). Use ERE: BRE '\|'
    # alternation is a GNU/FreeBSD extension that OpenBSD grep does not accept,
    # so '^\(client\|remote\)' matched nothing there and flagged valid configs.
    if ! grep -qE "^(client|remote)" "$item" 2>>"$LOG_FILE"; then
      echo "# [WARNING] Config missing OpenVPN directives (client/remote): openvpn/$config_name"
      has_warnings=1
    fi
  done

  # Summary
  echo "#"
  if [ $has_errors -eq 0 ] && [ $has_warnings -eq 0 ]; then
    echo "# Validation complete: No issues found"
    return 0
  elif [ $has_errors -eq 0 ]; then
    echo "# Validation complete: Warnings found (no errors)"
    return 0
  else
    echo "# Validation complete: Errors found"
    return 1
  fi
}

#@help ___openvpn_clean0
# @command openvpn clean
# @summary Generate cleanup commands for broken links
# @group   openvpn
# @returns shell commands (review, then pipe to sh)
# @example vpn-switch openvpn clean | sh
# @see     openvpn validate
#@end
___openvpn_clean0() {
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"

  echo "# OpenVPN database cleanup commands"
  echo "# Pipe to sh to execute: vpn-switch openvpn clean | sh"
  echo ""

  # Check protocol-level links
  for item in "$ovpn_dir"/*; do
    [ ! -L "$item" ] && continue
    [ -e "$item" ] && continue  # Skip if target exists

    local item_name=$(basename -- "$item")
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn remove \"$item_name\""
  done

  # Check group links
  for group_dir in "$ovpn_dir"/*/; do
    [ ! -d "$group_dir" ] && continue
    local group=$(basename -- "$group_dir")

    for link in "$group_dir"/*; do
      [ ! -L "$link" ] && continue
      [ -e "$link" ] && continue  # Skip if target exists

      local link_name=$(basename -- "$link")
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn remove \"$group\" \"$link_name\""
    done
  done
}

#@help _openvpn_info1
# @command openvpn info <group>
# @summary Show group details and configurations
# @group   openvpn
# @param   group  group to inspect
# @returns group report
# @example vpn-switch openvpn info work
#@end
_openvpn_info1() {
  local group="$1"
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"
  local group_dir="$ovpn_dir/$group"

  # Validate group exists
  if [ ! -d "$group_dir" ]; then
    generate_error "Group not found: $group"
    return 1
  fi

  echo "# Group: $group"
  echo "# Path: $group_dir"
  echo ""

  # Count items
  local total=0
  for item in "$group_dir"/*; do
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue
    total=$((total + 1))
  done

  echo "# Total links: $total"
  echo ""
  echo "# Contents:"

  # List with targets
  for entry in "$group_dir"/*; do
    [ ! -e "$entry" ] && [ ! -L "$entry" ] && continue

    local basename_entry=$(basename -- "$entry")

    if [ -L "$entry" ]; then
      # Symlink - show target
      local target=$(readlink "$entry")
      echo "#   $basename_entry -> $target"
    elif [ -f "$entry" ]; then
      # Regular file
      echo "#   $basename_entry"
    fi
  done | sort
}

#@help ___openvpn_dump0
# @command openvpn dump
# @summary Generate restorable shell commands for all OpenVPN configs
# @group   openvpn
# @returns shell commands (restorable database dump)
# @example vpn-switch openvpn dump
# @see     dump
#@end
___openvpn_dump0() {
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"

  # Validate openvpn directory exists
  if [ ! -d "$ovpn_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"OpenVPN directory not found: $ovpn_dir\""
    return 0
  fi

  # Phase 1: Import all configs (absolute paths from SOURCE database)
  echo "# Import openvpn configurations"
  for config_file in "$ovpn_dir"/*.ovpn; do
    [ ! -f "$config_file" ] && continue

    # Skip files with newlines in name (cannot be safely represented in line-based dump)
    if has_newline_in_path "$config_file"; then
      echo "# WARNING: Skipping file with newline in name (cannot be safely dumped)"
      continue
    fi

    # Use absolute path for imports with proper quoting
    # Output literal \$VPN_SWITCH_CONTEXT_SCRIPT so it expands during restore
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn import \"$config_file\""
  done

  # Output separator
  echo ""

  # Phase 2: Create groups
  echo "# Create groups"
  scan_openvpn_groups | while IFS= read -r group_path; do
    # Extract group name (remove openvpn/ prefix and / suffix)
    local group=$(echo "$group_path" | sed 's|^openvpn/||' | sed 's|/$||')
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn add $group"
  done

  # Output separator
  echo ""

  # Phase 3: Create protocol-level links (aliases in openvpn/ directory)
  echo "# Create protocol-level links"
  scan_openvpn_links | while IFS= read -r link_info; do
    # Parse "openvpn/alias -> target" format
    local alias=$(echo "$link_info" | sed 's|^openvpn/||' | sed 's| ->.*||')
    local target=$(echo "$link_info" | sed 's|.* -> ||')
    # Normalize target: strip ./ prefix (openvpn link will add it back)
    target=$(echo "$target" | sed 's|^\./||')
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn link $alias $target"
  done

  # Output separator
  echo ""

  # Phase 4: Create group links
  echo "# Create group links"
  scan_openvpn_groups | while IFS= read -r group_path; do
    # Extract group name
    local group=$(echo "$group_path" | sed 's|^openvpn/||' | sed 's|/$||')
    local group_dir="$ovpn_dir/$group"

    # Scan for links in this group
    for link_file in "$group_dir"/*; do
      [ ! -L "$link_file" ] && continue
      local link_name=$(basename -- "$link_file")
      local target=$(readlink "$link_file")
      local target_basename=$(basename -- "$target")

      # Determine if this is arity-2 (link and target have same name) or arity-3 (different)
      local target_base=$(basename -- "$target" .ovpn)
      if [ "$link_name" = "$target_base" ] || [ "$link_name" = "$target_basename" ]; then
        # Arity-2: same name
        echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn add $group $target_basename"
      else
        # Arity-3: custom name
        echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" openvpn add $group $target_basename $link_name"
      fi
    done
  done
}

#@help __openvpn_help0
# @command openvpn help
# @summary Show OpenVPN command help
# @group   openvpn
# @returns help text
# @example vpn-switch openvpn help
#@end
__openvpn_help0() {
  # Backward compatibility: delegate to new pattern "help openvpn"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" help openvpn"
}

patch_openvpn_config() {
  local source_config="$1"
  local dest_config="$2"
  local resolvconf_base="${VPN_SWITCH_RESOLVCONF_openvpn:-/usr/local/sbin/ovpn-resolvconf}"
  local interface="${VPN_SWITCH_INTERFACE_openvpn:-tun0}"
  local credentials_file="${VPN_SWITCH_CREDENTIALS_openvpn:-}"

  # Derive session directory from destination path (for PID file)
  local session_dir
  if [ "$dest_config" = "/dev/stdout" ]; then
    # When outputting to stdout, use a placeholder for PID file
    session_dir="SESSION_DIR"
  else
    session_dir=$(dirname "$dest_config")
  fi
  local pid_file="$session_dir/openvpn.pid"

  # Use awk to patch config (supports stdout, no temp files needed)
  awk -v resolvconf_up="${resolvconf_base}-up" \
      -v resolvconf_down="${resolvconf_base}-down" \
      -v iface="$interface" \
      -v pidfile="$pid_file" \
      -v credentials_file="$credentials_file" '
    BEGIN {
      has_dev=0
      has_daemon=0
      has_writepid=0
      # Phase-based approach: up/down not tracked (stripped from config)
      # has_up=0
      # has_down=0
    }

    # Phase-based approach: Strip any existing up/down scripts
    # DNS configuration is handled entirely by the DNS phase, not OpenVPN up/down scripts
    # This prevents OpenVPN from exiting if up script fails (e.g., no DNS push from server)
    /^up / || /^down / {
      next  # Skip these lines entirely
    }

    # Update existing dev directive
    /^dev / {
      print "dev " iface
      has_dev=1
      next
    }

    # Mark daemon as present (update or keep)
    /^daemon/ {
      has_daemon=1
      print
      next
    }

    # Update existing writepid directive
    /^writepid / {
      print "writepid " pidfile
      has_writepid=1
      next
    }

    # Patch bare auth-user-pass directive (interactive prompt) with credentials file
    # Only patch if VPN_SWITCH_CREDENTIALS_openvpn is set
    /^auth-user-pass$/ {
      if (credentials_file != "") {
        print "auth-user-pass " credentials_file
      } else {
        print  # Leave unchanged for interactive prompt
      }
      next
    }

    # Leave auth-user-pass with existing path unchanged
    /^auth-user-pass / {
      print
      next
    }

    # Pass through all other lines
    { print }

    # Add missing directives at end
    END {
      if (!has_dev) print "dev " iface
      if (!has_daemon) print "daemon"
      if (!has_writepid) print "writepid " pidfile
      # Phase-based approach: DNS handled by phase scripts, not OpenVPN up/down
      # if (!has_up) print "up " resolvconf_up
      # if (!has_down) print "down " resolvconf_down
    }
  ' "$source_config" > "$dest_config"

  # Set permissions (skip if outputting to stdout)
  if [ "$dest_config" != "/dev/stdout" ]; then
    $MODIFY_FILE_PERMS 0400 "$dest_config"
  fi
}

get_openvpn_remotes() {
  local config_file="$1"

  # Extract IP addresses from "remote <ip> <port>" lines
  awk '/^remote / { print $2 }' "$config_file"
}

scan_openvpn_links() {
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"

  # Find all symlinks that are NOT config files (i.e., protocol-level aliases)
  for item in "$ovpn_dir"/*; do
    # Skip if no items found
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    # Skip directories (groups)
    [ -d "$item" ] && continue

    # Skip if not a symlink
    [ ! -L "$item" ] && continue

    local item_name=$(basename -- "$item")

    # Skip .ovpn files (those are listed in configs section)
    case "$item_name" in
      *.ovpn) continue ;;
    esac

    # Show symlink with target
    local target=$(readlink "$item")
    echo "openvpn/$item_name -> $target"
  done | sort
}

scan_openvpn_groups() {
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"

  # Find all subdirectories, add hierarchy prefix and "/" suffix
  # Use find -H to follow symlinks on command line (for $ovpn_dir) but not inside
  find -H "$ovpn_dir" -maxdepth 1 -type d ! -path "$ovpn_dir" -exec basename {} \; 2>>"$LOG_FILE" | \
    sed 's|^|openvpn/|' | \
    sed 's|$|/|' | \
    sort
}

scan_openvpn_configs() {
  local ovpn_dir="$VPN_SWITCH_BASE/openvpn"

  # Find all .ovpn files (both regular files and symlinks ending in .ovpn)
  # Use find -H to follow symlinks on command line (for $ovpn_dir) but not inside
  find -H "$ovpn_dir" -maxdepth 1 \( -type f -o -type l \) -name "*.ovpn" -exec basename {} \; 2>>"$LOG_FILE" | \
    sed 's|^|openvpn/|' | \
    sort
}

scan_group_links() {
  local group="$1"
  local group_dir="$VPN_SWITCH_BASE/openvpn/$group"

  # Find all items in group, add hierarchy prefix
  # Note: Groups contain symlinks, not actual files
  find -H "$group_dir" -maxdepth 1 -type l -exec basename {} \; 2>>"$LOG_FILE" | \
    sed "s|^|openvpn/$group/|" | \
    sort
}

