# session.sh - Dynamically loaded session module
# Generated by extract-modules-v2.sh
# DO NOT EDIT - This file is auto-generated

# resolve_session_id - Resolve a session argument to a numeric PID
#
# Args: $1 - session ID (numeric PID or named-session symlink)
# Output (stdout): resolved numeric PID, one line, no trailing whitespace
# Returns: 0 on success, 1 if argument is non-numeric and no matching
#          session/<name> symlink exists
#
# Used by every command that takes a "<PID>|<name>" argument:
#   - _session_show1, _session_remove1 (terminal functions)
#   - __session_start1, __session_stop1 (combinator functions)
#
# Helpers like this one (no underscore prefix) are *not* part of the
# combinator/terminal anchor set — they're plain shell utilities called
# from anchor functions. Cf. is_session_alive() in vpn-switch.sh which
# follows the same convention.
#
# This helper deliberately does NOT verify that .session/$pid exists.
# Callers check that separately so they can produce context-appropriate
# diagnostics ("Session not found" vs. "Stale session link").
resolve_session_id() {
  local session_id="$1"

  if echo "$session_id" | grep -q '^[0-9][0-9]*$'; then
    printf '%s\n' "$session_id"
    return 0
  fi

  local named_link="$VPN_SWITCH_BASE/session/$session_id"
  if [ ! -L "$named_link" ]; then
    return 1
  fi

  basename -- "$(readlink "$named_link")"
  return 0
}

#@help __session_disconnect1
# @command session disconnect <PID>
# @summary Lower-level disconnect of a session by PID (no name resolution)
# @group   sessions
# @param   PID  session PID to disconnect
# @env     VPN_SWITCH_INTERFACE_<proto>  interface name pattern for teardown
# @returns disconnect commands
# @example vpn-switch session disconnect 12345
# @see     session stop
#@end
__session_disconnect1() {
  local session_pid="$1"
  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"

  # Check if session exists
  if [ ! -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"Session $session_pid already removed [stale cleanup or concurrent stop]\""
    return 0
  fi

  # Read session metadata
  local session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE")
  local session_interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE")

  # Validate protocol metadata exists and protocol directory exists (filesystem-based detection)
  if [ -z "$session_protocol" ] || [ ! -d "$VPN_SWITCH_BASE/$session_protocol" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Invalid protocol for session $session_pid: '${session_protocol:-[empty]}'\""
    return 0
  fi

  # Legacy sessions: infer interface from protocol using environment variables
  # Uses dynamic variable lookup: VPN_SWITCH_INTERFACE_<protocol>
  if [ -z "$session_interface" ]; then
    eval "session_interface=\"\$VPN_SWITCH_INTERFACE_${session_protocol}\""
    if [ -z "$session_interface" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Legacy session $session_pid has no interface metadata\" \"No VPN_SWITCH_INTERFACE_${session_protocol} configured\""
      return 0
    fi
  fi

  # Delegate to protocol-specific disconnect
  # Session layer trusts protocol metadata from filesystem validation above
  # Script path uses literal variable reference for portability
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $session_protocol disconnect $session_interface"
}

#@help ___session_stop0
# @internal batch sibling of 'session stop' (stops all active sessions)
#@end
___session_stop0() {
  # Zero-arity variant: emit a 'session stop <pid>' for EVERY session.
  #
  # Rationale: __session_disconnect1 (the eventual target) is idempotent
  # — it cleans up whether the session is alive or already dead. So
  # rather than pick one session (which risks leaving an active session
  # running if "latest" happens to be a dead one), we stop them all.
  # Each batch step routes through __session_stop1 → __session_disconnect1
  # which does the right thing for its own state.
  #
  # This also eliminates the racy double-check that the previous
  # combinator design had (alive-check in stop0, alive-check again in
  # stop1) and the duplication with _session_list0's iteration.
  local session_base="$VPN_SWITCH_BASE/.session"

  if [ ! -d "$session_base" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No sessions found\""
    return
  fi

  local has_sessions=0
  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue
    has_sessions=1
    local pid=$(basename -- "$session_dir")
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session stop \"$pid\""
  done

  if [ "$has_sessions" = "0" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No sessions found\""
  fi
}

#@help __session_stop1
# @command session stop [<name>|<PID>]
# @summary Stop an active session; with no argument, stop all active sessions
# @group   sessions
# @param   name|PID  session to stop (default: all active sessions)
# @returns disconnect commands
# @example vpn-switch session stop work
# @see     session start
#@end
__session_stop1() {
  local session_id="$1"
  local resolved_pid

  # Accept either a numeric PID or a named-session symlink.
  if ! resolved_pid=$(resolve_session_id "$session_id"); then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Named session not found: $session_id\""
    return
  fi

  # Check if session exists
  local session_dir="$VPN_SWITCH_BASE/.session/$resolved_pid"
  if [ ! -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Stale session link $session_id: $resolved_pid\" \"Session directory removed - run vpn-switch session clean\""
    return
  fi

  # No alive-check here: __session_disconnect1 (and the underlying
  # disconnect.sh phases) are idempotent — they clean up whether the
  # VPN process is still running or already dead. The alive-check
  # belongs to display (list/show) and safety (remove/clean) contexts,
  # not to the stop routing path.
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session disconnect \"$resolved_pid\""
}

#@help _session_list0
# @command session list
# @summary Show all active and saved sessions
# @group   sessions
# @returns session table (active/stopped, referenced/unreferenced)
# @example vpn-switch session list
# @see     session refresh
# @see     session clean
#@end
_session_list0() {
  local session_base="$VPN_SWITCH_BASE/.session"
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  # Header (always output)
  echo '# VPN Sessions:'
  echo '#'

  if [ ! -d "$session_base" ]; then
    echo '# ⚠ No active sessions (session directory missing)'
    return 0
  fi

  local has_sessions=0
  for session_dir in "$session_base"/*/; do
    [ -d "$session_dir" ] && has_sessions=1 && break
  done

  if [ "$has_sessions" = "0" ]; then
    echo '# - No active sessions'
    return 0
  fi

  # Build referenced PIDs list
  local referenced_pids=""
  if [ -d "$session_proto_dir" ]; then
    for link in "$session_proto_dir"/*; do
      [ ! -L "$link" ] && continue
      local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "")
      if [ -n "$target" ]; then
        local target_pid=$(basename -- "$target")
        case " $referenced_pids " in
          *" $target_pid "*) ;;
          *) referenced_pids="$referenced_pids $target_pid" ;;
        esac
      fi
    done
  fi

  # Table header
  printf '# %-6s %-12s %-10s %-8s %-21s %-22s %s\n' 'PID' 'SESSION' 'PROTOCOL' 'IFACE' 'STATE' 'CONFIG' 'STARTED'
  printf '# %-6s %-12s %-10s %-8s %-21s %-22s %s\n' '---' '-------' '--------' '-----' '-----' '------' '-------'

  # Session rows
  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue

    local session_pid=$(basename -- "$session_dir")
    local session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE" || echo "unknown")
    local session_interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "unknown")
    local session_original=$(cat "$session_dir/original" 2>>"$LOG_FILE" || echo "unknown")
    local session_started=$(cat "$session_dir/started" 2>>"$LOG_FILE" || echo "unknown")
    local config_basename=$(basename -- "$session_original")

    # Collect session names for this PID (from session/ symlinks)
    local session_names=""
    if [ -d "$session_proto_dir" ]; then
      for link in "$session_proto_dir"/*; do
        [ ! -L "$link" ] && continue
        local link_name=$(basename "$link")

        # Skip system-generated links (latest, latest-wg0, etc.)
        case "$link_name" in
          latest|latest-*) continue ;;
        esac

        local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "")
        local target_pid=$(basename -- "$target" 2>>"$LOG_FILE" || echo "")

        if [ "$target_pid" = "$session_pid" ]; then
          if [ -z "$session_names" ]; then
            session_names="$link_name"
          else
            session_names="$session_names,$link_name"
          fi
        fi
      done
    fi

    # If no names, use "-"
    [ -z "$session_names" ] && session_names="-"

    local vpn_state="stopped"
    is_session_alive "$session_dir" && vpn_state="active"

    local ref_state="unreferenced"
    case " $referenced_pids " in
      *" $session_pid "*) ref_state="referenced" ;;
    esac

    local state="${vpn_state}/${ref_state}"

    printf '# %-6s %-12s %-10s %-8s %-21s %-22s %s\n' "$session_pid" "$session_names" "$session_protocol" "$session_interface" "$state" "$config_basename" "$session_started"
  done

  # Footer
  cat <<'EOF'
#
# States: active=VPN running, stopped=VPN disconnected, referenced=has saved links, unreferenced=no links
# Tip: Use 'vpn-switch session clean' to remove unreferenced sessions
EOF
}

#@help __session_show0
# @internal arity-0 sibling of 'session show' (latest session)
#@end
__session_show0() {
  # Combinator - find most recent session and delegate to show command
  local session_base="$VPN_SWITCH_BASE/.session"

  if [ ! -d "$session_base" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No active sessions found\""
    return
  fi

  # Find most recent session (by modification time)
  local latest_session=""
  local latest_mtime=0

  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue

    # Get modification time (seconds since epoch)
    local mtime=$($CMD_STAT_MTIME "$session_dir" 2>>"$LOG_FILE" || echo 0)

    if [ "$mtime" -gt "$latest_mtime" ]; then
      latest_mtime="$mtime"
      latest_session="$session_dir"
    fi
  done

  if [ -z "$latest_session" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No active sessions found\""
    return
  fi

  # Output vpn-switch command (combinator pattern)
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session show \"$(basename -- "$latest_session")\""
}

#@help _session_show1
# @command session show [<name>|<PID>]
# @summary Show a session's cached connect script and metadata
# @group   sessions
# @param   name|PID  saved session name or PID (default: latest)
# @returns the session's connect.sh and metadata
# @example vpn-switch session show work
#@end
_session_show1() {
  local session_id="$1"
  local session_pid

  echo '# Session Show'
  echo '#'

  # Accept either a numeric PID or a named-session symlink, mirroring
  # __session_start1 / __session_stop1. Documented in
  # TUTORIAL_SESSIONS.md Step 7 ("vpn-switch session show work").
  if ! session_pid=$(resolve_session_id "$session_id"); then
    echo "# ✗ Error: Named session not found: $session_id"
    return 1
  fi

  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"
  local connect_script="$session_dir/connect.sh"

  if [ ! -d "$session_dir" ]; then
    # Distinguish stale named link from a bare missing PID
    if [ "$session_id" != "$session_pid" ]; then
      echo "# ✗ Error: Stale session link $session_id: $session_pid"
      echo "# Session directory removed - run vpn-switch session clean"
    else
      echo "# ✗ Error: Session not found: $session_pid"
    fi
    return 1
  fi

  if [ ! -f "$connect_script" ]; then
    echo "# ✗ Error: Connect script not found for session: $session_pid"
    return 1
  fi

  # Session metadata
  local session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE" || echo "unknown")
  local session_interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "unknown")
  local session_original=$(cat "$session_dir/original" 2>>"$LOG_FILE" || echo "unknown")

  echo "# Session: $session_pid"
  echo "# Protocol: $session_protocol"
  echo "# Interface: $session_interface"
  echo "# Config: $(basename -- "$session_original")"
  echo '#'
  echo "# Connect script ($connect_script):"
  echo '#'

  # Display connect script contents (prefixed)
  sed 's/^/# /' "$connect_script"
}

#@help _session_remove1
# @command session remove <name>|<PID>
# @summary Remove a stopped session from the database
# @group   sessions
# @param   name|PID  session to remove (refuses if active)
# @returns shell commands (remove session directory and links)
# @example vpn-switch session remove 12345
# @see     session clean
#@end
_session_remove1() {
  local session_id="$1"
  local session_pid

  # Accept either a numeric PID or a named-session symlink, mirroring
  # __session_start1 / __session_stop1 / _session_show1.
  if ! session_pid=$(resolve_session_id "$session_id"); then
    generate_error "Named session not found: $session_id"
    return 0
  fi

  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"

  if [ ! -d "$session_dir" ]; then
    if [ "$session_id" != "$session_pid" ]; then
      generate_error "Stale session link $session_id: $session_pid" "Session directory removed - run vpn-switch session clean"
    else
      generate_error "Session not found: $session_pid"
    fi
    return 0
  fi

  # Check if VPN process still alive
  if is_session_alive "$session_dir"; then
    display warning "Session $session_pid appears to be active - process still running"
    display warning "You should stop the VPN first: vpn-switch stop"
    generate_error "Refusing to remove active session"
    return 0
  fi

  # Generate removal commands
  cat <<EOF
# Remove session directory
echo "Removing session: $session_pid"
$MODIFY_DIR_REMOVE "$session_dir"
echo "Session removed: $session_pid"
EOF
}

#@help __session_start0
# @internal arity-0 sibling of 'session start' (default session)
#@end
__session_start0() {
  local session_proto_dir="$VPN_SWITCH_BASE/session"
  local default_link="$session_proto_dir/default"

  # Check if default link exists
  if [ ! -L "$default_link" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No default session configured\" \"Use vpn-switch session save first\""
    return
  fi

  # Resolve the link to get PID
  local session_path=$(readlink "$default_link")
  local session_pid=$(basename -- "$session_path")

  # Bug #5 Fix: Check if symlink target exists
  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"
  if [ ! -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Stale session link default: $session_pid\" \"Session directory removed - run vpn-switch session clean\""
    return
  fi

  # Output combinator command to start this session
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session start \"$session_pid\""
}

#@help __session_start1
# @command session start [<name>|<PID>]
# @summary Resume a saved session by replaying its cached connect script
# @group   sessions
# @param   name|PID  saved session to resume (default: the 'default' session)
# @returns connect commands (run under the connect interpreter)
# @example vpn-switch session start work
# @see     session save
# @see     session stop
#@end
__session_start1() {
  local session_id="$1"
  local resolved_pid

  # Accept either a numeric PID or a named-session symlink.
  if ! resolved_pid=$(resolve_session_id "$session_id"); then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Named session not found: $session_id\""
    return
  fi

  # Bug #5 Fix: Check if symlink target exists
  local session_dir="$VPN_SWITCH_BASE/.session/$resolved_pid"
  if [ ! -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Stale session link $session_id: $resolved_pid\" \"Session directory removed - run vpn-switch session clean\""
    return
  fi

  # Output combinator command to connect
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session connect \"$resolved_pid\""
}

#@help ___session_switch1
# @command session switch <name>|<PID> [<from>]
# @summary Stop active sessions (all, or only <from>), then resume the target session
# @group   sessions
# @param   name|PID  saved session to switch to
# @param   from      optional: session to stop (default: all active sessions)
# @returns stop + start commands
# @example vpn-switch session switch work
# @example vpn-switch session switch work home
# @see     session start
# @see     session stop
#@end
___session_switch1() {
  local target_id="$1"
  local resolved_pid

  # Validate the target BEFORE emitting any stop: a typo in the target
  # must not take the active sessions down and leave the user offline.
  if ! resolved_pid=$(resolve_session_id "$target_id"); then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Named session not found: $target_id\""
    return
  fi

  local session_dir="$VPN_SWITCH_BASE/.session/$resolved_pid"
  if [ ! -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Stale session link $target_id: $resolved_pid\" \"Session directory removed - run vpn-switch session clean\""
    return
  fi

  # Stop only the sessions that are actually alive, then resume the
  # target. Unlike the no-arg 'session stop' (which iterates every
  # session dir and relies on idempotent disconnects), switch filters
  # via is_session_alive at generation time — the emitted plan then
  # names exactly the sessions that will be torn down, which is what a
  # user inspecting the batch expects to see. Stopping the target
  # itself (if it happens to be the active one) is harmless: its
  # session directory survives a stop (only 'session remove' deletes
  # it), so the subsequent start simply reconnects it.
  local session_base="$VPN_SWITCH_BASE/.session"
  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue
    is_session_alive "$session_dir" || continue
    local pid=$(basename -- "$session_dir")
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session stop \"$pid\""
  done

  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session start \"$resolved_pid\""
}

#@help ___session_switch2
# @internal arity-2 sibling of 'session switch' (stop only <from>)
#@end
___session_switch2() {
  local target_id="$1"
  local from_id="$2"
  local resolved_pid

  # Same target-first validation as the arity-1 variant. The <from>
  # argument is validated by 'session stop' itself; if it is invalid,
  # the batch aborts before the start is reached.
  if ! resolved_pid=$(resolve_session_id "$target_id"); then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Named session not found: $target_id\""
    return
  fi

  local session_dir="$VPN_SWITCH_BASE/.session/$resolved_pid"
  if [ ! -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Stale session link $target_id: $resolved_pid\" \"Session directory removed - run vpn-switch session clean\""
    return
  fi

  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session stop \"$from_id\""
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session start \"$resolved_pid\""
}

#@help _session_connect1
# @internal connect-chain step for session resume
#@end
_session_connect1() {
  local session_pid="$1"
  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"

  # Validate session exists
  if [ ! -d "$session_dir" ]; then
    generate_error "Session directory not found: $session_dir"
    return 0
  fi

  # Check if connect.sh exists
  local connect_script="$session_dir/connect.sh"
  if [ ! -f "$connect_script" ]; then
    generate_error "Session has no cached connect script: $session_pid"
    return 0
  fi

  # Execute the cached script (directly, using exec - no fork)
  # The connect.sh has proper shebang and is executable (0700)
  # The script is self-contained with isolated environment
  cat <<EOF
# Resume session: $session_pid (via self-contained script)
exec "$connect_script"
EOF
}

#@help _session_save0
# @internal arity-0 sibling of 'session save' (saves as the default session)
#@end
_session_save0() {
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  # Validate FIRST - find most recent session using 'latest' symlink
  local latest_link="$session_proto_dir/latest"
  if [ ! -L "$latest_link" ]; then
    generate_error "No recent session found - session/latest missing"
    display plain "Start a VPN session first"
    return 0
  fi

  # Resolve latest link to get PID
  local link_target=$(readlink "$latest_link")
  local latest_pid=$(basename -- "$link_target")

  # Verify session directory exists
  if [ ! -d "$VPN_SWITCH_BASE/.session/$latest_pid" ]; then
    generate_error "Stale latest link: points to non-existent session $latest_pid"
    return 0
  fi

  # NOW output commands (validation passed)
  # Create session/ directory if it doesn't exist
  if [ ! -d "$session_proto_dir" ]; then
    cat <<EOF
$MODIFY_DIR_CREATE "$session_proto_dir"
$MODIFY_FILE_PERMS 0750 "$session_proto_dir"
EOF
  fi

  local target_path="../.session/$latest_pid"
  local link_path="$session_proto_dir/default"

  # Output commands to create the default symlink
  # NOTE: Using ln -sfn instead of ln -sf because when the existing symlink
  # points to a directory (which .session/<PID> is), POSIX ln -sf will
  # create the link INSIDE that directory instead of replacing the symlink
  cat <<EOF
# Save session as: default
echo "# Saving session $latest_pid as 'default'"
$MODIFY_LINK_FORCE "$target_path" "$link_path"
echo "# Session saved: default -> $latest_pid"
EOF
}

#@help _session_save1
# @command session save [<name>]
# @summary Save the most-recent session under a name for later resumption
# @group   sessions
# @param   name  name to save under (default: the 'default' session)
# @returns shell commands (create the named session symlink)
# @example vpn-switch session save work
# @see     session start
#@end
_session_save1() {
  local session_name="$1"
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  # Validate FIRST - reject reserved keyword 'latest' (system-managed)
  if [ "$session_name" = "latest" ]; then
    generate_error "Cannot use reserved keyword 'latest' as session name"
    return 0
  fi

  # Validate FIRST - find most recent session using 'latest' symlink
  local latest_link="$session_proto_dir/latest"
  if [ ! -L "$latest_link" ]; then
    generate_error "No recent session found - session/latest missing"
    display plain "Start a VPN session first"
    return 0
  fi

  # Resolve latest link to get PID
  local link_target=$(readlink "$latest_link")
  local latest_pid=$(basename -- "$link_target")

  # Verify session directory exists
  if [ ! -d "$VPN_SWITCH_BASE/.session/$latest_pid" ]; then
    generate_error "Stale 'latest' link: points to non-existent session $latest_pid"
    return 0
  fi

  # NOW output commands (validation passed)
  # Create session/ directory if it doesn't exist
  if [ ! -d "$session_proto_dir" ]; then
    cat <<EOF
$MODIFY_DIR_CREATE "$session_proto_dir"
$MODIFY_FILE_PERMS 0750 "$session_proto_dir"
EOF
  fi

  local target_path="../.session/$latest_pid"
  local link_path="$session_proto_dir/$session_name"

  # Output commands to create the symlink
  # NOTE: Using ln -sfn instead of ln -sf because when the existing symlink
  # points to a directory (which .session/<PID> is), POSIX ln -sf will
  # create the link INSIDE that directory instead of replacing the symlink
  cat <<EOF
# Save session as: $session_name
echo "# Saving session $latest_pid as '$session_name'"
$MODIFY_LINK_FORCE "$target_path" "$link_path"
echo "# Session saved: $session_name -> $latest_pid"
EOF
}

#@help _session_clean0
# @command session clean
# @summary Remove stale session symlinks and orphaned sessions
# @group   sessions
# @returns cleanup report (commands are executed directly, interpreter: sh)
# @example vpn-switch session clean
# @see     session remove
# @see     session refresh
#@end
_session_clean0() {
  local session_proto_dir="$VPN_SWITCH_BASE/session"
  local session_base="$VPN_SWITCH_BASE/.session"

  # Counters for summary (generation time)
  local stale_link_count=0
  local removed_count=0
  local kept_count=0
  local active_count=0

  echo "# Session cleanup (symlinks + stale sessions)"

  # Part 1: Scan for stale symlinks at GENERATION TIME
  if [ -d "$session_proto_dir" ]; then
    echo "#"
    echo "# Part 1: Stale symlink cleanup"

    local found_stale=0
    for link in "$session_proto_dir"/*; do
      [ ! -L "$link" ] && continue

      # Check if target exists NOW (generation time)
      if [ ! -e "$link" ]; then
        found_stale=1
        local link_name=$(basename -- "$link")
        local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "unknown")
        local target_name=$(basename -- "$target")

        echo "echo '# Removing stale link: $link_name → $target_name'"
        echo "$MODIFY_LINK_REMOVE '$link'"
        stale_link_count=$((stale_link_count + 1))
      fi
    done

    if [ "$found_stale" -eq 0 ]; then
      echo "echo '# No stale symlinks found'"
    fi
  fi

  # Part 2: Scan for stale sessions at GENERATION TIME
  if [ -d "$session_base" ]; then
    echo "#"
    echo "# Part 2: Stale session cleanup"

    # Build list of referenced PIDs NOW (generation time)
    local referenced_pids=""
    if [ -d "$session_proto_dir" ]; then
      for link in "$session_proto_dir"/*; do
        [ ! -L "$link" ] && continue
        local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "")
        if [ -n "$target" ]; then
          local target_pid=$(basename -- "$target")
          case " $referenced_pids " in
            *" $target_pid "*) ;;
            *) referenced_pids="$referenced_pids $target_pid" ;;
          esac
        fi
      done
    fi

    local found_sessions=0
    for session_dir in "$session_base"/*/; do
      [ ! -d "$session_dir" ] && continue
      found_sessions=1

      local pid=$(basename -- "$session_dir")

      # Check if session is still alive NOW (generation time)
      # Use is_session_alive() to prevent PID recycling false positives
      if is_session_alive "$session_dir"; then
        local vpn_pid=""
        if [ -f "$session_dir/vpn.pid" ]; then
          vpn_pid=$(cat "$session_dir/vpn.pid" 2>>"$LOG_FILE" || echo "")
        fi
        echo "echo '# Skipping active session: $pid (VPN process $vpn_pid running)'"
        active_count=$((active_count + 1))
        continue
      fi

      # Process is dead - check if referenced for resumption
      case " $referenced_pids " in
        *" $pid "*)
          # Dead but referenced - keep for resumption
          echo "echo '# Keeping session $pid (saved for resumption)'"
          kept_count=$((kept_count + 1))
          ;;
        *)
          # Dead and unreferenced - destroy interface and remove session
          local session_protocol=""
          local session_interface=""
          if [ -f "$session_dir/protocol" ]; then
            session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE" || echo "")
          fi
          if [ -f "$session_dir/interface" ]; then
            session_interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "")
          fi

          # Note: session clean is a DATABASE cleanup function only
          # It does NOT destroy interfaces - that's the job of 'vpn-switch stop'
          # Stale interfaces should be cleaned manually or via stop/disconnect commands

          # Output remove command
          echo "echo '# Removing stale session: $pid (process dead, unreferenced)'"
          echo "$MODIFY_DIR_REMOVE '$session_base/$pid'"
          removed_count=$((removed_count + 1))
          ;;
      esac
    done

    if [ "$found_sessions" -eq 0 ]; then
      echo "echo '# No sessions found'"
    fi
  fi

  # Summary (computed at generation time, output as concrete echo)
  echo "#"
  echo "# Summary"
  if [ "$stale_link_count" -eq 0 ] && [ "$removed_count" -eq 0 ]; then
    echo "echo '# No cleanup needed'"
  else
    [ "$stale_link_count" -gt 0 ] && echo "echo '# Removed $stale_link_count stale symlink(s)'"
    [ "$removed_count" -gt 0 ] && echo "echo '# Removed $removed_count stale session(s)'"
  fi
  echo "echo '# Session cleanup complete'"
}

# _session_refresh0 - Reconcile interface ownership against the peers actually
# loaded on the live interface.
#
# Terminal function (outputs sh commands; interpreter override 'sh'). Repairs
# the drift where session/latest-$interface points at a session whose config is
# no longer the one loaded on the interface - e.g. a resume re-pointed ownership
# but `wg-quick up` then failed because the interface was already up with a
# different config (connect.sh appends the ownership symlink unconditionally).
# The loaded WireGuard peer set is the ground truth: this finds the session whose
# stored config matches and re-points the ownership symlink to it, so
# `session list` reports the session that is genuinely live.
#
# Conservative: acts only on positive evidence. If the loaded peer set cannot be
# read (interface up but needs root, non-WireGuard, etc.) ownership is left
# untouched and reported. Operates only on symlinks in the user-owned session/
# directory, so it needs no elevated privileges. Cf. session_peer_matches_interface()
# in vpn-switch.sh, which uses the same fingerprint to demote stale sessions in
# is_session_alive().
#@help _session_refresh0
# @command session refresh
# @summary Reconcile interface ownership with the loaded peers
# @group   sessions
# @returns shell commands (re-point / remove ownership symlinks)
# @example vpn-switch session refresh
# @see     session list
# @see     session clean
#@end
_session_refresh0() {
  local session_proto_dir="$VPN_SWITCH_BASE/session"
  local session_base="$VPN_SWITCH_BASE/.session"

  echo "# Reconcile interface ownership against loaded peers"

  if [ ! -d "$session_base" ]; then
    echo "echo '# No sessions found'"
    return 0
  fi

  # Referenced PIDs (saved via named links) - used to prefer user-saved sessions
  # when several sessions share an identical config.
  local referenced_pids=""
  if [ -d "$session_proto_dir" ]; then
    for link in "$session_proto_dir"/*; do
      [ ! -L "$link" ] && continue
      case "$(basename -- "$link")" in latest|latest-*) continue ;; esac
      local ref_target=$(readlink "$link" 2>>"$LOG_FILE" || echo "")
      [ -n "$ref_target" ] && referenced_pids="$referenced_pids $(basename -- "$ref_target")"
    done
  fi

  # Discover interfaces to reconcile: union of existing latest-* ownership links
  # and the interfaces of known WireGuard sessions.
  local interfaces=""
  if [ -d "$session_proto_dir" ]; then
    for link in "$session_proto_dir"/latest-*; do
      [ ! -L "$link" ] && continue
      local iname=$(basename -- "$link"); iname="${iname#latest-}"
      case " $interfaces " in *" $iname "*) ;; *) interfaces="$interfaces $iname" ;; esac
    done
  fi
  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue
    [ "$(cat "$session_dir/protocol" 2>>"$LOG_FILE" || echo "")" = "wireguard" ] || continue
    local si=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "")
    [ -n "$si" ] || continue
    case " $interfaces " in *" $si "*) ;; *) interfaces="$interfaces $si" ;; esac
  done

  if [ -z "$interfaces" ]; then
    echo "echo '# No interfaces to reconcile'"
    return 0
  fi

  local changed=0
  for iface in $interfaces; do
    echo "#"
    echo "# Interface: $iface"

    local link="$session_proto_dir/latest-$iface"
    local current=""
    [ -L "$link" ] && current=$(basename -- "$(readlink "$link" 2>>"$LOG_FILE")")

    # Ground truth: peers loaded on the live interface (read-only, no root needed
    # on supported platforms).
    local loaded=""
    loaded=$($EXAMINE_VPN_WIREGUARD_INTERFACE "$iface" 2>>"$LOG_FILE" \
      | grep '^peer:' \
      | sed 's/^peer:[[:space:]]*//' \
      | sort)

    if [ -z "$loaded" ]; then
      # Distinguish "interface down" (positive evidence -> stale link) from
      # "up but unreadable" (no judgement).
      if $EXAMINE_NETWORK_INTERFACE_EXISTS "$iface" >/dev/null 2>&1; then
        echo "echo '# $iface: peers unreadable (needs root?) - ownership left unchanged'"
      elif [ -n "$current" ]; then
        echo "echo '# $iface: interface down - removing stale ownership ($current)'"
        echo "$MODIFY_LINK_REMOVE '$link'"
        changed=$((changed + 1))
      else
        echo "echo '# $iface: interface down, no ownership link'"
      fi
      continue
    fi

    # Find sessions whose stored config matches the loaded peer set. Collect as
    # "ref<TAB>started<TAB>pid" so a single sort picks the rightful owner:
    # referenced sessions first, then the most-recently started.
    local candidates=""
    for session_dir in "$session_base"/*/; do
      [ ! -d "$session_dir" ] && continue
      local pid=$(basename -- "$session_dir")
      [ "$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "")" = "$iface" ] || continue
      local conf="$session_dir/$iface.conf"
      [ -f "$conf" ] || continue
      local stored=$(grep -i '^[[:space:]]*PublicKey' "$conf" 2>>"$LOG_FILE" \
        | sed 's/^[[:space:]]*[Pp]ublic[Kk]ey[[:space:]]*=[[:space:]]*//' \
        | sort)
      [ "$stored" = "$loaded" ] || continue

      local started=$(cat "$session_dir/started" 2>>"$LOG_FILE" || echo "")
      local ref=0
      case " $referenced_pids " in *" $pid "*) ref=1 ;; esac
      candidates="${candidates}${ref}	${started}	${pid}
"
    done

    local best=""
    if [ -n "$candidates" ]; then
      best=$(printf '%s' "$candidates" | grep -v '^$' | sort | tail -1 | cut -f3)
    fi

    if [ -z "$best" ]; then
      echo "echo '# $iface: loaded config matches no known session (external/unknown) - left unchanged'"
    elif [ "$current" = "$best" ]; then
      echo "echo '# $iface: ownership already correct ($best)'"
    else
      echo "echo '# $iface: re-pointing ownership ${current:-none} -> $best'"
      echo "$MODIFY_LINK_FORCE '../.session/$best' '$link'"
      changed=$((changed + 1))
    fi
  done

  echo "#"
  echo "# Summary"
  if [ "$changed" -eq 0 ]; then
    echo "echo '# Ownership already consistent - no changes'"
  else
    echo "echo '# Reconciled ownership for $changed interface(s)'"
  fi
  echo "echo '# Session refresh complete'"
}

#@help _session_validate0
# @internal session bookkeeping validation (sub-check of 'validate')
#@end
_session_validate0() {
  local session_proto_dir="$VPN_SWITCH_BASE/session"
  local session_base="$VPN_SWITCH_BASE/.session"
  local has_errors=0
  local has_warnings=0

  echo "# === Session Validation ==="
  echo "#"

  # Part 1: Check for stale symlinks in session/
  echo "# Checking session symlinks..."
  if [ -d "$session_proto_dir" ]; then
    for link in "$session_proto_dir"/*; do
      [ ! -L "$link" ] && continue

      if [ ! -e "$link" ]; then
        local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "unknown")
        echo "# [ERROR] Stale symlink: session/$(basename -- "$link") → $(basename -- "$target")"
        has_errors=1
      fi
    done
  else
    echo "# [WARNING] Session directory not found: $session_proto_dir"
    has_warnings=1
  fi

  # Part 2: Check for unreferenced session directories
  echo "#"
  echo "# Checking session directories..."
  if [ -d "$session_base" ]; then
    # Build list of referenced PIDs
    local referenced_pids=""
    if [ -d "$session_proto_dir" ]; then
      for link in "$session_proto_dir"/*; do
        [ ! -L "$link" ] && continue
        local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "")
        if [ -n "$target" ]; then
          local target_pid=$(basename -- "$target")
          case " $referenced_pids " in
            *" $target_pid "*) ;;
            *) referenced_pids="$referenced_pids $target_pid" ;;
          esac
        fi
      done
    fi

    # Check each session directory
    for session_dir in "$session_base"/*/; do
      [ ! -d "$session_dir" ] && continue
      local pid=$(basename -- "$session_dir")

      # Check if unreferenced
      case " $referenced_pids " in
        *" $pid "*)
          # Referenced - check metadata integrity
          local protocol_file="$session_dir/protocol"
          local original_file="$session_dir/original"
          local interface_file="$session_dir/interface"

          if [ ! -f "$protocol_file" ]; then
            echo "# [ERROR] Missing protocol metadata: .session/$pid/protocol"
            has_errors=1
          fi

          if [ ! -f "$original_file" ]; then
            echo "# [ERROR] Missing original config metadata: .session/$pid/original"
            has_errors=1
          fi

          if [ ! -f "$interface_file" ]; then
            echo "# [WARNING] Missing interface metadata: .session/$pid/interface"
            has_warnings=1
          fi
          ;;
        *)
          # Unreferenced session
          echo "# [WARNING] Unreferenced session: .session/$pid (no links point to it)"
          has_warnings=1
          ;;
      esac
    done
  fi

  # Summary
  echo "#"
  if [ "$has_errors" -eq 0 ] && [ "$has_warnings" -eq 0 ]; then
    echo "# ✓ Session validation passed - no issues found"
    return 0
  elif [ "$has_errors" -eq 0 ]; then
    echo "# ⚠ Session validation completed with warnings"
    echo "# Run 'vpn-switch session clean' to remove unreferenced sessions"
    return 0
  else
    echo "# ✗ Session validation failed - errors found"
    echo "# Run 'vpn-switch session clean' to fix stale symlinks and remove unreferenced sessions"
    return 1
  fi
}

#@help ___session_dump0
# @internal session portion of 'dump'
#@end
___session_dump0() {
  local session_pseudo="$VPN_SWITCH_BASE/session"

  # Check if session directory exists
  if [ ! -d "$session_pseudo" ]; then
    # No sessions to dump - return empty (valid for set-combinator)
    return 0
  fi

  echo "# Dump named sessions"

  # Iterate over all symlinks in session/ directory
  for session_link in "$session_pseudo"/*; do
    # Skip if no links found
    [ ! -L "$session_link" ] && continue

    local session_name=$(basename -- "$session_link")

    # Skip 'latest' symlink (transient system state, recreated on next start)
    [ "$session_name" = "latest" ] && continue

    # Resolve symlink to get actual session directory
    local session_dir=$(readlink -f "$session_link" 2>>"$LOG_FILE")
    [ ! -d "$session_dir" ] && continue

    # Read session metadata
    local protocol_file="$session_dir/protocol"
    [ ! -f "$protocol_file" ] && continue

    local original_file="$session_dir/original"
    [ ! -f "$original_file" ] && continue

    local protocol=$(cat "$protocol_file" 2>>"$LOG_FILE")
    local original_config=$(cat "$original_file" 2>>"$LOG_FILE")

    # Validate we have the required metadata
    [ -z "$protocol" ] && continue
    [ -z "$original_config" ] && continue

    # Read interface from session metadata
    local interface_file="$session_dir/interface"
    [ ! -f "$interface_file" ] && continue
    local interface=$(cat "$interface_file" 2>>"$LOG_FILE")
    [ -z "$interface" ] && continue

    # Output feingranular commands to recreate session structure
    # This avoids calling 'connect' which would try to start the VPN
    # Uses a unique PID placeholder that will be replaced at restore time
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session create \"\$\$\""
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session populate \"\$\$\" \"$protocol\" \"$interface\""
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $protocol patch \"\$\$\" \"$original_config\""
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $protocol configure \"\$\$\""
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session save $session_name"
  done
}

#@help __session_help0
# @command session help
# @summary Show session-management command help
# @group   sessions
# @returns help text
# @example vpn-switch session help
#@end
__session_help0() {
  # Backward compatibility: delegate to new pattern "help session"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" help session"
}

#@help ___session_inspect0
# @internal session portion of 'inspect'
#@end
___session_inspect0() {
  # Save current ANSI setting (at generation time)
  ansi_original="${VPN_SWITCH_DISPLAY_ANSI}"

  # Disable ANSI if currently enabled (suppress stderr)
  if [ "${VPN_SWITCH_DISPLAY_ANSI}" != "0" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" setenv VPN_SWITCH_DISPLAY_ANSI 0 2>/dev/null"
  fi

  # Output section header (consistent with other inspect functions)
  cat <<'EOF'
# Section: Session Status
EOF

  # Batch combinator - delegates to three vpn-switch commands
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session list"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session enumerate"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session describe"

  # Restore ANSI to original value if we changed it (suppress stderr)
  if [ "${ansi_original}" != "0" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" setenv VPN_SWITCH_DISPLAY_ANSI ${ansi_original} 2>/dev/null"
  fi

  # Re-enable cache if it was enabled (suppress stderr)
  if [ -n "${VPN_SWITCH_INTERPRETER_environment_cache}" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" environment cache on 2>/dev/null"
  fi
}

#@help _session_enumerate0
# @internal session enumeration helper
#@end
_session_enumerate0() {
  # Terminal function - enumerate named sessions (internal, used by inspect)
  # Generation-time pattern: discover now, output only concrete echo commands
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  echo "# Named Sessions"
  echo "#"

  if [ ! -d "$session_proto_dir" ]; then
    echo "# (no session directory)"
    return 0
  fi

  local found=0
  for link in "$session_proto_dir"/*; do
    [ -L "$link" ] || continue
    found=1

    local name=$(basename -- "$link")
    local target=$($EXAMINE_LINK_TARGET "$link" 2>>"$LOG_FILE" || echo "unknown")

    echo "# $name → $target"
  done

  if [ "$found" -eq 0 ]; then
    echo "# (no named sessions)"
  fi
}

#@help _session_describe0
# @internal session description helper
#@end
_session_describe0() {
  # Terminal function - describe session scripts (internal, used by inspect)
  # Generation-time pattern: discover now, output only concrete comments
  local session_base="$VPN_SWITCH_BASE/.session"

  echo "# Session Scripts"
  echo "#"

  if [ ! -d "$session_base" ]; then
    echo "# (no session directory)"
    return 0
  fi

  local found=0
  for session_dir in "$session_base"/*/; do
    [ -d "$session_dir" ] || continue
    found=1

    local pid=$(basename -- "$session_dir")
    local protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE" || echo "unknown")
    local interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "unknown")

    echo "#"
    echo "# Session $pid ($protocol / $interface):"
    echo "#   Connect: $session_dir/connect.sh"
    echo "#   Disconnect: $session_dir/disconnect.sh"

    if [ -f "$session_dir/connect.sh" ]; then
      local connect_lines=$(wc -l < "$session_dir/connect.sh" 2>>"$LOG_FILE" || echo "?")
      echo "#   Connect size: $connect_lines lines"
    fi

    if [ -f "$session_dir/disconnect.sh" ]; then
      local disconnect_lines=$(wc -l < "$session_dir/disconnect.sh" 2>>"$LOG_FILE" || echo "?")
      echo "#   Disconnect size: $disconnect_lines lines"
    fi
  done

  if [ "$found" -eq 0 ]; then
    echo "# (no sessions)"
  fi
}

# Note: is_session_alive() is defined in vpn-switch.sh (not here) because
# it's needed by batch combinators (___wireguard_stop0, ___openvpn_stop0)
# which run before modules are loaded.


# --- sessions, interfaces, start and stop (out of vpn-switch.sh, 15.09.2026) ---

# random_select - Randomly select one item from list
#
# Input: items on stdin (one per line)
# Output: one randomly selected item
#
random_select() {
  local items=$(cat)
  local count=$(echo "$items" | wc -l | tr -d ' ')

  if [ "$count" -eq 0 ]; then
    return 1
  fi

  # Use /dev/urandom for random selection. od's decimal output is padded, and
  # the padding char differs by OS: OpenBSD zero-pads ("00826"), which $(())
  # would read as invalid octal (8/9 are not octal digits) and abort. Normalise
  # to a bare decimal via awk ($1+0) before the modulo so it is shell-agnostic.
  local rand
  rand=$(od -An -N2 -tu2 < /dev/urandom | awk '{print $1+0; exit}')
  local selected=$(( rand % count + 1 ))
  echo "$items" | sed -n "${selected}p"
}

# resolve_default_or_random - Resolve using default symlink or random selection
#
# Args: $1 - directory path
#       $2 - pattern to select from (e.g., "*.conf" or "*")
# Output: selected item name (basename)
#
resolve_default_or_random() {
  local dir="$1"
  local pattern="${2:-*}"

  # Check for default symlink
  if [ -L "$dir/default" ]; then
    local target=$(readlink "$dir/default")
    basename -- "$target"
    return 0
  fi

  # Random selection - list items matching pattern, exclude directories and reserved keywords
  local items=$(cd "$dir" && ls -1 $pattern 2>>"$LOG_FILE" | while read -r item; do
    [ ! -d "$item" ] && [ "$item" != "default" ] && [ "$item" != "latest" ] && echo "$item"
  done)

  # Return empty if no items found (let caller decide if that's an error)
  if [ -z "$items" ]; then
    echo ""
    return 0
  fi

  echo "$items" | random_select
}

#-----------------------------------------------------------------------------
# Session Management
#-----------------------------------------------------------------------------

# check_and_create_session - Validate and prepare session directory creation
#
# Args: $1 - interface name (e.g., wg0, tun0)
# Output: Commands to create session directory and handle conflicts
#
# IMPORTANT: This function is a BATCH COMBINATOR helper - it outputs commands
# to stdout and should ONLY be called from batch combinator functions (___).
# It must NOT be called from terminal functions or executed directly.
#
# The function outputs vpn-switch commands for:
# - Session conflict detection and resolution
# - Orphaned interface cleanup warnings
# - Session directory creation with proper permissions
#
# Phase 2.1.1: Updated to include interface metadata and proper file permissions
#
check_and_create_session() {
  local interface="$1"
  local session_dir="$VPN_SWITCH_BASE/.session/$$"

  # Check if session already exists (collision detection)
  # This prevents multiple VPN starts in the same process from overwriting each other
  if [ -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Session $$ already exists\" \"Cannot create multiple sessions in the same process\""
    return 1
  fi

  # Validation - check for existing sessions on this interface
  local session_base="$VPN_SWITCH_BASE/.session"
  if [ -d "$session_base" ]; then
    for session_dir_iter in "$session_base"/*/; do
      [ ! -d "$session_dir_iter" ] && continue

      # Read interface name from session
      local session_interface_file="$session_dir_iter/interface"
      local session_interface=""

      if [ ! -f "$session_interface_file" ]; then
        # Old session format without interface file - check protocol instead
        local session_protocol="$(cat "$session_dir_iter/protocol" 2>>"$LOG_FILE" || echo "unknown")"

        # Legacy: infer interface from protocol using dynamic variable lookup
        local interface_var="VPN_SWITCH_INTERFACE_${session_protocol}"
        eval "session_interface=\"\$$interface_var\""
        [ -z "$session_interface" ] && continue
      else
        session_interface="$(cat "$session_interface_file")"
      fi

      # Check if interfaces match
      if [ "$session_interface" = "$interface" ]; then
        local session_pid=$(basename "$session_dir_iter")

        # Skip current session (we may have just created it)
        if [ "$session_pid" = "$$" ]; then
          continue
        fi

        # Check if the session is actually alive (uses is_session_alive with ownership check)
        # Note: is_session_alive is defined in include/session.sh and checks:
        # 1. Ownership via session/latest-$interface symlink
        # 2. Interface existence
        # 3. Process existence (fallback)
        # This prevents false positives from PID recycling
        if is_session_alive "$session_dir_iter"; then
          local original_config=$(cat "$session_dir_iter/original" 2>>"$LOG_FILE" || echo "unknown")
          local config_name=$(basename "$original_config")
          echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"VPN already running on interface $interface\" \"PID: $session_pid, config: $config_name\" \"Stop it first: vpn-switch stop\""
          return 1
        fi
      fi
    done
  fi

  # Check for running VPN processes (database-aware, protocol-agnostic)
  # We warn about conflicts but allow creation because:
  # 1. Session creation happens at generation time (may not execute)
  # 2. Different databases should be isolated
  # 3. Same-database conflicts are caught by check #2 (session tracking)
  for protocol_dir in "$VPN_SWITCH_BASE"/*; do
    [ ! -d "$protocol_dir" ] && continue
    [ -L "$protocol_dir" ] && continue  # Skip symlinks

    local protocol=$(basename "$protocol_dir")
    is_pseudo_protocol "$protocol" && continue

    # Get binary path from environment variable (VPN_SWITCH_BINARY_<protocol>)
    local binary_var="VPN_SWITCH_BINARY_${protocol}"
    eval "local binary_path=\"\$$binary_var\""
    [ -z "$binary_path" ] && continue

    # Extract just the binary name for pgrep matching
    local binary_name=$(basename "$binary_path")

    if pgrep -f "${binary_name}.*${interface}" >/dev/null 2>&1; then
      local matching_pids=$(pgrep -f "${binary_name}.*${interface}")
      for pid in $matching_pids; do
        local cmdline=$(ps -p "$pid" -o args= 2>/dev/null || continue)

        if echo "$cmdline" | grep -q "$VPN_SWITCH_BASE"; then
          # Same database - orphaned process (check #2 should have caught tracked sessions)
          echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"Warning: Found orphaned $binary_name process for $interface (PID: $pid)\" \"Proceeding - interface cleanup will handle if needed\""
        else
          # Different database - warn about potential conflict
          echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"Warning: Interface $interface may be in use by another database (PID: $pid)\" \"Session created. Connect will fail if interface exists.\""
        fi
      done
    fi
  done

  # Fallback: Check for orphaned interfaces (platform-agnostic)
  if $EXAMINE_NETWORK_INTERFACES "$interface" >/dev/null 2>&1; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"Warning: Found orphaned interface $interface (no active process). Auto-destroying...\""
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" interface destroy \"$interface\""
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"Orphaned interface $interface destroyed\""
  fi

  # Output command to create minimal session directory (only PID file)
  # Uses existing _session_create1 terminal function for actual execution
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session create \"$$\""

  return 0
}

# get_session_process_pid - Get the actual VPN process PID for a session
#
# Args: $1 - session directory path
# Output: PID to stdout
#
# Returns the PID of the actual VPN process (wg-quick, openvpn, etc.)
# Falls back to session directory name if VPN process PID not yet captured.
#
# This abstracts the difference between:
#   - Session directory name (vpn-switch.sh PID - short-lived)
#   - Actual VPN process PID (wg-quick/openvpn - long-lived)
#
get_session_process_pid() {
  local session_dir="$1"

  # Try to read VPN process PID from metadata
  # This file is created during connection (protocol-agnostic: vpn.pid)
  local vpn_pid=$(cat "$session_dir/vpn.pid" 2>>"$LOG_FILE")

  if [ -n "$vpn_pid" ]; then
    echo "$vpn_pid"
  else
    # Fall back to session directory name (pre-connection state)
    basename "$session_dir"
  fi
}

# session_peer_matches_interface - Verify a session's stored peer set matches
# the peers actually loaded on the live interface.
#
# Args: $1 - Session directory path
#       $2 - Interface name (e.g. "wg0")
# Returns: 0 if the session's config matches the loaded interface OR the check
#          cannot be performed safely; 1 only on positive evidence of mismatch.
#
# Rationale: is_session_alive() trusts the session/latest-$interface ownership
# symlink to decide which session owns a live interface. If the interface is
# later reconfigured with a different peer (or the symlink drifts), the symlink
# can point at a session whose config is no longer loaded - so `session list`
# would report a stale session as active. This cross-check catches that drift.
#
# Conservative by design: this helper may only DEMOTE active->stopped, and only
# when it can positively read BOTH peer sets and they differ. Any uncertainty
# (non-WireGuard protocol, unreadable dump - e.g. requires root or wg missing,
# empty config) returns 0, so the existing no-root and OpenVPN behaviour is
# never regressed.
session_peer_matches_interface() {
  local session_dir="$1"
  local interface="$2"

  # Only WireGuard exposes a peer identity on the interface; skip others.
  local protocol=""
  if [ -f "$session_dir/protocol" ]; then
    protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE")
  fi
  [ "$protocol" = "wireguard" ] || return 0

  # Peers loaded on the live interface (read-only; works without root on
  # supported platforms). Empty/unreadable -> no judgement.
  local loaded=""
  loaded=$($EXAMINE_VPN_WIREGUARD_INTERFACE "$interface" 2>>"$LOG_FILE" \
    | grep '^peer:' \
    | sed 's/^peer:[[:space:]]*//' \
    | sort)
  [ -n "$loaded" ] || return 0

  # Peers declared by this session's stored config. Empty/unreadable -> no
  # judgement.
  local conf="$session_dir/$interface.conf"
  [ -f "$conf" ] || return 0
  local stored=""
  stored=$(grep -i '^[[:space:]]*PublicKey' "$conf" 2>>"$LOG_FILE" \
    | sed 's/^[[:space:]]*[Pp]ublic[Kk]ey[[:space:]]*=[[:space:]]*//' \
    | sort)
  [ -n "$stored" ] || return 0

  # Positive comparison: match -> 0, mismatch -> 1 (drift detected).
  [ "$loaded" = "$stored" ]
}

# is_session_alive - Check if a session's VPN process is running
#
# Args: $1 - Session directory path
# Returns: 0 if process is alive, 1 if dead
#
# Checks session liveness using multiple strategies:
# 1. Ownership check via session/latest-$interface symlink
# 2. Interface existence check
# 3. Peer cross-check (WireGuard): config loaded on the interface must match
# 4. Process existence check (may require sudo for cross-user)
#
# This function must be in vpn-switch.sh (not just session.sh) because
# it's called by batch combinators (___wireguard_stop0, etc.) which run
# before modules are loaded.
#
is_session_alive() {
  local session_dir="$1"

  # Sessions without vpn.pid are treated as stopped/stale
  # This includes:
  # - Legacy sessions (created before vpn.pid migration)
  # - Pending sessions (created but never connected)
  # - Broken sessions (vpn.pid deleted/lost)
  if [ ! -f "$session_dir/vpn.pid" ]; then
    return 1  # Mark as stopped
  fi

  # Read interface name
  local interface=""
  if [ -f "$session_dir/interface" ]; then
    interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE")
  fi

  # Primary check: Ownership + interface existence (works without root privileges)
  # Uses latest-$interface symlink to determine which session owns the interface
  # This prevents multiple sessions from claiming the same interface
  if [ -n "$interface" ]; then
    local session_proto_dir="$VPN_SWITCH_BASE/session"
    local ownership_link="$session_proto_dir/latest-$interface"

    # Check if ownership symlink exists and points to this session
    if [ -L "$ownership_link" ]; then
      local owner_session=$(readlink "$ownership_link" 2>>"$LOG_FILE" || echo "")
      local owner_pid=$(basename "$owner_session" 2>>"$LOG_FILE" || echo "")
      local this_pid=$(basename "$session_dir")

      # This session owns the interface - check if interface actually exists
      if [ "$owner_pid" = "$this_pid" ]; then
        if $EXAMINE_NETWORK_INTERFACE_EXISTS "$interface" >/dev/null 2>&1; then
          # Interface exists and we own it per the ownership symlink. Cross-check
          # that the peer actually loaded on the interface matches this session's
          # config; a mismatch means the interface was reconfigured by another
          # session and this one is effectively stopped (see
          # session_peer_matches_interface).
          if session_peer_matches_interface "$session_dir" "$interface"; then
            return 0  # We own the interface, it exists, and our config is loaded
          fi
          return 1    # We own the symlink but a different config is loaded → stopped
        else
          return 1  # We own it but interface is down
        fi
      else
        # Ownership symlink exists but points to different session
        # This session does NOT own the interface → stopped
        return 1
      fi
    fi

    # No ownership symlink exists
    # For old sessions (pre-ownership-tracking): check if interface exists
    # If interface doesn't exist, we need process check to distinguish:
    # - PID recycling (process dead) → stopped
    # - Test session or pending (process alive) → active
    if ! $EXAMINE_NETWORK_INTERFACE_EXISTS "$interface" >/dev/null 2>&1; then
      # Interface doesn't exist - use process check as final arbiter
      local pid=$(cat "$session_dir/vpn.pid" 2>>"$LOG_FILE")
      if $EXAMINE_PROCESS_EXISTS "$pid" 2>>"$LOG_FILE"; then
        return 0  # Process alive despite no interface (test/pending session)
      else
        return 1  # No interface + dead process → PID recycling, definitely stopped
      fi
    fi
  fi

  # Fallback check: Process exists (only reached for old sessions with existing interface)
  # Platform variable EXAMINE_PROCESS_EXISTS can be configured with sudo prefix
  # This is a last resort for sessions created before ownership tracking
  local pid=$(cat "$session_dir/vpn.pid" 2>>"$LOG_FILE")
  if $EXAMINE_PROCESS_EXISTS "$pid" 2>>"$LOG_FILE"; then
    return 0  # Process running (old session, interface exists, process alive)
  fi

  # All checks failed
  return 1  # Session is stopped
}

# find_session_by_interface - Find session directory by interface name
#
# Args: $1 - interface name (e.g., "wg0")
# Output: Session PID if found, empty string otherwise
# Returns: 0 if found, 1 if not found
#
find_session_by_interface() {
  local target_interface="$1"
  local session_base="$VPN_SWITCH_BASE/.session"

  [ ! -d "$session_base" ] && return 1

  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue

    local session_interface="$(cat "$session_dir/interface" 2>>"$LOG_FILE")"

    # Legacy sessions: infer interface from protocol
    if [ -z "$session_interface" ]; then
      local session_protocol="$(cat "$session_dir/protocol" 2>>"$LOG_FILE")"
      case "$session_protocol" in
        wireguard) session_interface="$VPN_SWITCH_INTERFACE_wireguard" ;;
        openvpn) session_interface="$VPN_SWITCH_INTERFACE_openvpn" ;;
        *) continue ;;
      esac
    fi

    if [ "$session_interface" = "$target_interface" ]; then
      basename "$session_dir"
      return 0
    fi
  done

  return 1
}

# _session_create1 - Create session directory with minimal structure
#
# Args: $1 - session PID
# Output: Shell commands to create session directory
#
# Terminal function - outputs shell commands for execution
#
#@help _session_create1
# @internal create a session metadata directory (start chain step)
#@end
_session_create1() {
  local session_pid="$1"
  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"

  cat <<EOF
$MODIFY_DIR_CREATE "$session_dir"
$MODIFY_FILE_PERMS 0750 "$session_dir"
echo "$session_pid" > "$session_dir/pid"
$MODIFY_FILE_PERMS 0640 "$session_dir/pid"
EOF
}

# __session_exists1 - Check for session directory collision
#
# Args: $1 - session PID
# Output: error command if collision exists, log command otherwise
#
# Combinator - outputs exactly 1 vpn-switch command
#
#@help __session_exists1
# @internal guard: refuse a duplicate session for the current process
#@end
__session_exists1() {
  local session_pid="$1"
  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"

  if [ -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Session $session_pid already exists\" \"Cannot create multiple sessions in the same process\""
  else
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"Session directory available for $session_pid\""
  fi
}

# __session_conflicts2 - Check for interface conflict with existing sessions
#
# Args: $1 - session PID
#       $2 - interface name
# Output: error command if conflict exists, log command otherwise
#
# Combinator - outputs exactly 1 vpn-switch command
#
#@help __session_conflicts2
# @internal guard: detect interface conflicts before connect
#@end
__session_conflicts2() {
  local session_pid="$1"
  local interface="$2"
  local session_base="$VPN_SWITCH_BASE/.session"

  # No sessions directory - no conflicts
  if [ ! -d "$session_base" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"No sessions directory - no interface conflicts\""
    return
  fi

  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue

    # Interface file is required - skip sessions without it
    [ ! -f "$session_dir/interface" ] && continue

    local session_interface
    session_interface=$(cat "$session_dir/interface")

    # Different interface - no conflict
    [ "$session_interface" != "$interface" ] && continue

    # Same interface - check if it's another session
    local other_pid
    other_pid=$(basename "$session_dir")

    # Skip self
    [ "$other_pid" = "$session_pid" ] && continue

    # Check if VPN process is running
    [ ! -f "$session_dir/vpn.pid" ] && continue

    local vpn_pid
    vpn_pid=$(cat "$session_dir/vpn.pid")

    # Use platform variable for process check
    if $EXAMINE_PROCESS_EXISTS "$vpn_pid" 2>/dev/null; then
      local original_config
      original_config=$(cat "$session_dir/original" 2>/dev/null || echo "unknown")
      local config_name
      config_name=$(basename "$original_config")

      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"VPN already running on interface $interface\" \"PID: $other_pid, config: $config_name\" \"Stop it first: vpn-switch stop\""
      return
    fi
  done

  # No conflicts found
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"No interface conflicts found for $interface\""
}

# __interface_check1 - Check if network interface exists (orphan check)
#
# Args: $1 - interface name
# Output: error command if interface exists, log command otherwise
#
# Terminal function - outputs shell commands to destroy an interface
#
#@help _interface_destroy1
# @internal destroy an orphaned interface (cleanup chain step)
#@end
_interface_destroy1() {
  local interface="$1"
  # Use printf format template for platform independence (FreeBSD vs Linux)
  printf '%s 2>>"$LOG_FILE" || true\n' "$(printf "$MODIFY_INTERFACE_DESTROY_FMT" "$interface")"
}

# Combinator - outputs exactly 1 vpn-switch command
#
#@help __interface_check1
# @internal guard: check interface availability before connect
#@end
__interface_check1() {
  local interface="$1"

  if $EXAMINE_NETWORK_INTERFACES "$interface" >/dev/null 2>&1; then
    local destroy_cmd=$(printf "$MODIFY_INTERFACE_DESTROY_FMT" "$interface")
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Orphaned interface $interface exists\" \"Please destroy it manually: $destroy_cmd\""
  else
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"Interface $interface is available\""
  fi
}

# ___session_prepare3 - Prepare session with validation
#
# Args: $1 - session PID
#       $2 - protocol name
#       $3 - interface name
# Output: vpn-switch commands for session create and populate
#
# Batch combinator - performs validation at generation time, outputs commands
# Protocol-agnostic: caller provides interface directly
#
#@help ___session_prepare3
# @internal prepare a session (exists/conflicts/check/create/populate chain)
#@end
___session_prepare3() {
  local session_pid="$1"
  local protocol="$2"
  local interface="$3"

  # All checks passed - output commands
  cat <<EOF
"\$VPN_SWITCH_CONTEXT_SCRIPT" session exists "$session_pid"
"\$VPN_SWITCH_CONTEXT_SCRIPT" session conflicts "$session_pid" "$interface"
"\$VPN_SWITCH_CONTEXT_SCRIPT" interface check "$interface"
"\$VPN_SWITCH_CONTEXT_SCRIPT" session create "$session_pid"
"\$VPN_SWITCH_CONTEXT_SCRIPT" session populate "$session_pid" "$protocol" "$interface"
EOF
}

# _session_populate3 - Populate session directory with metadata
#
# Args: $1 - session PID
#       $2 - protocol (wireguard or openvpn)
#       $3 - interface name
# Output: Shell commands to populate session metadata
#
# Terminal function - outputs shell commands for execution
# Protocol-agnostic: caller provides interface directly
#
# NOTE: Stale session cleanup is performed by 'session clean' command
# which should be run periodically to clean up dead sessions and orphaned interfaces.
#
#@help _session_populate3
# @internal write session metadata (protocol, interface, original)
#@end
_session_populate3() {
  local pid="$1"
  local protocol="$2"
  local interface="$3"
  local session_dir="$VPN_SWITCH_BASE/.session/$pid"

  cat <<EOF
echo "$protocol" > "$session_dir/protocol"
echo "$interface" > "$session_dir/interface"
$EXAMINE_DATE_NOW > "$session_dir/started"
$MODIFY_FILE_PERMS 0640 "$session_dir/protocol" "$session_dir/interface" "$session_dir/started"
EOF
}

#-----------------------------------------------------------------------------
# Configuration File Patching
#-----------------------------------------------------------------------------

# is_pseudo_protocol - Check if directory name is a pseudo-protocol
#
# Args: $1 - protocol/directory name
# Returns: 0 if pseudo-protocol (should skip), 1 if real protocol
#
# Pseudo-protocols are special directories that are NOT VPN protocols.
# Detection rules:
#   1. Hidden directories (.*) are always pseudo-protocols
#   2. Directories in VPN_SWITCH_PSEUDO_PROTOCOL variable (space-separated list)
#
# Default VPN_SWITCH_PSEUDO_PROTOCOL: "session environment"
# Override in tests to simulate "no protocols found" scenarios
#
is_pseudo_protocol() {
  local proto="$1"

  # Hidden directories are always pseudo-protocols
  case "$proto" in
    .*) return 0 ;;
  esac

  # Check against configured pseudo-protocol list
  local pseudo
  for pseudo in $VPN_SWITCH_PSEUDO_PROTOCOL; do
    [ "$proto" = "$pseudo" ] && return 0
  done

  return 1
}

#-----------------------------------------------------------------------------
# Stop/Disconnect Commands (Combinator Pattern)
#-----------------------------------------------------------------------------

# __stop0 - Stop all VPN sessions (filesystem discovery)
#
# Output: Combinator commands (one per protocol)
#
# Uses filesystem discovery: VPN_SWITCH_BASE subdirectories = protocols.
# Special handling: "session" pseudo-protocol runs first (stale cleanup).
#
#@help ___stop0
# @command stop
# @summary Stop every active VPN session (idempotent)
# @group   connection
# @returns disconnect commands for all active sessions
# @example vpn-switch stop
# @see     start
#@end
___stop0() {
  # First: Stop all protocol interfaces (VPN teardown)
  local base_dir="$VPN_SWITCH_BASE"
  [ ! -d "$base_dir" ] && return 0

  for protocol_dir in "$base_dir"/*/; do
    [ ! -d "$protocol_dir" ] && continue

    local protocol=$(basename "$protocol_dir")

    # Skip pseudo-protocols (consistent with other batch combinators)
    is_pseudo_protocol "$protocol" && continue

    # Check if protocol has a stop function (prevent usage() spam)
    # Look for __<protocol>_stop0 or __<protocol>_stop1 in ANCHOR_FUNCTIONS list
    # (Functions may be in modules, not in main script, so check the complete list)
    if ! echo "$ANCHOR_FUNCTIONS" | grep -q "__${protocol}_stop"; then
      echo "# Skipping protocol '$protocol' (no stop function implemented)"
      continue
    fi

    # Output stop command for each discovered protocol
    # Script path uses literal variable reference for portability
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $protocol stop"
  done

  # Note: Session cleanup is now explicit - users should run 'vpn-switch session clean'
  # to remove unreferenced sessions after stopping VPNs
}

# __stop1 - Stop specific VPN session by interface name
#
# Args: $1 - interface name (e.g., "wg0", "tun0")
# Output: Combinator command for protocol-specific stop
#
# Resolves interface → protocol, outputs "<protocol> stop <interface>"
#
#@help __stop1
# @internal arity-1 sibling of 'stop' (stop a specific interface)
#@end
__stop1() {
  local interface="$1"

  # Find session for this interface
  local session_pid=$(find_session_by_interface "$interface")

  if [ -z "$session_pid" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No active VPN session found for interface: $interface\""
    return
  fi

  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"
  local session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE")

  if [ -z "$session_protocol" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Could not determine protocol for interface: $interface\""
    return
  fi

  # Output protocol-specific stop command
  # Script path uses literal variable reference for portability
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $session_protocol stop $interface"
}

#-----------------------------------------------------------------------------
# Database Initialization (Phase 2.3.1)
#-----------------------------------------------------------------------------

#-----------------------------------------------------------------------------
# Phase Template Lifting Engine
#-----------------------------------------------------------------------------

# __start1 - Protocol-agnostic start with auto-detection (Phase 3.4.1)
#
# Args: $1 - config name (can be in any protocol directory)
# Output: Resolved protocol start command (single vpn-switch command)
#
# Resolution strategy (three-tier):
# 1. Extension link fast path: If name has extension and extension link exists,
#    resolve protocol via link (O(1) - fast)
# 2. Filesystem search: Scan all protocol directories for matching config
#    (O(n) protocols - slower but flexible)
# 3. Error handling: Clear messages for not found or ambiguous matches
#
# Benefits:
# - No hardcoded protocol names
# - User can add new protocols (e.g., ikev2/) without modifying this function
# - Extension links provide fast path for common case
# - Fallback search handles configs without extensions
#
#@help __start1
# @command start [<config>]
# @completion config any-config
# @summary Connect using a config; with no argument, resume the default session or pick at random
# @group   connection
# @param   config  config/category/group/alias to start; omit to use the 'default' session, otherwise a random protocol and config
# @returns connect commands (delegates to the resolved protocol)
# @example vpn-switch start privacy
# @example vpn-switch start
# @see     stop
# @see     session save
# @see     wireguard start
#@end
__start1() {
  local name="$1"

  if [ -z "$name" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"start: config name required\""
    return
  fi

  # Extract extension if present
  local ext=""
  case "$name" in
    *.*) ext="${name##*.}" ;;
  esac

  # Fast path: Extension link exists
  if [ -n "$ext" ] && [ -L "$VPN_SWITCH_BASE/$ext" ]; then
    local link_target
    link_target=$(readlink "$VPN_SWITCH_BASE/$ext" 2>>"$LOG_FILE")
    if [ $? -ne 0 ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"start: failed to resolve extension link: $ext\""
      return
    fi

    local protocol
    protocol=$(basename "$link_target")

    # Validate protocol directory exists
    if [ ! -d "$VPN_SWITCH_BASE/$protocol" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"start: extension link '$ext' points to non-existent protocol '$protocol'\""
      return
    fi

    # Delegate to protocol-specific start
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $protocol start $name"
    return
  fi

  # Fallback: Search all protocol directories
  local matches=""
  local proto
  for protocol_dir in "$VPN_SWITCH_BASE"/*; do
    # Skip symlinks (extension links like conf→wireguard/)
    [ -L "$protocol_dir" ] && continue
    [ -d "$protocol_dir" ] || continue
    proto=$(basename "$protocol_dir")

    # Skip pseudo-protocols
    is_pseudo_protocol "$proto" && continue

    # Look for config (exact match, with extension, or as category)
    for candidate in "$protocol_dir/$name" "$protocol_dir/$name".*; do
      # Check if file, symlink, or directory (category)
      if [ -f "$candidate" ] || [ -L "$candidate" ] || [ -d "$candidate" ]; then
        config_basename=$(basename "$candidate")

        # Add to matches
        if [ -z "$matches" ]; then
          matches="$proto:$config_basename"
        else
          matches="$matches $proto:$config_basename"
        fi
        break  # Only count first match per protocol
      fi
    done
  done

  # Handle results
  case "$matches" in
    "")
      # No matches found - build list of protocols searched
      local proto_list=""
      for protocol_dir in "$VPN_SWITCH_BASE"/*; do
        [ -L "$protocol_dir" ] && continue
        [ -d "$protocol_dir" ] || continue
        proto=$(basename "$protocol_dir")
        is_pseudo_protocol "$proto" && continue
        if [ -z "$proto_list" ]; then
          proto_list="$proto/$name"
        else
          proto_list="$proto_list, $proto/$name"
        fi
      done
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"start: config not found: $name\" \"Searched in: $proto_list\""
      return
      ;;
    *" "*)
      # Multiple matches - build list and suggest first match
      local match_list=""
      for match in $matches; do
        if [ -z "$match_list" ]; then
          match_list="${match%%:*}/${match#*:}"
        else
          match_list="$match_list, ${match%%:*}/${match#*:}"
        fi
      done
      # Get first match for suggestion
      local first_match="${matches%% *}"
      local first_proto="${first_match%%:*}"
      local first_config="${first_match#*:}"
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Multiple configs match: $name\" \"Found: $match_list\" \"Use: vpn-switch $first_proto start $first_config\""
      return
      ;;
    *)
      # Single match - use it
      proto="${matches%%:*}"
      config="${matches#*:}"
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $proto start $config"
      ;;
  esac
}

# __start0 - Protocol-agnostic start using default or random (Phase 3.4.1)
#
# No args - tries default session, then random protocol selection
# Output: Resolved protocol start command or session start command
#
# Resolution strategy:
# 1. Try session/default link (if exists, resume that session)
# 2. Otherwise: discover protocols and pick random config from random protocol
# 3. Skip pseudo-protocols during discovery
#
# Benefits:
# - No hardcoded protocol names
# - User can add new protocols and they'll be included in random selection
# - Seamless integration with session management (default session takes priority)
#
#@help __start0
# @internal arity-0 sibling of 'start' (use the default config)
#@end
__start0() {
  # Try default session first
  if [ -L "$VPN_SWITCH_BASE/session/default" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session start"
    return
  fi

  # No default session - discover protocols and pick randomly
  local protocols=""
  local proto
  for dir in "$VPN_SWITCH_BASE"/*; do
    # Skip symlinks (extension links like conf→wireguard/)
    [ -L "$dir" ] && continue
    [ -d "$dir" ] || continue
    proto=$(basename "$dir")

    # Skip pseudo-protocols
    is_pseudo_protocol "$proto" && continue

    # Check if protocol has any configs
    if ls "$dir"/*.* >/dev/null 2>&1 || \
       ls "$dir"/*/ >/dev/null 2>&1; then
      protocols="$protocols $proto"
    fi
  done

  # No protocols found
  if [ -z "$protocols" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"start: no VPN protocols found\" \"Run 'vpn-switch import' to add configs\""
    return 0
  fi

  # Pick random protocol
  local proto_count
  proto_count=$(printf "%s" "$protocols" | wc -w | tr -d ' ')
  local proto_index
  proto_index=$(($(date +%s) % proto_count + 1))
  local selected_proto
  selected_proto=$(printf "%s" "$protocols" | awk "{print \$$proto_index}")

  # Delegate to protocol-specific start with no args (picks random config)
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $selected_proto start"
}

#-----------------------------------------------------------------------------
# Error Commands - Terminal Functions
#-----------------------------------------------------------------------------
