# session.sh - Dynamically loaded session module
# Generated by extract-modules-v2.sh
# DO NOT EDIT - This file is auto-generated

# resolve_session_id - Resolve a session argument to a numeric PID
#
# Args: $1 - session ID (numeric PID or named-session symlink)
# Output (stdout): resolved numeric PID, one line, no trailing whitespace
# Returns: 0 on success, 1 if argument is non-numeric and no matching
#          session/<name> symlink exists
#
# Used by every command that takes a "<PID>|<name>" argument:
#   - _session_show1, _session_remove1 (terminal functions)
#   - __session_start1, __session_stop1 (combinator functions)
#
# Helpers like this one (no underscore prefix) are *not* part of the
# combinator/terminal anchor set — they're plain shell utilities called
# from anchor functions. Cf. is_session_alive() in vpn-switch.sh which
# follows the same convention.
#
# This helper deliberately does NOT verify that .session/$pid exists.
# Callers check that separately so they can produce context-appropriate
# diagnostics ("Session not found" vs. "Stale session link").
resolve_session_id() {
  local session_id="$1"

  if echo "$session_id" | grep -q '^[0-9][0-9]*$'; then
    printf '%s\n' "$session_id"
    return 0
  fi

  local named_link="$VPN_SWITCH_BASE/session/$session_id"
  if [ ! -L "$named_link" ]; then
    return 1
  fi

  basename -- "$(readlink "$named_link")"
  return 0
}

#@help __session_disconnect1
# @command session disconnect <PID>
# @summary Lower-level disconnect of a session by PID (no name resolution)
# @group   sessions
# @param   PID  session PID to disconnect
# @returns disconnect commands
# @example vpn-switch session disconnect 12345
# @see     session stop
#@end
__session_disconnect1() {
  local session_pid="$1"
  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"

  # Check if session exists
  if [ ! -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"Session $session_pid already removed [stale cleanup or concurrent stop]\""
    return 0
  fi

  # Read session metadata
  local session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE")
  local session_interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE")

  # Validate protocol metadata exists and protocol directory exists (filesystem-based detection)
  if [ -z "$session_protocol" ] || [ ! -d "$VPN_SWITCH_BASE/$session_protocol" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Invalid protocol for session $session_pid: '${session_protocol:-[empty]}'\""
    return 0
  fi

  # Legacy sessions: infer interface from protocol using environment variables
  # Uses dynamic variable lookup: VPN_SWITCH_INTERFACE_<protocol>
  if [ -z "$session_interface" ]; then
    eval "session_interface=\"\$VPN_SWITCH_INTERFACE_${session_protocol}\""
    if [ -z "$session_interface" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Legacy session $session_pid has no interface metadata\" \"No VPN_SWITCH_INTERFACE_${session_protocol} configured\""
      return 0
    fi
  fi

  # Delegate to protocol-specific disconnect
  # Session layer trusts protocol metadata from filesystem validation above
  # Script path uses literal variable reference for portability
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $session_protocol disconnect $session_interface"
}

#@help ___session_stop0
# @internal batch sibling of 'session stop' (stops all active sessions)
#@end
___session_stop0() {
  # Zero-arity variant: emit a 'session stop <pid>' for EVERY session.
  #
  # Rationale: __session_disconnect1 (the eventual target) is idempotent
  # — it cleans up whether the session is alive or already dead. So
  # rather than pick one session (which risks leaving an active session
  # running if "latest" happens to be a dead one), we stop them all.
  # Each batch step routes through __session_stop1 → __session_disconnect1
  # which does the right thing for its own state.
  #
  # This also eliminates the racy double-check that the previous
  # combinator design had (alive-check in stop0, alive-check again in
  # stop1) and the duplication with _session_list0's iteration.
  local session_base="$VPN_SWITCH_BASE/.session"

  if [ ! -d "$session_base" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No sessions found\""
    return
  fi

  local has_sessions=0
  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue
    has_sessions=1
    local pid=$(basename -- "$session_dir")
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session stop \"$pid\""
  done

  if [ "$has_sessions" = "0" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No sessions found\""
  fi
}

#@help __session_stop1
# @command session stop [<name>|<PID>]
# @summary Stop an active session; with no argument, stop all active sessions
# @group   sessions
# @param   name|PID  session to stop (default: all active sessions)
# @returns disconnect commands
# @example vpn-switch session stop work
# @see     session start
#@end
__session_stop1() {
  local session_id="$1"
  local resolved_pid

  # Accept either a numeric PID or a named-session symlink.
  if ! resolved_pid=$(resolve_session_id "$session_id"); then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Named session not found: $session_id\""
    return
  fi

  # Check if session exists
  local session_dir="$VPN_SWITCH_BASE/.session/$resolved_pid"
  if [ ! -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Stale session link $session_id: $resolved_pid\" \"Session directory removed - run vpn-switch session clean\""
    return
  fi

  # No alive-check here: __session_disconnect1 (and the underlying
  # disconnect.sh phases) are idempotent — they clean up whether the
  # VPN process is still running or already dead. The alive-check
  # belongs to display (list/show) and safety (remove/clean) contexts,
  # not to the stop routing path.
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session disconnect \"$resolved_pid\""
}

#@help _session_list0
# @command session list
# @summary Show all active and saved sessions
# @group   sessions
# @returns session table (active/stopped, referenced/unreferenced)
# @example vpn-switch session list
# @see     session refresh
# @see     session clean
#@end
_session_list0() {
  local session_base="$VPN_SWITCH_BASE/.session"
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  # Header (always output)
  echo '# VPN Sessions:'
  echo '#'

  if [ ! -d "$session_base" ]; then
    echo '# ⚠ No active sessions (session directory missing)'
    return 0
  fi

  local has_sessions=0
  for session_dir in "$session_base"/*/; do
    [ -d "$session_dir" ] && has_sessions=1 && break
  done

  if [ "$has_sessions" = "0" ]; then
    echo '# - No active sessions'
    return 0
  fi

  # Build referenced PIDs list
  local referenced_pids=""
  if [ -d "$session_proto_dir" ]; then
    for link in "$session_proto_dir"/*; do
      [ ! -L "$link" ] && continue
      local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "")
      if [ -n "$target" ]; then
        local target_pid=$(basename -- "$target")
        case " $referenced_pids " in
          *" $target_pid "*) ;;
          *) referenced_pids="$referenced_pids $target_pid" ;;
        esac
      fi
    done
  fi

  # Table header
  printf '# %-6s %-12s %-10s %-8s %-21s %-22s %s\n' 'PID' 'SESSION' 'PROTOCOL' 'IFACE' 'STATE' 'CONFIG' 'STARTED'
  printf '# %-6s %-12s %-10s %-8s %-21s %-22s %s\n' '---' '-------' '--------' '-----' '-----' '------' '-------'

  # Session rows
  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue

    local session_pid=$(basename -- "$session_dir")
    local session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE" || echo "unknown")
    local session_interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "unknown")
    local session_original=$(cat "$session_dir/original" 2>>"$LOG_FILE" || echo "unknown")
    local session_started=$(cat "$session_dir/started" 2>>"$LOG_FILE" || echo "unknown")
    local config_basename=$(basename -- "$session_original")

    # Collect session names for this PID (from session/ symlinks)
    local session_names=""
    if [ -d "$session_proto_dir" ]; then
      for link in "$session_proto_dir"/*; do
        [ ! -L "$link" ] && continue
        local link_name=$(basename "$link")

        # Skip system-generated links (latest, latest-wg0, etc.)
        case "$link_name" in
          latest|latest-*) continue ;;
        esac

        local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "")
        local target_pid=$(basename -- "$target" 2>>"$LOG_FILE" || echo "")

        if [ "$target_pid" = "$session_pid" ]; then
          if [ -z "$session_names" ]; then
            session_names="$link_name"
          else
            session_names="$session_names,$link_name"
          fi
        fi
      done
    fi

    # If no names, use "-"
    [ -z "$session_names" ] && session_names="-"

    local vpn_state="stopped"
    is_session_alive "$session_dir" && vpn_state="active"

    local ref_state="unreferenced"
    case " $referenced_pids " in
      *" $session_pid "*) ref_state="referenced" ;;
    esac

    local state="${vpn_state}/${ref_state}"

    printf '# %-6s %-12s %-10s %-8s %-21s %-22s %s\n' "$session_pid" "$session_names" "$session_protocol" "$session_interface" "$state" "$config_basename" "$session_started"
  done

  # Footer
  cat <<'EOF'
#
# States: active=VPN running, stopped=VPN disconnected, referenced=has saved links, unreferenced=no links
# Tip: Use 'vpn-switch session clean' to remove unreferenced sessions
EOF
}

#@help __session_show0
# @internal arity-0 sibling of 'session show' (latest session)
#@end
__session_show0() {
  # Combinator - find most recent session and delegate to show command
  local session_base="$VPN_SWITCH_BASE/.session"

  if [ ! -d "$session_base" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No active sessions found\""
    return
  fi

  # Find most recent session (by modification time)
  local latest_session=""
  local latest_mtime=0

  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue

    # Get modification time (seconds since epoch)
    local mtime=$($CMD_STAT_MTIME "$session_dir" 2>>"$LOG_FILE" || echo 0)

    if [ "$mtime" -gt "$latest_mtime" ]; then
      latest_mtime="$mtime"
      latest_session="$session_dir"
    fi
  done

  if [ -z "$latest_session" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No active sessions found\""
    return
  fi

  # Output vpn-switch command (combinator pattern)
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session show \"$(basename -- "$latest_session")\""
}

#@help _session_show1
# @command session show [<name>|<PID>]
# @summary Show a session's cached connect script and metadata
# @group   sessions
# @param   name|PID  saved session name or PID (default: latest)
# @returns the session's connect.sh and metadata
# @example vpn-switch session show work
#@end
_session_show1() {
  local session_id="$1"
  local session_pid

  echo '# Session Show'
  echo '#'

  # Accept either a numeric PID or a named-session symlink, mirroring
  # __session_start1 / __session_stop1. Documented in
  # TUTORIAL_SESSIONS.md Step 7 ("vpn-switch session show work").
  if ! session_pid=$(resolve_session_id "$session_id"); then
    echo "# ✗ Error: Named session not found: $session_id"
    return 1
  fi

  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"
  local connect_script="$session_dir/connect.sh"

  if [ ! -d "$session_dir" ]; then
    # Distinguish stale named link from a bare missing PID
    if [ "$session_id" != "$session_pid" ]; then
      echo "# ✗ Error: Stale session link $session_id: $session_pid"
      echo "# Session directory removed - run vpn-switch session clean"
    else
      echo "# ✗ Error: Session not found: $session_pid"
    fi
    return 1
  fi

  if [ ! -f "$connect_script" ]; then
    echo "# ✗ Error: Connect script not found for session: $session_pid"
    return 1
  fi

  # Session metadata
  local session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE" || echo "unknown")
  local session_interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "unknown")
  local session_original=$(cat "$session_dir/original" 2>>"$LOG_FILE" || echo "unknown")

  echo "# Session: $session_pid"
  echo "# Protocol: $session_protocol"
  echo "# Interface: $session_interface"
  echo "# Config: $(basename -- "$session_original")"
  echo '#'
  echo "# Connect script ($connect_script):"
  echo '#'

  # Display connect script contents (prefixed)
  sed 's/^/# /' "$connect_script"
}

#@help _session_remove1
# @command session remove <name>|<PID>
# @summary Remove a stopped session from the database
# @group   sessions
# @param   name|PID  session to remove (refuses if active)
# @returns shell commands (remove session directory and links)
# @example vpn-switch session remove 12345
# @see     session clean
#@end
_session_remove1() {
  local session_id="$1"
  local session_pid

  # Accept either a numeric PID or a named-session symlink, mirroring
  # __session_start1 / __session_stop1 / _session_show1.
  if ! session_pid=$(resolve_session_id "$session_id"); then
    generate_error "Named session not found: $session_id"
    return 0
  fi

  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"

  if [ ! -d "$session_dir" ]; then
    if [ "$session_id" != "$session_pid" ]; then
      generate_error "Stale session link $session_id: $session_pid" "Session directory removed - run vpn-switch session clean"
    else
      generate_error "Session not found: $session_pid"
    fi
    return 0
  fi

  # Check if VPN process still alive
  if is_session_alive "$session_dir"; then
    display warning "Session $session_pid appears to be active - process still running"
    display warning "You should stop the VPN first: vpn-switch stop"
    generate_error "Refusing to remove active session"
    return 0
  fi

  # Generate removal commands
  cat <<EOF
# Remove session directory
echo "Removing session: $session_pid"
$MODIFY_DIR_REMOVE "$session_dir"
echo "Session removed: $session_pid"
EOF
}

#@help __session_start0
# @internal arity-0 sibling of 'session start' (default session)
#@end
__session_start0() {
  local session_proto_dir="$VPN_SWITCH_BASE/session"
  local default_link="$session_proto_dir/default"

  # Check if default link exists
  if [ ! -L "$default_link" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No default session configured\" \"Use vpn-switch session save first\""
    return
  fi

  # Resolve the link to get PID
  local session_path=$(readlink "$default_link")
  local session_pid=$(basename -- "$session_path")

  # Bug #5 Fix: Check if symlink target exists
  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"
  if [ ! -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Stale session link default: $session_pid\" \"Session directory removed - run vpn-switch session clean\""
    return
  fi

  # Output combinator command to start this session
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session start \"$session_pid\""
}

#@help __session_start1
# @command session start [<name>|<PID>]
# @summary Resume a saved session by replaying its cached connect script
# @group   sessions
# @param   name|PID  saved session to resume (default: the 'default' session)
# @returns connect commands (run under the connect interpreter)
# @example vpn-switch session start work
# @see     session save
# @see     session stop
#@end
__session_start1() {
  local session_id="$1"
  local resolved_pid

  # Accept either a numeric PID or a named-session symlink.
  if ! resolved_pid=$(resolve_session_id "$session_id"); then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Named session not found: $session_id\""
    return
  fi

  # Bug #5 Fix: Check if symlink target exists
  local session_dir="$VPN_SWITCH_BASE/.session/$resolved_pid"
  if [ ! -d "$session_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Stale session link $session_id: $resolved_pid\" \"Session directory removed - run vpn-switch session clean\""
    return
  fi

  # Output combinator command to connect
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session connect \"$resolved_pid\""
}

#@help _session_connect1
# @internal connect-chain step for session resume
#@end
_session_connect1() {
  local session_pid="$1"
  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"

  # Validate session exists
  if [ ! -d "$session_dir" ]; then
    generate_error "Session directory not found: $session_dir"
    return 0
  fi

  # Check if connect.sh exists
  local connect_script="$session_dir/connect.sh"
  if [ ! -f "$connect_script" ]; then
    generate_error "Session has no cached connect script: $session_pid"
    return 0
  fi

  # Execute the cached script (directly, using exec - no fork)
  # The connect.sh has proper shebang and is executable (0700)
  # The script is self-contained with isolated environment
  cat <<EOF
# Resume session: $session_pid (via self-contained script)
exec "$connect_script"
EOF
}

#@help _session_save0
# @internal arity-0 sibling of 'session save' (saves as the default session)
#@end
_session_save0() {
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  # Validate FIRST - find most recent session using 'latest' symlink
  local latest_link="$session_proto_dir/latest"
  if [ ! -L "$latest_link" ]; then
    generate_error "No recent session found - session/latest missing"
    display plain "Start a VPN session first"
    return 0
  fi

  # Resolve latest link to get PID
  local link_target=$(readlink "$latest_link")
  local latest_pid=$(basename -- "$link_target")

  # Verify session directory exists
  if [ ! -d "$VPN_SWITCH_BASE/.session/$latest_pid" ]; then
    generate_error "Stale latest link: points to non-existent session $latest_pid"
    return 0
  fi

  # NOW output commands (validation passed)
  # Create session/ directory if it doesn't exist
  if [ ! -d "$session_proto_dir" ]; then
    cat <<EOF
$MODIFY_DIR_CREATE "$session_proto_dir"
$MODIFY_FILE_PERMS 0750 "$session_proto_dir"
EOF
  fi

  local target_path="../.session/$latest_pid"
  local link_path="$session_proto_dir/default"

  # Output commands to create the default symlink
  # NOTE: Using ln -sfn instead of ln -sf because when the existing symlink
  # points to a directory (which .session/<PID> is), POSIX ln -sf will
  # create the link INSIDE that directory instead of replacing the symlink
  cat <<EOF
# Save session as: default
echo "# Saving session $latest_pid as 'default'"
$MODIFY_LINK_FORCE "$target_path" "$link_path"
echo "# Session saved: default -> $latest_pid"
EOF
}

#@help _session_save1
# @command session save [<name>]
# @summary Save the most-recent session under a name for later resumption
# @group   sessions
# @param   name  name to save under (default: the 'default' session)
# @returns shell commands (create the named session symlink)
# @example vpn-switch session save work
# @see     session start
#@end
_session_save1() {
  local session_name="$1"
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  # Validate FIRST - reject reserved keyword 'latest' (system-managed)
  if [ "$session_name" = "latest" ]; then
    generate_error "Cannot use reserved keyword 'latest' as session name"
    return 0
  fi

  # Validate FIRST - find most recent session using 'latest' symlink
  local latest_link="$session_proto_dir/latest"
  if [ ! -L "$latest_link" ]; then
    generate_error "No recent session found - session/latest missing"
    display plain "Start a VPN session first"
    return 0
  fi

  # Resolve latest link to get PID
  local link_target=$(readlink "$latest_link")
  local latest_pid=$(basename -- "$link_target")

  # Verify session directory exists
  if [ ! -d "$VPN_SWITCH_BASE/.session/$latest_pid" ]; then
    generate_error "Stale 'latest' link: points to non-existent session $latest_pid"
    return 0
  fi

  # NOW output commands (validation passed)
  # Create session/ directory if it doesn't exist
  if [ ! -d "$session_proto_dir" ]; then
    cat <<EOF
$MODIFY_DIR_CREATE "$session_proto_dir"
$MODIFY_FILE_PERMS 0750 "$session_proto_dir"
EOF
  fi

  local target_path="../.session/$latest_pid"
  local link_path="$session_proto_dir/$session_name"

  # Output commands to create the symlink
  # NOTE: Using ln -sfn instead of ln -sf because when the existing symlink
  # points to a directory (which .session/<PID> is), POSIX ln -sf will
  # create the link INSIDE that directory instead of replacing the symlink
  cat <<EOF
# Save session as: $session_name
echo "# Saving session $latest_pid as '$session_name'"
$MODIFY_LINK_FORCE "$target_path" "$link_path"
echo "# Session saved: $session_name -> $latest_pid"
EOF
}

#@help _session_clean0
# @command session clean
# @summary Generate cleanup commands for stale/orphaned sessions
# @group   sessions
# @returns shell commands (review, then pipe to sh)
# @example vpn-switch session clean | sh
# @see     session remove
# @see     session refresh
#@end
_session_clean0() {
  local session_proto_dir="$VPN_SWITCH_BASE/session"
  local session_base="$VPN_SWITCH_BASE/.session"

  # Counters for summary (generation time)
  local stale_link_count=0
  local removed_count=0
  local kept_count=0
  local active_count=0

  echo "# Session cleanup (symlinks + stale sessions)"

  # Part 1: Scan for stale symlinks at GENERATION TIME
  if [ -d "$session_proto_dir" ]; then
    echo "#"
    echo "# Part 1: Stale symlink cleanup"

    local found_stale=0
    for link in "$session_proto_dir"/*; do
      [ ! -L "$link" ] && continue

      # Check if target exists NOW (generation time)
      if [ ! -e "$link" ]; then
        found_stale=1
        local link_name=$(basename -- "$link")
        local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "unknown")
        local target_name=$(basename -- "$target")

        echo "echo '# Removing stale link: $link_name → $target_name'"
        echo "$MODIFY_LINK_REMOVE '$link'"
        stale_link_count=$((stale_link_count + 1))
      fi
    done

    if [ "$found_stale" -eq 0 ]; then
      echo "echo '# No stale symlinks found'"
    fi
  fi

  # Part 2: Scan for stale sessions at GENERATION TIME
  if [ -d "$session_base" ]; then
    echo "#"
    echo "# Part 2: Stale session cleanup"

    # Build list of referenced PIDs NOW (generation time)
    local referenced_pids=""
    if [ -d "$session_proto_dir" ]; then
      for link in "$session_proto_dir"/*; do
        [ ! -L "$link" ] && continue
        local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "")
        if [ -n "$target" ]; then
          local target_pid=$(basename -- "$target")
          case " $referenced_pids " in
            *" $target_pid "*) ;;
            *) referenced_pids="$referenced_pids $target_pid" ;;
          esac
        fi
      done
    fi

    local found_sessions=0
    for session_dir in "$session_base"/*/; do
      [ ! -d "$session_dir" ] && continue
      found_sessions=1

      local pid=$(basename -- "$session_dir")

      # Check if session is still alive NOW (generation time)
      # Use is_session_alive() to prevent PID recycling false positives
      if is_session_alive "$session_dir"; then
        local vpn_pid=""
        if [ -f "$session_dir/vpn.pid" ]; then
          vpn_pid=$(cat "$session_dir/vpn.pid" 2>>"$LOG_FILE" || echo "")
        fi
        echo "echo '# Skipping active session: $pid (VPN process $vpn_pid running)'"
        active_count=$((active_count + 1))
        continue
      fi

      # Process is dead - check if referenced for resumption
      case " $referenced_pids " in
        *" $pid "*)
          # Dead but referenced - keep for resumption
          echo "echo '# Keeping session $pid (saved for resumption)'"
          kept_count=$((kept_count + 1))
          ;;
        *)
          # Dead and unreferenced - destroy interface and remove session
          local session_protocol=""
          local session_interface=""
          if [ -f "$session_dir/protocol" ]; then
            session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE" || echo "")
          fi
          if [ -f "$session_dir/interface" ]; then
            session_interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "")
          fi

          # Note: session clean is a DATABASE cleanup function only
          # It does NOT destroy interfaces - that's the job of 'vpn-switch stop'
          # Stale interfaces should be cleaned manually or via stop/disconnect commands

          # Output remove command
          echo "echo '# Removing stale session: $pid (process dead, unreferenced)'"
          echo "$MODIFY_DIR_REMOVE '$session_base/$pid'"
          removed_count=$((removed_count + 1))
          ;;
      esac
    done

    if [ "$found_sessions" -eq 0 ]; then
      echo "echo '# No sessions found'"
    fi
  fi

  # Summary (computed at generation time, output as concrete echo)
  echo "#"
  echo "# Summary"
  if [ "$stale_link_count" -eq 0 ] && [ "$removed_count" -eq 0 ]; then
    echo "echo '# No cleanup needed'"
  else
    [ "$stale_link_count" -gt 0 ] && echo "echo '# Removed $stale_link_count stale symlink(s)'"
    [ "$removed_count" -gt 0 ] && echo "echo '# Removed $removed_count stale session(s)'"
  fi
  echo "echo '# Session cleanup complete'"
}

# _session_refresh0 - Reconcile interface ownership against the peers actually
# loaded on the live interface.
#
# Terminal function (outputs sh commands; interpreter override 'sh'). Repairs
# the drift where session/latest-$interface points at a session whose config is
# no longer the one loaded on the interface - e.g. a resume re-pointed ownership
# but `wg-quick up` then failed because the interface was already up with a
# different config (connect.sh appends the ownership symlink unconditionally).
# The loaded WireGuard peer set is the ground truth: this finds the session whose
# stored config matches and re-points the ownership symlink to it, so
# `session list` reports the session that is genuinely live.
#
# Conservative: acts only on positive evidence. If the loaded peer set cannot be
# read (interface up but needs root, non-WireGuard, etc.) ownership is left
# untouched and reported. Operates only on symlinks in the user-owned session/
# directory, so it needs no elevated privileges. Cf. session_peer_matches_interface()
# in vpn-switch.sh, which uses the same fingerprint to demote stale sessions in
# is_session_alive().
#@help _session_refresh0
# @command session refresh
# @summary Reconcile interface ownership with the loaded peers
# @group   sessions
# @returns shell commands (re-point / remove ownership symlinks)
# @example vpn-switch session refresh
# @see     session list
# @see     session clean
#@end
_session_refresh0() {
  local session_proto_dir="$VPN_SWITCH_BASE/session"
  local session_base="$VPN_SWITCH_BASE/.session"

  echo "# Reconcile interface ownership against loaded peers"

  if [ ! -d "$session_base" ]; then
    echo "echo '# No sessions found'"
    return 0
  fi

  # Referenced PIDs (saved via named links) - used to prefer user-saved sessions
  # when several sessions share an identical config.
  local referenced_pids=""
  if [ -d "$session_proto_dir" ]; then
    for link in "$session_proto_dir"/*; do
      [ ! -L "$link" ] && continue
      case "$(basename -- "$link")" in latest|latest-*) continue ;; esac
      local ref_target=$(readlink "$link" 2>>"$LOG_FILE" || echo "")
      [ -n "$ref_target" ] && referenced_pids="$referenced_pids $(basename -- "$ref_target")"
    done
  fi

  # Discover interfaces to reconcile: union of existing latest-* ownership links
  # and the interfaces of known WireGuard sessions.
  local interfaces=""
  if [ -d "$session_proto_dir" ]; then
    for link in "$session_proto_dir"/latest-*; do
      [ ! -L "$link" ] && continue
      local iname=$(basename -- "$link"); iname="${iname#latest-}"
      case " $interfaces " in *" $iname "*) ;; *) interfaces="$interfaces $iname" ;; esac
    done
  fi
  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue
    [ "$(cat "$session_dir/protocol" 2>>"$LOG_FILE" || echo "")" = "wireguard" ] || continue
    local si=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "")
    [ -n "$si" ] || continue
    case " $interfaces " in *" $si "*) ;; *) interfaces="$interfaces $si" ;; esac
  done

  if [ -z "$interfaces" ]; then
    echo "echo '# No interfaces to reconcile'"
    return 0
  fi

  local changed=0
  for iface in $interfaces; do
    echo "#"
    echo "# Interface: $iface"

    local link="$session_proto_dir/latest-$iface"
    local current=""
    [ -L "$link" ] && current=$(basename -- "$(readlink "$link" 2>>"$LOG_FILE")")

    # Ground truth: peers loaded on the live interface (read-only, no root needed
    # on supported platforms).
    local loaded=""
    loaded=$($EXAMINE_VPN_WIREGUARD_INTERFACE "$iface" 2>>"$LOG_FILE" \
      | grep '^peer:' \
      | sed 's/^peer:[[:space:]]*//' \
      | sort)

    if [ -z "$loaded" ]; then
      # Distinguish "interface down" (positive evidence -> stale link) from
      # "up but unreadable" (no judgement).
      if $EXAMINE_NETWORK_INTERFACE_EXISTS "$iface" >/dev/null 2>&1; then
        echo "echo '# $iface: peers unreadable (needs root?) - ownership left unchanged'"
      elif [ -n "$current" ]; then
        echo "echo '# $iface: interface down - removing stale ownership ($current)'"
        echo "$MODIFY_LINK_REMOVE '$link'"
        changed=$((changed + 1))
      else
        echo "echo '# $iface: interface down, no ownership link'"
      fi
      continue
    fi

    # Find sessions whose stored config matches the loaded peer set. Collect as
    # "ref<TAB>started<TAB>pid" so a single sort picks the rightful owner:
    # referenced sessions first, then the most-recently started.
    local candidates=""
    for session_dir in "$session_base"/*/; do
      [ ! -d "$session_dir" ] && continue
      local pid=$(basename -- "$session_dir")
      [ "$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "")" = "$iface" ] || continue
      local conf="$session_dir/$iface.conf"
      [ -f "$conf" ] || continue
      local stored=$(grep -i '^[[:space:]]*PublicKey' "$conf" 2>>"$LOG_FILE" \
        | sed 's/^[[:space:]]*[Pp]ublic[Kk]ey[[:space:]]*=[[:space:]]*//' \
        | sort)
      [ "$stored" = "$loaded" ] || continue

      local started=$(cat "$session_dir/started" 2>>"$LOG_FILE" || echo "")
      local ref=0
      case " $referenced_pids " in *" $pid "*) ref=1 ;; esac
      candidates="${candidates}${ref}	${started}	${pid}
"
    done

    local best=""
    if [ -n "$candidates" ]; then
      best=$(printf '%s' "$candidates" | grep -v '^$' | sort | tail -1 | cut -f3)
    fi

    if [ -z "$best" ]; then
      echo "echo '# $iface: loaded config matches no known session (external/unknown) - left unchanged'"
    elif [ "$current" = "$best" ]; then
      echo "echo '# $iface: ownership already correct ($best)'"
    else
      echo "echo '# $iface: re-pointing ownership ${current:-none} -> $best'"
      echo "$MODIFY_LINK_FORCE '../.session/$best' '$link'"
      changed=$((changed + 1))
    fi
  done

  echo "#"
  echo "# Summary"
  if [ "$changed" -eq 0 ]; then
    echo "echo '# Ownership already consistent - no changes'"
  else
    echo "echo '# Reconciled ownership for $changed interface(s)'"
  fi
  echo "echo '# Session refresh complete'"
}

#@help _session_validate0
# @internal session bookkeeping validation (sub-check of 'validate')
#@end
_session_validate0() {
  local session_proto_dir="$VPN_SWITCH_BASE/session"
  local session_base="$VPN_SWITCH_BASE/.session"
  local has_errors=0
  local has_warnings=0

  echo "# === Session Validation ==="
  echo "#"

  # Part 1: Check for stale symlinks in session/
  echo "# Checking session symlinks..."
  if [ -d "$session_proto_dir" ]; then
    for link in "$session_proto_dir"/*; do
      [ ! -L "$link" ] && continue

      if [ ! -e "$link" ]; then
        local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "unknown")
        echo "# [ERROR] Stale symlink: session/$(basename -- "$link") → $(basename -- "$target")"
        has_errors=1
      fi
    done
  else
    echo "# [WARNING] Session directory not found: $session_proto_dir"
    has_warnings=1
  fi

  # Part 2: Check for unreferenced session directories
  echo "#"
  echo "# Checking session directories..."
  if [ -d "$session_base" ]; then
    # Build list of referenced PIDs
    local referenced_pids=""
    if [ -d "$session_proto_dir" ]; then
      for link in "$session_proto_dir"/*; do
        [ ! -L "$link" ] && continue
        local target=$(readlink "$link" 2>>"$LOG_FILE" || echo "")
        if [ -n "$target" ]; then
          local target_pid=$(basename -- "$target")
          case " $referenced_pids " in
            *" $target_pid "*) ;;
            *) referenced_pids="$referenced_pids $target_pid" ;;
          esac
        fi
      done
    fi

    # Check each session directory
    for session_dir in "$session_base"/*/; do
      [ ! -d "$session_dir" ] && continue
      local pid=$(basename -- "$session_dir")

      # Check if unreferenced
      case " $referenced_pids " in
        *" $pid "*)
          # Referenced - check metadata integrity
          local protocol_file="$session_dir/protocol"
          local original_file="$session_dir/original"
          local interface_file="$session_dir/interface"

          if [ ! -f "$protocol_file" ]; then
            echo "# [ERROR] Missing protocol metadata: .session/$pid/protocol"
            has_errors=1
          fi

          if [ ! -f "$original_file" ]; then
            echo "# [ERROR] Missing original config metadata: .session/$pid/original"
            has_errors=1
          fi

          if [ ! -f "$interface_file" ]; then
            echo "# [WARNING] Missing interface metadata: .session/$pid/interface"
            has_warnings=1
          fi
          ;;
        *)
          # Unreferenced session
          echo "# [WARNING] Unreferenced session: .session/$pid (no links point to it)"
          has_warnings=1
          ;;
      esac
    done
  fi

  # Summary
  echo "#"
  if [ "$has_errors" -eq 0 ] && [ "$has_warnings" -eq 0 ]; then
    echo "# ✓ Session validation passed - no issues found"
    return 0
  elif [ "$has_errors" -eq 0 ]; then
    echo "# ⚠ Session validation completed with warnings"
    echo "# Run 'vpn-switch session clean' to remove unreferenced sessions"
    return 0
  else
    echo "# ✗ Session validation failed - errors found"
    echo "# Run 'vpn-switch session clean' to fix stale symlinks and remove unreferenced sessions"
    return 1
  fi
}

#@help ___session_dump0
# @internal session portion of 'dump'
#@end
___session_dump0() {
  local session_pseudo="$VPN_SWITCH_BASE/session"

  # Check if session directory exists
  if [ ! -d "$session_pseudo" ]; then
    # No sessions to dump - return empty (valid for set-combinator)
    return 0
  fi

  echo "# Dump named sessions"

  # Iterate over all symlinks in session/ directory
  for session_link in "$session_pseudo"/*; do
    # Skip if no links found
    [ ! -L "$session_link" ] && continue

    local session_name=$(basename -- "$session_link")

    # Skip 'latest' symlink (transient system state, recreated on next start)
    [ "$session_name" = "latest" ] && continue

    # Resolve symlink to get actual session directory
    local session_dir=$(readlink -f "$session_link" 2>>"$LOG_FILE")
    [ ! -d "$session_dir" ] && continue

    # Read session metadata
    local protocol_file="$session_dir/protocol"
    [ ! -f "$protocol_file" ] && continue

    local original_file="$session_dir/original"
    [ ! -f "$original_file" ] && continue

    local protocol=$(cat "$protocol_file" 2>>"$LOG_FILE")
    local original_config=$(cat "$original_file" 2>>"$LOG_FILE")

    # Validate we have the required metadata
    [ -z "$protocol" ] && continue
    [ -z "$original_config" ] && continue

    # Read interface from session metadata
    local interface_file="$session_dir/interface"
    [ ! -f "$interface_file" ] && continue
    local interface=$(cat "$interface_file" 2>>"$LOG_FILE")
    [ -z "$interface" ] && continue

    # Output feingranular commands to recreate session structure
    # This avoids calling 'connect' which would try to start the VPN
    # Uses a unique PID placeholder that will be replaced at restore time
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session create \"\$\$\""
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session populate \"\$\$\" \"$protocol\" \"$interface\""
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $protocol patch \"\$\$\" \"$original_config\""
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" $protocol configure \"\$\$\""
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session save $session_name"
  done
}

#@help __session_help0
# @command session help
# @summary Show session-management command help
# @group   sessions
# @returns help text
# @example vpn-switch session help
#@end
__session_help0() {
  # Backward compatibility: delegate to new pattern "help session"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" help session"
}

#@help ___session_inspect0
# @internal session portion of 'inspect'
#@end
___session_inspect0() {
  # Save current ANSI setting (at generation time)
  ansi_original="${VPN_SWITCH_DISPLAY_ANSI}"

  # Disable ANSI if currently enabled (suppress stderr)
  if [ "${VPN_SWITCH_DISPLAY_ANSI}" != "0" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" setenv VPN_SWITCH_DISPLAY_ANSI 0 2>/dev/null"
  fi

  # Output section header (consistent with other inspect functions)
  cat <<'EOF'
# Section: Session Status
EOF

  # Batch combinator - delegates to three vpn-switch commands
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session list"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session enumerate"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" session describe"

  # Restore ANSI to original value if we changed it (suppress stderr)
  if [ "${ansi_original}" != "0" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" setenv VPN_SWITCH_DISPLAY_ANSI ${ansi_original} 2>/dev/null"
  fi

  # Re-enable cache if it was enabled (suppress stderr)
  if [ -n "${VPN_SWITCH_INTERPRETER_environment_cache}" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" environment cache on 2>/dev/null"
  fi
}

#@help _session_enumerate0
# @internal session enumeration helper
#@end
_session_enumerate0() {
  # Terminal function - enumerate named sessions (internal, used by inspect)
  # Generation-time pattern: discover now, output only concrete echo commands
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  echo "# Named Sessions"
  echo "#"

  if [ ! -d "$session_proto_dir" ]; then
    echo "# (no session directory)"
    return 0
  fi

  local found=0
  for link in "$session_proto_dir"/*; do
    [ -L "$link" ] || continue
    found=1

    local name=$(basename -- "$link")
    local target=$($EXAMINE_LINK_TARGET "$link" 2>>"$LOG_FILE" || echo "unknown")

    echo "# $name → $target"
  done

  if [ "$found" -eq 0 ]; then
    echo "# (no named sessions)"
  fi
}

#@help _session_describe0
# @internal session description helper
#@end
_session_describe0() {
  # Terminal function - describe session scripts (internal, used by inspect)
  # Generation-time pattern: discover now, output only concrete comments
  local session_base="$VPN_SWITCH_BASE/.session"

  echo "# Session Scripts"
  echo "#"

  if [ ! -d "$session_base" ]; then
    echo "# (no session directory)"
    return 0
  fi

  local found=0
  for session_dir in "$session_base"/*/; do
    [ -d "$session_dir" ] || continue
    found=1

    local pid=$(basename -- "$session_dir")
    local protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE" || echo "unknown")
    local interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE" || echo "unknown")

    echo "#"
    echo "# Session $pid ($protocol / $interface):"
    echo "#   Connect: $session_dir/connect.sh"
    echo "#   Disconnect: $session_dir/disconnect.sh"

    if [ -f "$session_dir/connect.sh" ]; then
      local connect_lines=$(wc -l < "$session_dir/connect.sh" 2>>"$LOG_FILE" || echo "?")
      echo "#   Connect size: $connect_lines lines"
    fi

    if [ -f "$session_dir/disconnect.sh" ]; then
      local disconnect_lines=$(wc -l < "$session_dir/disconnect.sh" 2>>"$LOG_FILE" || echo "?")
      echo "#   Disconnect size: $disconnect_lines lines"
    fi
  done

  if [ "$found" -eq 0 ]; then
    echo "# (no sessions)"
  fi
}

# Note: is_session_alive() is defined in vpn-switch.sh (not here) because
# it's needed by batch combinators (___wireguard_stop0, ___openvpn_stop0)
# which run before modules are loaded.

