# wireguard.sh - Dynamically loaded wireguard module
# Generated by extract-modules-v2.sh
# DO NOT EDIT - This file is auto-generated

#@help __wireguard_start0
# @internal arity-0 sibling of 'wireguard start'
#@end
__wireguard_start0() {
  local protocol_dir="$VPN_SWITCH_BASE/wireguard"

  # Use resolve_default_or_random to pick config
  # Pattern: "*.conf" to match WireGuard configs
  local config
  config=$(resolve_default_or_random "$protocol_dir" "*.conf")

  # Check if any configs were found
  if [ -z "$config" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No WireGuard configs found in wireguard/\""
    return
  fi

  # Delegate to start1 with selected config
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard start $config"
}

#@help __wireguard_start1
# @command wireguard start [<category>]
# @summary Start a WireGuard tunnel; with no argument, use the default or a random config
# @group   wireguard
# @param   category  config category, config name or alias; omit for the default-or-random config
# @returns connect commands (run under the connect interpreter)
# @example vpn-switch wireguard start privacy
# @example vpn-switch wireguard start
# @see     wireguard stop
# @see     session save
#@end
__wireguard_start1() {
  local object="$1"
  local protocol_dir="$VPN_SWITCH_BASE/wireguard"
  local object_path="$protocol_dir/$object"
  local config=""
  local config_path=""

  # Case 1: Directory (category) - pick a config from it
  if [ -d "$object_path" ]; then
    local category="$object"
    local category_dir="$object_path"

    # Resolve config file from category
    # Note: Use pattern "*" because category directories contain symlinks WITHOUT extensions
    # The symlinks point to actual .conf files in the parent protocol directory
    config=$(resolve_default_or_random "$category_dir" "*")

    # Check if category is empty
    if [ -z "$config" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Category '$category' is empty (no configs found)\""
      return
    fi

    # Follow symlinks to get actual config file (with loop detection)
    if ! config=$(follow_symlinks_safe "$category_dir" "$config"); then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Symlink loop detected: $config\""
      return
    fi

    # Resolve to full path
    config_path="$protocol_dir/$config"

    # Validate config file exists
    if [ ! -f "$config_path" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Config file not found: $config_path\""
      return
    fi

  # Case 2: File or symlink - use directly
  elif [ -f "$object_path" ] || [ -L "$object_path" ]; then
    config="$object"

    # Follow symlinks if needed (with loop detection)
    if ! config=$(follow_symlinks_safe "$protocol_dir" "$config"); then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Symlink loop detected: $config\""
      return
    fi

    # Resolve to full path
    config_path="$protocol_dir/$config"

    # Validate config file exists after following symlinks
    if [ ! -f "$config_path" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Config file not found: $config_path \\(after following symlinks\\)\""
      return
    fi

  # Case 3: Try with extension if exact match failed
  elif [ -f "$object_path.conf" ] || [ -L "$object_path.conf" ]; then
    config="$object.conf"

    # Follow symlinks if needed (with loop detection)
    if ! config=$(follow_symlinks_safe "$protocol_dir" "$config"); then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Symlink loop detected: $config\""
      return
    fi

    # Resolve to full path
    config_path="$protocol_dir/$config"

    # Validate config file exists after following symlinks
    if [ ! -f "$config_path" ]; then
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Config file not found: $config_path \\(after following symlinks\\)\""
      return
    fi

  else
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Not found in wireguard/: $object \\(must be a category, config file, or symlink\\)\""
    return
  fi

  # Delegate to create (resolved config visible via command inspection)
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard create \"$config\""
}

#@help ___wireguard_create1
# @internal session-create chain step for 'wireguard start'
#@end
___wireguard_create1() {
  local config="$1"
  local config_path="$VPN_SWITCH_BASE/wireguard/$config"

  # Check and create minimal session (PID only)
  check_and_create_session "$VPN_SWITCH_INTERFACE_wireguard" || return

  local session_pid="$$"

  # Output batch with comment + commands (KEEP_GOING=0)
  cat <<EOF
# Created session $session_pid
"\$VPN_SWITCH_CONTEXT_SCRIPT" session populate "$session_pid" "wireguard" "$VPN_SWITCH_INTERFACE_wireguard"
"\$VPN_SWITCH_CONTEXT_SCRIPT" wireguard patch "$session_pid" "$config_path"
"\$VPN_SWITCH_CONTEXT_SCRIPT" wireguard configure "$session_pid"
"\$VPN_SWITCH_CONTEXT_SCRIPT" wireguard connect "$session_pid"
EOF
}

#@help _wireguard_patch2
# @internal session-scoped patch variant (used during connect)
#@end
_wireguard_patch2() {
  local session_pid="$1"
  local config_path="$2"
  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"
  local patched_config="$session_dir/${VPN_SWITCH_INTERFACE_wireguard}.conf"

  # Output shell commands (terminal function - normal form)
  cat <<EOF
# Record original config
echo "$config_path" > "$session_dir/original"
$MODIFY_FILE_PERMS 0640 "$session_dir/original"

# Copy and patch config
$MODIFY_FILE_COPY "$config_path" "$patched_config"
$MODIFY_FILE_PERMS 0640 "$patched_config"

# Remove existing DNS hooks (DNS handled by DNS phase)
$MODIFY_FILE_SED_INPLACE '/^PostUp.*resolvconf/d' "$patched_config"
$MODIFY_FILE_SED_INPLACE '/^PostDown.*resolvconf/d' "$patched_config"

# Set read-only permissions
$MODIFY_FILE_PERMS 0640 "$patched_config"
EOF
}

#@help _wireguard_configure1
# @internal configure chain step (generates connect/disconnect scripts)
#@end
_wireguard_configure1() {
  local session_pid="$1"
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  # Output shell commands (terminal function - normal form)
  cat <<EOF
# Create session protocol directory
$MODIFY_DIR_CREATE "$session_proto_dir"
$MODIFY_FILE_PERMS 0750 "$session_proto_dir"

# Update latest session link (use -n to prevent dereferencing)
$MODIFY_LINK_FORCE "../.session/$session_pid" "$session_proto_dir/latest"
EOF
}

#@help _wireguard_connect1
# @internal connect chain step (emits the connect commands)
#@end
_wireguard_connect1() {
  local session_id="$1"
  local session_dir="$VPN_SWITCH_BASE/.session/$session_id"
  local interface="${VPN_SWITCH_INTERFACE_wireguard}"
  local patched_config="$session_dir/${interface}.conf"
  local connect_script="$session_dir/connect.sh"
  local disconnect_script="$session_dir/disconnect.sh"
  local session_proto_dir="$VPN_SWITCH_BASE/session"

  # Validate session exists
  if [ ! -d "$session_dir" ]; then
    generate_error "Session not found: $session_id"
    return 0
  fi

  # Validate patched config exists
  if [ ! -f "$patched_config" ]; then
    generate_error "Patched config not found in session $session_id: $patched_config"
    return 0
  fi

  # Read original config path from session metadata
  local original_config=$(cat "$session_dir/original" 2>>"$LOG_FILE" || echo "unknown")

  # Compute relative path from session directory to original config
  # Session is at: $VPN_SWITCH_BASE/.session/$session_id/
  # Original is at: $VPN_SWITCH_BASE/wireguard/... or $VPN_SWITCH_BASE/wireguard/category/...
  # Relative path: ../../wireguard/... or ../../wireguard/category/...
  local original_config_relative="${original_config#$VPN_SWITCH_BASE/}"
  original_config_relative="../../$original_config_relative"

  # NOTE: Duplicate session check moved to __wireguard_start1 (before session creation)
  # This prevents PID mismatch issues in the combinator chain

  # Extract DNS server for firewall table (from patched config)
  local dns_server=$(grep '^DNS' "$patched_config" | head -1 | awk -F= '{print $2}')
  dns_server="${dns_server:-${VPN_SWITCH_DNS_wireguard:-10.2.0.1}}"  # VPN provider WireGuard uses 10.2.0.1

  # Extract remote server IPs for firewall table (from patched config)
  local remote_ips=$(get_wireguard_remotes "$patched_config")

  # Get phase lists
  local phases_connect="${VPN_SWITCH_PHASES_CONNECT:-firewall vpn dns}"
  local phases_disconnect="${VPN_SWITCH_PHASES_DISCONNECT:-dns vpn firewall}"

  # Phase script directory
  local phase_dir="$VPN_SWITCH_BASE/.include/phase/wireguard"

  # Strict phase resolution (least surprise): every phase in the list MUST
  # resolve to a script. A phase that does not resolve is a configuration error
  # and aborts generation — it is never silently dropped (which previously could
  # remove e.g. the firewall phase on a typo or a missing @profile). To skip a
  # phase on purpose, use the ':none' backend. Supports :variant@profile syntax.
  local protocol=$(basename -- "$phase_dir")  # Extract protocol from phase_dir
  for phase_spec in $phases_connect; do
    if ! resolve_phase_script "$phase_spec" "$protocol" "connect" "$VPN_SWITCH_BASE" >/dev/null 2>&1; then
      generate_error "Phase '$phase_spec' (connect) does not resolve" "Fix VPN_SWITCH_PHASES_CONNECT or add the backend; use ':none' to skip a phase"
      return 0
    fi
  done
  for phase_spec in $phases_disconnect; do
    if ! resolve_phase_script "$phase_spec" "$protocol" "disconnect" "$VPN_SWITCH_BASE" >/dev/null 2>&1; then
      generate_error "Phase '$phase_spec' (disconnect) does not resolve" "Fix VPN_SWITCH_PHASES_DISCONNECT or add the backend; use ':none' to skip a phase"
      return 0
    fi
  done

  # Build VPN_SWITCH_CONTEXT_CONNECT (new context variable system)
  # Gateway for WireGuard is the DNS server
  local gateway="$dns_server"
  VPN_SWITCH_CONTEXT_CONNECT="
export VPN_SESSION_DIR=\"$session_dir\"
export VPN_SESSION_PID=\"$session_id\"
export VPN_CONFIG_FILE=\"$patched_config\"
export VPN_ORIGINAL_CONFIG=\"$original_config\"
export VPN_ORIGINAL_CONFIG_RELATIVE=\"$original_config_relative\"
export VPN_INTERFACE=\"$VPN_SWITCH_INTERFACE_wireguard\"
export VPN_DNS_SERVER=\"$dns_server\"
export VPN_REMOTE_IPS=\"$remote_ips\"
export VPN_GATEWAY=\"$gateway\"
export VPN_PROTOCOL=\"wireguard\"
export VPN_PHASES_CONNECT=\"$phases_connect\"
export VPN_PHASES_DISCONNECT=\"$phases_disconnect\"
"
  export VPN_SWITCH_CONTEXT_CONNECT

  # Generate connect.sh using phase-based approach
  {
    # Generate prologue
    if [ -f "$phase_dir/connect/prologue.sh" ]; then
      run_env -- sh "$phase_dir/connect/prologue.sh"
    else
      generate_error "Prologue not found: $phase_dir/connect/prologue.sh"
      return 0
    fi

    # Generate phases (verify → prepare → execute for each phase)
    for phase_spec in $phases_connect; do
      local phase_script=$(resolve_phase_script "$phase_spec" "$protocol" "connect" "$VPN_SWITCH_BASE")
      if [ -n "$phase_script" ] && [ -f "$phase_script" ]; then
        run_env -- sh "$phase_script" verify
        run_env -- sh "$phase_script" prepare
        run_env -- sh "$phase_script" execute
      fi
      # Pre-flight above guarantees every phase resolves (missing => error, not skip)
    done
  } > "$connect_script"

  $MODIFY_FILE_PERMS 0750 "$connect_script"

  # Claim interface ownership only when this session's config is actually the one
  # loaded on the interface. A self-validating claim keeps session/latest-$interface
  # from drifting: previously this symlink was set unconditionally at the end of
  # connect.sh, so a resume whose `wg-quick up` failed (e.g. the interface was
  # already up with a different config) would still claim ownership of someone
  # else's tunnel. We compare the live peer set against this session's config and
  # only claim on a match. Cf. session_peer_matches_interface() in vpn-switch.sh
  # (same fingerprint, used by is_session_alive) and 'vpn-switch session refresh'
  # (reconciles drift after the fact).
  {
    echo ""
    echo "# Claim interface ownership (only if our config is the one loaded)"
    cat <<EOF
__vpn_loaded=\$($EXAMINE_VPN_WIREGUARD_INTERFACE "\$interface" 2>/dev/null | grep '^peer:' | sed 's/^peer:[[:space:]]*//' | sort)
__vpn_ours=\$(grep -i '^[[:space:]]*PublicKey' "\$config_path" 2>/dev/null | sed 's/^[[:space:]]*[Pp]ublic[Kk]ey[[:space:]]*=[[:space:]]*//' | sort)
if [ -n "\$__vpn_loaded" ] && [ "\$__vpn_loaded" = "\$__vpn_ours" ]; then
  $MODIFY_LINK_FORCE "../.session/$session_id" "$session_proto_dir/latest-$interface"
  echo "# Interface ownership claimed: $interface -> session $session_id" >&2
else
  echo "WARNING: $interface not loaded with this session's config - ownership not claimed" >&2
  echo "WARNING: if the VPN is up, run 'vpn-switch session refresh' to reconcile" >&2
fi
EOF
  } >> "$connect_script"

  # Generate disconnect.sh using phase-based approach
  {
    # Generate prologue
    if [ -f "$phase_dir/disconnect/prologue.sh" ]; then
      run_env -- sh "$phase_dir/disconnect/prologue.sh"
    else
      generate_error "Prologue not found: $phase_dir/disconnect/prologue.sh"
      return 0
    fi

    # Generate phases (verify → prepare → execute for each phase)
    for phase_spec in $phases_disconnect; do
      local phase_script=$(resolve_phase_script "$phase_spec" "$protocol" "disconnect" "$VPN_SWITCH_BASE")
      if [ -n "$phase_script" ] && [ -f "$phase_script" ]; then
        run_env -- sh "$phase_script" verify
        run_env -- sh "$phase_script" prepare
        run_env -- sh "$phase_script" execute
      fi
      # Pre-flight above guarantees every phase resolves (missing => error, not skip)
    done
  } > "$disconnect_script"

  # Release interface ownership: drop latest-$interface if it still points to
  # this session, so a stopped session never keeps claiming the interface (this
  # is the other half of preventing ownership drift; previously disconnect left
  # the symlink behind).
  {
    echo ""
    echo "# Release interface ownership (only if still ours)"
    cat <<EOF
if [ -L "$session_proto_dir/latest-$interface" ] && [ "\$($EXAMINE_LINK_TARGET "$session_proto_dir/latest-$interface" 2>/dev/null)" = "../.session/$session_id" ]; then
  $MODIFY_LINK_REMOVE "$session_proto_dir/latest-$interface"
  echo "# Interface ownership released: $interface (was session $session_id)" >&2
fi
EOF
  } >> "$disconnect_script"

  $MODIFY_FILE_PERMS 0750 "$disconnect_script"

  # Output connect script for immediate execution
  cat "$connect_script"
}

#@help _wireguard_disconnect1
# @internal disconnect chain step (emits the disconnect commands)
#@end
_wireguard_disconnect1() {
  local interface="$1"

  # Find session by interface name
  local session_pid=$(find_session_by_interface "$interface")

  if [ -z "$session_pid" ]; then
    generate_error "No vpn-switch session found for interface: $interface"
    return 0
  fi

  local session_dir="$VPN_SWITCH_BASE/.session/$session_pid"
  local disconnect_script="$session_dir/disconnect.sh"

  # Build VPN_SWITCH_CONTEXT_DISCONNECT (new context variable system)
  VPN_SWITCH_CONTEXT_DISCONNECT="
export VPN_SESSION_DIR='$session_dir'
export VPN_SESSION_PID='$session_pid'
export VPN_INTERFACE='$interface'
export VPN_PROTOCOL='wireguard'
"
  export VPN_SWITCH_CONTEXT_DISCONNECT

  # If disconnect.sh exists (phase-based sessions), use it
  if [ -f "$disconnect_script" ]; then
    cat "$disconnect_script"
  else
    # Legacy fallback for old sessions created before phase-based implementation
    local original_config=$(cat "$session_dir/original" 2>>"$LOG_FILE" || echo "unknown")
    local original_config_relative="${original_config#$VPN_SWITCH_BASE/}"
    original_config_relative="../../$original_config_relative"

    local wg_quick="$VPN_SWITCH_BINARY_wireguard"
    local pfctl="${VPN_SWITCH_PFCTL:-pfctl}"
    local vpn_dns_table="${VPN_SWITCH_VPN_DNS_TABLE:-vpn_dns}"
    local vpn_remotes_table="${VPN_SWITCH_VPN_REMOTES_TABLE:-vpn_remotes}"

    # Generate legacy cleanup commands
    cat <<EOF
# Disconnect WireGuard interface: $interface (legacy mode - no disconnect.sh found)
# Session PID: $session_pid
# Original config: $original_config_relative

# Kill wg-quick process group (including background route monitors)
if [ -f "$session_dir/wg_quick_pid" ]; then
  wg_quick_pid=\$(cat "$session_dir/wg_quick_pid" 2>>"$LOG_FILE")
  if [ -n "\$wg_quick_pid" ]; then
    echo "Killing wg-quick process group (PID: \$wg_quick_pid)..."
    kill -TERM -- -\$wg_quick_pid 2>>"$LOG_FILE" || true
    sleep 1
  fi
fi

# Stop WireGuard interface
echo "Stopping WireGuard interface: $interface"
$wg_quick down "$interface" 2>>"$LOG_FILE" || true

# Clean up firewall tables
echo "Cleaning up firewall tables..."
$pfctl -t "$vpn_dns_table" -T flush 2>>"$LOG_FILE" || true
$pfctl -t "$vpn_remotes_table" -T flush 2>>"$LOG_FILE" || true

echo "VPN disconnected: $interface"
echo "Note: Session metadata will be cleaned up by 'session stop'"
EOF
  fi
}

#@help ___wireguard_inspect0
# @internal WireGuard portion of 'inspect'
#@end
___wireguard_inspect0() {
  # Batch combinator - compose multiple inspection commands
  # Note: wireguard_list, validate0, and enumerate0 have templates with appropriate interpreters

  echo "# WireGuard Inspection Report"
  echo ""
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard list 2>>\"\$LOG_FILE\""
  echo ""
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard validate 2>>\"\$LOG_FILE\""
  echo ""
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard enumerate 2>>\"\$LOG_FILE\""
}

#@help _wireguard_enumerate0
# @internal WireGuard enumeration helper
#@end
_wireguard_enumerate0() {
  # Process Table Analysis - enumerate running WireGuard processes
  # Generates shell code that examines process table at execution time

  cat <<EOF
ps_output=\$(ps auxww 2>>"$LOG_FILE" | grep '[w]g-quick' || true)

if [ -z "\$ps_output" ]; then
  echo "# No wg-quick processes found"
  exit 0
fi

echo "\$ps_output" | while IFS= read -r line; do
  pid=\$(echo "\$line" | awk '{print \$2}')
  cmd=\$(echo "\$line" | awk '{for(i=11;i<=NF;i++) printf \$i " "; print ""}')
  config=\$(echo "\$cmd" | sed -n 's/.*wg-quick[[:space:]]*up[[:space:]]*\([^[:space:]]*\).*/\1/p')

  if echo "\$config" | grep -q "^$VPN_SWITCH_BASE/.session/"; then
    session_id=\$(echo "\$config" | sed "s|^$VPN_SWITCH_BASE/.session/\([^/]*\)/.*|\1|")
    interface=\$(basename "\$config" .conf 2>>"$LOG_FILE" || echo 'unknown')
    echo "#"
    echo "# ✓ wg-quick (PID \$pid) [managed by this instance]"
    echo "#   Config: \$config"
    echo "#   Session: \$session_id"
    echo "#   Interface: \$interface"
  elif echo "\$config" | grep -q '/.session/'; then
    other_base=\$(echo "\$config" | sed 's|\(.*\)/.session/.*|\1|')
    interface=\$(basename "\$config" .conf 2>>"$LOG_FILE" || echo 'unknown')
    echo "#"
    echo "# ⚠ wg-quick (PID \$pid) [different vpn-switch instance]"
    echo "#   Config: \$config"
    echo "#   Instance: \$other_base"
    echo "#   Interface: \$interface"
  else
    interface=\$(basename "\$config" .conf 2>>"$LOG_FILE" || echo 'unknown')
    echo "#"
    echo "# ⚠ wg-quick (PID \$pid) [NOT managed by vpn-switch]"
    echo "#   Config: \$config"
    echo "#   Interface: \$interface"
    for session_dir in "$VPN_SWITCH_BASE/.session"/*; do
      [ -d "\$session_dir" ] || continue
      our_interface=\$(cat "\$session_dir/interface" 2>>"$LOG_FILE" || true)
      if [ "\$our_interface" = "\$interface" ]; then
        our_session=\$(basename "\$session_dir")
        echo "#   ⚠ WARNING: Interface conflict with our session \$our_session!"
      fi
    done
  fi
done
EOF
}

#@help ___wireguard_stop0
# @internal batch sibling of 'wireguard stop' (stops all WireGuard sessions)
#@end
___wireguard_stop0() {
  local session_base="$VPN_SWITCH_BASE/.session"

  if [ ! -d "$session_base" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"No WireGuard sessions to stop\""
    return 0
  fi

  # Find all wireguard sessions
  local found_session=0
  for session_dir in "$session_base"/*/; do
    [ ! -d "$session_dir" ] && continue

    local session_protocol=$(cat "$session_dir/protocol" 2>>"$LOG_FILE")

    # Skip non-wireguard sessions
    [ "$session_protocol" != "wireguard" ] && continue

    # Skip inactive sessions (not running)
    is_session_alive "$session_dir" || continue

    local session_interface=$(cat "$session_dir/interface" 2>>"$LOG_FILE")

    # Legacy: infer interface if missing
    if [ -z "$session_interface" ]; then
      session_interface="$VPN_SWITCH_INTERFACE_wireguard"
    fi

    # Script path uses literal variable reference for portability
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard disconnect $session_interface"
    found_session=1
  done

  # If no WireGuard sessions were found, output log message
  if [ "$found_session" -eq 0 ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" log \"No WireGuard sessions to stop\""
  fi
}

#@help __wireguard_stop1
# @command wireguard stop [<interface>]
# @summary Stop WireGuard sessions, or one specific interface
# @group   wireguard
# @param   interface  interface to stop (default: all WireGuard sessions)
# @returns disconnect commands
# @example vpn-switch wireguard stop
# @see     wireguard start
#@end
__wireguard_stop1() {
  local interface="$1"

  # Validate session exists
  local session_pid=$(find_session_by_interface "$interface")

  if [ -z "$session_pid" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"No wireguard session found for interface: $interface\""
    return
  fi

  # Output disconnect command
  # Script path uses literal variable reference for portability
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard disconnect $interface"
}

#@help _wireguard_import1
# @command wireguard import <file>
# @summary Import a WireGuard .conf file into the database
# @group   wireguard
# @param   file  path to a .conf file to import
# @returns shell commands (copy config into the database)
# @example vpn-switch wireguard import ~/Downloads/wg-CH-201.conf
# @see     wireguard list
#@end
_wireguard_import1() {
  local source_path="$1"

  # Validate file exists
  if [ ! -f "$source_path" ]; then
    generate_error "Config file not found: $source_path"
    return 0
  fi

  # Extract filename
  local filename=$(basename -- "$source_path")

  # Validate extension
  case "$filename" in
    *.conf) ;;
    *)
      generate_error "Invalid config file extension - expected .conf: $filename"
      return 0
      ;;
  esac

  # Check if config already exists in protocol directory
  local dest_path="$VPN_SWITCH_BASE/wireguard/$filename"
  if [ -f "$dest_path" ]; then
    generate_error "Config already exists: wireguard/$filename"
    return 0
  fi

  # Output import commands
  cat <<EOF
# Import WireGuard config: $filename
$MODIFY_FILE_COPY "$source_path" "$dest_path"
$MODIFY_FILE_PERMS 0400 "$dest_path"
echo "# Imported: wireguard/$filename" >&2
EOF
}

#@help _wireguard_list0
# @command wireguard list [<category>]
# @summary List WireGuard configs and categories
# @group   wireguard
# @param   category  restrict the listing to one category
# @returns config / category listing
# @example vpn-switch wireguard list
#@end
_wireguard_list0() {
  local wg_dir="$VPN_SWITCH_BASE/wireguard"

  # Check if directory exists (follows symlinks for the directory itself)
  if [ ! -d "$wg_dir" ]; then
    generate_error "WireGuard directory not found: $wg_dir"
    return 0
  fi

  # Output listing with hierarchy prefixes and comment headers
  echo "# === WireGuard Configurations ==="
  echo "#"
  echo "# Configuration files:"
  scan_wireguard_configs

  # Check if there are protocol-level links (aliases) to show
  local links=$(scan_wireguard_links)
  if [ -n "$links" ]; then
    echo "#"
    echo "# Protocol-level links:"
    echo "$links"
  fi

  echo "#"
  echo "# Categories: (use 'wireguard list <category>' to see contents)"
  scan_wireguard_categories
}

#@help _wireguard_list1
# @internal arity-1 sibling of 'wireguard list' (single category)
#@end
_wireguard_list1() {
  local category="$1"
  local category_dir="$VPN_SWITCH_BASE/wireguard/$category"

  # Check if category exists
  if [ ! -d "$category_dir" ]; then
    generate_error "Category not found: $category"
    return 0
  fi

  # Output listing with hierarchy prefixes and comment headers
  echo "# === Links in wireguard/$category ==="
  echo "#"

  # List all items in category with targets (inline to show arrows)
  # Note: Categories typically contain symlinks, show their targets
  for item in "$category_dir"/*; do
    # Skip if no items found (glob didn't match)
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    # Skip items with newlines (cannot output safely)
    has_newline_in_path "$item" && continue

    local item_name=$(basename -- "$item")

    # Show symlink target if it's a link
    if [ -L "$item" ]; then
      local target=$(readlink "$item")
      echo "wireguard/$category/$item_name -> $target"
    else
      # Regular file/directory (shouldn't happen in categories, but be safe)
      echo "wireguard/$category/$item_name"
    fi
  done | sort
}

#@help _wireguard_add1
# @command wireguard add <category> [<config> [<alias>]]
# @summary Create a category, or link a config into one
# @group   wireguard
# @param   category  category to create or add to
# @param   config    config to link into the category
# @param   alias     custom link name (default: derived)
# @returns shell commands (create category / create symlink)
# @example vpn-switch wireguard add privacy wg-CH-201.conf switzerland
# @see     wireguard link
#@end
_wireguard_add1() {
  local category="$1"
  local wg_dir="$VPN_SWITCH_BASE/wireguard"
  local category_path="$wg_dir/$category"

  # Check if category already exists (file, link, or directory)
  if [ -e "$category_path" ] || [ -L "$category_path" ]; then
    generate_error "Category already exists: $category"
    return 0
  fi

  # Output commands to create category
  cat <<EOF
# Create WireGuard category: $category
$MODIFY_DIR_CREATE "$category_path"
$MODIFY_FILE_PERMS 0755 "$category_path"
echo "# Created category: wireguard/$category" >&2
EOF
}

#@help __wireguard_add2
# @internal arity-2 sibling of 'wireguard add' (config into category)
#@end
__wireguard_add2() {
  local category="$1"
  local target="$2"
  local wg_dir="$VPN_SWITCH_BASE/wireguard"
  local category_dir="$wg_dir/$category"

  # Validate category exists and is a directory
  if [ ! -d "$category_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Category not found: $category\""
    return
  fi

  # Validate target exists in protocol directory
  # Note: Target could be a .conf file or a symlink
  local target_path="$wg_dir/$target"
  if [ ! -e "$target_path" ] && [ ! -L "$target_path" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Target not found in wireguard directory: $target\""
    return
  fi

  # Check if link already exists in category
  local link_path="$category_dir/$target"
  if [ -e "$link_path" ] || [ -L "$link_path" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Link already exists in category $category: $target\""
    return
  fi

  # Delegate to add3 with target as both target and alias
  # Script path included in output (expands inside run_env)
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard add \"$category\" \"$target\" \"$target\""
}

#@help _wireguard_add3
# @internal arity-3 sibling of 'wireguard add' (config + custom alias)
#@end
_wireguard_add3() {
  local category="$1"
  local target="$2"
  local alias="$3"
  local wg_dir="$VPN_SWITCH_BASE/wireguard"
  local category_dir="$wg_dir/$category"

  # Validate category exists and is a directory
  if [ ! -d "$category_dir" ]; then
    generate_error "Category not found: $category"
    return 0
  fi

  # Validate target exists in protocol directory
  local target_path="$wg_dir/$target"
  if [ ! -e "$target_path" ] && [ ! -L "$target_path" ]; then
    generate_error "Target not found in wireguard directory: $target"
    return 0
  fi

  # Check if alias already exists in category
  local link_path="$category_dir/$alias"
  if [ -e "$link_path" ] || [ -L "$link_path" ]; then
    generate_error "Alias already exists in category $category: $alias"
    return 0
  fi

  # Output commands to create symlink (relative path)
  cat <<EOF
# Add link to category: wireguard/$category/$alias -> $target
$MODIFY_LINK_CREATE "../$target" "$category_dir/$alias"
echo "# Added to category $category: $alias -> $target" >&2
EOF
}

#@help _wireguard_link2
# @command wireguard link <alias> <target>
# @summary Create a protocol-level alias to a config
# @group   wireguard
# @param   alias   new alias name
# @param   target  config the alias points to
# @returns shell commands (create symlink)
# @example vpn-switch wireguard link switzerland wg-CH-201.conf
# @see     wireguard add
#@end
_wireguard_link2() {
  local alias="$1"
  local target="$2"
  local wg_dir="$VPN_SWITCH_BASE/wireguard"
  local alias_path="$wg_dir/$alias"
  local target_path="$wg_dir/$target"

  # Validate target exists in protocol directory
  if [ ! -e "$target_path" ] && [ ! -L "$target_path" ]; then
    generate_error "Target not found in wireguard directory: $target"
    return 0
  fi

  # Check if alias already exists (file, link, or directory)
  if [ -e "$alias_path" ] || [ -L "$alias_path" ]; then
    generate_error "Alias already exists: $alias"
    return 0
  fi

  # Output commands to create symlink (relative path for same directory)
  cat <<EOF
# Create link in wireguard/: $alias -> $target
$MODIFY_LINK_CREATE "./$target" "$alias_path"
echo "# Created link: wireguard/$alias -> $target" >&2
EOF
}

#@help _wireguard_remove1
# @command wireguard remove <name>
# @summary Remove a config, link or category (with safety checks)
# @group   wireguard
# @param   name  config, link or category to remove
# @returns shell commands (remove the target)
# @example vpn-switch wireguard remove old-server
#@end
_wireguard_remove1() {
  local name="$1"
  local wg_dir="$VPN_SWITCH_BASE/wireguard"
  local target_path="$wg_dir/$name"

  # Validate target exists
  if [ ! -e "$target_path" ] && [ ! -L "$target_path" ]; then
    generate_error "Target not found in wireguard directory: $name"
    return 0
  fi

  # If it's a symlink, remove without checks
  if [ -L "$target_path" ]; then
    cat <<EOF
# Remove symlink from wireguard/: $name
$MODIFY_LINK_REMOVE "$target_path"
echo "Removed link: wireguard/$name"
EOF
    return 0
  fi

  # If it's a directory (category), check if empty
  if [ -d "$target_path" ]; then
    # Check if directory is empty
    if [ -n "$(ls -A "$target_path" 2>>"$LOG_FILE")" ]; then
      generate_error "Category not empty: $name"
      display plain "Remove all links from category first, then retry"
      return 0
    fi

    # Directory is empty, safe to remove
    cat <<EOF
# Remove empty category: $name
rmdir "$target_path"
echo "Removed category: wireguard/$name"
EOF
    return 0
  fi

  # It's a file - check if it's a config
  case "$name" in
    *.conf)
      # Check for active sessions using this config
      local session_dir="$VPN_SWITCH_BASE/.session"
      if [ -d "$session_dir" ]; then
        for session in "$session_dir"/*; do
          if [ -d "$session" ] && [ -f "$session/original" ]; then
            local original=$(cat "$session/original")
            if [ "$original" = "$target_path" ]; then
              local pid=$(basename -- "$session")
              generate_error "Config in use by active session - PID $pid: $name"
              display plain "Remove the session first with: vpn-switch session remove $pid"
              return 0
            fi
          fi
        done
      fi

      # Check for symlinks referencing this config
      local refs=""
      local ref_count=0

      # Canonicalize target path for comparison
      local canonical_target=$(readlink -f "$target_path")

      # Check protocol directory for symlinks
      for item in "$wg_dir"/*; do
        if [ -L "$item" ] && [ "$(readlink -f "$item")" = "$canonical_target" ]; then
          refs="$refs
  - wireguard/$(basename -- "$item")"
          ref_count=$((ref_count + 1))
        fi
      done

      # Check categories for symlinks
      for category in "$wg_dir"/*; do
        if [ -d "$category" ]; then
          for item in "$category"/*; do
            if [ -L "$item" ] && [ "$(readlink -f "$item")" = "$canonical_target" ]; then
              refs="$refs
  - wireguard/$(basename -- "$category")/$(basename -- "$item")"
              ref_count=$((ref_count + 1))
            fi
          done
        fi
      done

      # If references found, refuse with error
      if [ $ref_count -gt 0 ]; then
        generate_error "Config has $ref_count symlink reference(s): $name"
        display plain "$refs"
        display plain "Remove symlinks first, or use: vpn-switch wireguard clean | sh"
        return 0
      fi

      # No references, safe to remove
      cat <<EOF
# Remove config from wireguard/: $name
$MODIFY_FILE_REMOVE "$target_path"
echo "Removed config: wireguard/$name"
EOF
      ;;
    *)
      # Not a .conf file and not a symlink - refuse
      generate_error "Cannot remove: $name - not a config file or symlink"
      return 0
      ;;
  esac
}

#@help _wireguard_remove2
# @internal arity-2 variant of 'wireguard remove' (remove link from a category)
#@end
_wireguard_remove2() {
  local category="$1"
  local name="$2"
  local wg_dir="$VPN_SWITCH_BASE/wireguard"
  local category_path="$wg_dir/$category"
  local target_path="$category_path/$name"

  # Validate category exists
  if [ ! -d "$category_path" ]; then
    generate_error "Category not found: $category"
    return 0
  fi

  # Validate target exists in category
  if [ ! -e "$target_path" ] && [ ! -L "$target_path" ]; then
    generate_error "Link not found in category $category: $name"
    return 0
  fi

  # Output commands to remove
  cat <<EOF
# Remove from category $category: $name
$MODIFY_LINK_REMOVE "$target_path"
echo "Removed from $category: $name"
EOF
}

#@help _wireguard_validate0
# @command wireguard validate
# @summary Check WireGuard symlink integrity in the database
# @group   wireguard
# @returns validation report
# @example vpn-switch wireguard validate
# @see     wireguard clean
#@end
_wireguard_validate0() {
  local wg_dir="$VPN_SWITCH_BASE/wireguard"
  local has_errors=0
  local has_warnings=0

  # Check if wireguard directory exists
  if [ ! -d "$wg_dir" ]; then
    echo "# [ERROR] WireGuard directory not found: $wg_dir"
    return 1
  fi

  echo "# === WireGuard Configuration Validation ==="
  echo "#"

  # Check for files with newlines in name (cannot be safely handled)
  echo "# Checking for files with newlines in name..."
  for item in "$wg_dir"/*; do
    # Skip if no items
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    # Check for newlines in path
    if has_newline_in_path "$item"; then
      echo "# [ERROR] File has newline in name (cannot be safely handled)"
      has_errors=1
    fi
  done

  # Check for broken symlinks in protocol directory
  echo "#"
  echo "# Checking protocol directory for broken symlinks..."
  for item in "$wg_dir"/*; do
    # Skip if no items
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    # Skip files with newlines (already reported above)
    has_newline_in_path "$item" && continue

    # Check if symlink and broken
    if [ -L "$item" ] && [ ! -e "$item" ]; then
      echo "# [ERROR] Broken symlink: wireguard/$(basename -- "$item")"
      has_errors=1
    fi
  done

  # Check for broken symlinks in categories
  echo "#"
  echo "# Checking categories for broken symlinks..."
  for category in "$wg_dir"/*; do
    [ ! -d "$category" ] && continue

    # Skip categories with newlines (already reported above)
    has_newline_in_path "$category" && continue

    local category_name=$(basename -- "$category")

    for item in "$category"/*; do
      # Skip if no items
      [ ! -e "$item" ] && [ ! -L "$item" ] && continue

      # Skip items with newlines
      if has_newline_in_path "$item"; then
        echo "# [ERROR] File has newline in name (in category $category_name)"
        has_errors=1
        continue
      fi

      # Check if symlink and broken
      if [ -L "$item" ] && [ ! -e "$item" ]; then
        echo "# [ERROR] Broken symlink: wireguard/$category_name/$(basename -- "$item")"
        has_errors=1
      fi
    done
  done

  # Check for naming conflicts (file and directory with same name)
  echo "#"
  echo "# Checking for naming conflicts..."
  for item in "$wg_dir"/*; do
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    # Skip items with newlines (already reported above)
    has_newline_in_path "$item" && continue

    local base_name=$(basename -- "$item")

    # Skip directories and non-conf files for this check
    [ -d "$item" ] && continue
    [ ! -f "$item" ] && [ ! -L "$item" ] && continue

    # Check if there's also a directory with the same name (without .conf)
    local name_without_ext="${base_name%.conf}"
    if [ -d "$wg_dir/$name_without_ext" ]; then
      echo "# [WARNING] Naming conflict: wireguard/$base_name (file) and wireguard/$name_without_ext/ (directory)"
      has_warnings=1
    fi
  done

  # Check for basic config file validity (just check if readable and non-empty)
  echo "#"
  echo "# Checking config file validity..."
  for item in "$wg_dir"/*.conf; do
    # Skip if glob didn't match any files
    [ ! -e "$item" ] && continue

    # Skip items with newlines (already reported above)
    has_newline_in_path "$item" && continue

    local config_name=$(basename -- "$item")

    # Check if readable
    if [ ! -r "$item" ]; then
      echo "# [ERROR] Config not readable: wireguard/$config_name"
      has_errors=1
      continue
    fi

    # Check if non-empty
    if [ ! -s "$item" ]; then
      echo "# [WARNING] Config file is empty: wireguard/$config_name"
      has_warnings=1
      continue
    fi

    # Check for basic WireGuard sections
    if ! grep -q "^\[Interface\]" "$item" 2>>"$LOG_FILE"; then
      echo "# [WARNING] Config missing [Interface] section: wireguard/$config_name"
      has_warnings=1
    fi
  done

  # Summary
  echo "#"
  if [ $has_errors -eq 0 ] && [ $has_warnings -eq 0 ]; then
    echo "# Validation complete: No issues found"
    return 0
  elif [ $has_errors -eq 0 ]; then
    echo "# Validation complete: Warnings found (no errors)"
    return 0
  else
    echo "# Validation complete: Errors found"
    return 1
  fi
}

#@help ___wireguard_clean0
# @command wireguard clean [<category>]
# @summary Generate cleanup commands for broken links
# @group   wireguard
# @param   category  restrict cleanup to one category
# @returns shell commands (review, then pipe to sh)
# @example vpn-switch wireguard clean | sh
# @see     wireguard validate
#@end
___wireguard_clean0() {
  local wg_dir="$VPN_SWITCH_BASE/wireguard"

  # Check if wireguard directory exists
  if [ ! -d "$wg_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"WireGuard directory not found: $wg_dir\""
    return 0
  fi

  echo "# Clean up broken symlinks in wireguard/"
  echo "#"
  echo "# This script will remove broken symlinks."
  echo "# Review the commands below, then run: vpn-switch wireguard clean | sh"
  echo "#"
  safety_first_message
  echo "#"

  local found_broken=0

  # Check protocol directory for broken symlinks
  for item in "$wg_dir"/*; do
    # Skip if no items
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    # Skip items with newlines (cannot generate valid commands)
    if has_newline_in_path "$item"; then
      echo "# WARNING: Skipping file with newline in name (cannot be safely handled)"
      continue
    fi

    # Check if symlink and broken
    if [ -L "$item" ] && [ ! -e "$item" ]; then
      local item_name=$(basename -- "$item")
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard remove \"$item_name\""
      found_broken=1
    fi
  done

  # Check categories for broken symlinks
  for category in "$wg_dir"/*; do
    [ ! -d "$category" ] && continue

    # Skip categories with newlines
    has_newline_in_path "$category" && continue

    local category_name=$(basename -- "$category")

    for item in "$category"/*; do
      # Skip if no items
      [ ! -e "$item" ] && [ ! -L "$item" ] && continue

      # Skip items with newlines (cannot generate valid commands)
      if has_newline_in_path "$item"; then
        echo "# WARNING: Skipping file with newline in name (cannot be safely handled)"
        continue
      fi

      # Check if symlink and broken
      if [ -L "$item" ] && [ ! -e "$item" ]; then
        local item_name=$(basename -- "$item")
        echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard remove \"$category_name\" \"$item_name\""
        found_broken=1
      fi
    done
  done

  if [ $found_broken -eq 0 ]; then
    echo "# No broken symlinks found"
  fi
}

#@help ___wireguard_clean1
# @internal arity-1 sibling of 'wireguard clean' (single category)
#@end
___wireguard_clean1() {
  local category="$1"
  local wg_dir="$VPN_SWITCH_BASE/wireguard"
  local category_path="$wg_dir/$category"

  # Validate category exists
  if [ ! -d "$category_path" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"Category not found: $category\""
    return 0
  fi

  echo "# Clean up broken symlinks in wireguard/$category/"
  echo "#"
  echo "# This script will remove broken symlinks from category: $category"
  echo "# Review the commands below, then run: vpn-switch wireguard clean $category | sh"
  echo "#"

  local found_broken=0

  # Check category for broken symlinks
  for item in "$category_path"/*; do
    # Skip if no items
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    # Skip items with newlines (cannot generate valid commands)
    if has_newline_in_path "$item"; then
      echo "# WARNING: Skipping file with newline in name (cannot be safely handled)"
      continue
    fi

    # Check if symlink and broken
    if [ -L "$item" ] && [ ! -e "$item" ]; then
      local item_name=$(basename -- "$item")
      echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard remove \"$category\" \"$item_name\""
      found_broken=1
    fi
  done

  if [ $found_broken -eq 0 ]; then
    echo "# No broken symlinks found in category: $category"
  fi
}

#@help _wireguard_patch1
# @command wireguard patch <config>
# @summary Preview the patched config that would be used to connect
# @group   wireguard
# @param   config  config to preview
# @returns the patched configuration
# @example vpn-switch wireguard patch wg-CH-201.conf
#@end
_wireguard_patch1() {
  local config_name="$1"
  local wg_dir="$VPN_SWITCH_BASE/wireguard"

  # Resolve config path (handle both relative and absolute paths)
  local config_path=""
  case "$config_name" in
    /*)
      # Absolute path - use as-is
      config_path="$config_name"
      ;;
    *)
      # Relative path - resolve from wireguard directory
      config_path="$wg_dir/$config_name"
      ;;
  esac

  # Validate config exists
  if [ ! -f "$config_path" ]; then
    generate_error "Config file not found: $config_path"
    return 0
  fi

  # Validate it's readable
  if [ ! -r "$config_path" ]; then
    generate_error "Config file not readable: $config_path"
    return 0
  fi

  # Output patched config to stdout using patch_wireguard_config helper
  # Note: /dev/stdout is POSIX-compliant for output redirection
  patch_wireguard_config "$config_path" /dev/stdout
}

#@help _wireguard_info1
# @command wireguard info <category>
# @summary Show category details, including config expiry dates
# @group   wireguard
# @param   category  category to inspect
# @returns category report
# @example vpn-switch wireguard info privacy
#@end
_wireguard_info1() {
  local category="$1"
  local wg_dir="$VPN_SWITCH_BASE/wireguard"
  local category_path="$wg_dir/$category"

  # Validate category exists and is a directory
  if [ ! -d "$category_path" ]; then
    generate_error "Category does not exist: $category"
    return 0
  fi

  # Count configs and links
  local config_count=0
  local link_count=0

  for entry in "$category_path"/*; do
    [ -e "$entry" ] || continue
    if [ -L "$entry" ]; then
      link_count=$((link_count + 1))
    elif [ -f "$entry" ] && [ "${entry%.conf}" != "$entry" ]; then
      config_count=$((config_count + 1))
    fi
  done

  # Display formatted output
  cat <<EOF
# Category: $category
#
# Configs: $config_count
# Links:   $link_count
# Path:    $category_path
#
# Contents:
EOF

  # List all entries with expiry information
  for entry in "$category_path"/*; do
    [ -e "$entry" ] || continue
    local basename_entry=$(basename -- "$entry")

    if [ -L "$entry" ]; then
      # Follow symlink to get actual config file
      local target=$(readlink "$entry")
      local target_path="$category_path/$target"

      # Resolve relative symlinks
      if [ "${target#/}" = "$target" ]; then
        # Relative path - resolve it
        target_path=$(cd "$(dirname "$entry")" && cd "$(dirname "$target")" && pwd)/$(basename "$target")
      fi

      # Get expiry for the target
      local expiry_info=""
      if [ -f "$target_path" ]; then
        expiry_info=$(get_wireguard_expiry_status "$target_path")
      fi

      if [ -n "$expiry_info" ]; then
        echo "#   $basename_entry -> $target  $expiry_info"
      else
        echo "#   $basename_entry -> $target"
      fi
    elif [ -f "$entry" ]; then
      # Regular file - get expiry
      local expiry_info=$(get_wireguard_expiry_status "$entry")
      if [ -n "$expiry_info" ]; then
        echo "#   $basename_entry  $expiry_info"
      else
        echo "#   $basename_entry"
      fi
    else
      echo "#   $basename_entry"
    fi
  done
}

#@help ___wireguard_dump0
# @command wireguard dump
# @summary Generate restorable shell commands for all WireGuard configs
# @group   wireguard
# @returns shell commands (restorable database dump)
# @example vpn-switch wireguard dump
# @see     dump
#@end
___wireguard_dump0() {
  local wg_dir="$VPN_SWITCH_BASE/wireguard"
  local session_pseudo="$VPN_SWITCH_BASE/session"

  # Validate wireguard directory exists
  if [ ! -d "$wg_dir" ]; then
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" error \"WireGuard directory not found: $wg_dir\""
    return 0
  fi

  # Phase 1: Import all configs (absolute paths from SOURCE database)
  echo "# Import wireguard configurations"
  for config_file in "$wg_dir"/*.conf; do
    [ ! -f "$config_file" ] && continue

    # Skip files with newlines in name (cannot be safely represented in line-based dump)
    if has_newline_in_path "$config_file"; then
      echo "# WARNING: Skipping file with newline in name (cannot be safely dumped)"
      continue
    fi

    # Use absolute path for imports with proper quoting
    # Output literal \$VPN_SWITCH_CONTEXT_SCRIPT so it expands during restore
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard import \"$config_file\""
  done

  # Output separator
  echo ""

  # Phase 2: Create categories
  echo "# Create categories"
  scan_wireguard_categories | while IFS= read -r category_path; do
    # Extract category name (remove wireguard/ prefix and / suffix)
    local category=$(echo "$category_path" | sed 's|^wireguard/||' | sed 's|/$||')
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard add $category"
  done

  # Output separator
  echo ""

  # Phase 3: Create protocol-level links (aliases in wireguard/ directory)
  echo "# Create protocol-level links"
  scan_wireguard_links | while IFS= read -r link_info; do
    # Parse "wireguard/alias -> target" format
    local alias=$(echo "$link_info" | sed 's|^wireguard/||' | sed 's| ->.*||')
    local target=$(echo "$link_info" | sed 's|.* -> ||')
    # Normalize target: strip ./ prefix (wireguard link will add it back)
    target=$(echo "$target" | sed 's|^\./||')
    echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard link $alias $target"
  done

  # Output separator
  echo ""

  # Phase 4: Create category links
  echo "# Create category links"
  scan_wireguard_categories | while IFS= read -r category_path; do
    # Extract category name
    local category=$(echo "$category_path" | sed 's|^wireguard/||' | sed 's|/$||')
    local category_dir="$wg_dir/$category"

    # Scan for links in this category
    for link_file in "$category_dir"/*; do
      [ ! -L "$link_file" ] && continue
      local link_name=$(basename "$link_file")
      local target=$(readlink "$link_file")
      local target_basename=$(basename "$target")

      # Determine if this is arity-2 (link and target have same name) or arity-3 (different)
      local target_base=$(basename "$target" .conf)
      if [ "$link_name" = "$target_base" ] || [ "$link_name" = "$target_basename" ]; then
        # Arity-2: same name
        echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard add $category $target_basename"
      else
        # Arity-3: custom name
        echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" wireguard add $category $target_basename $link_name"
      fi
    done
  done

  # Output separator
  echo ""

  # Note: Phase 5 (session dumping) removed - now handled by ___session_dump0()
  # This ensures multi-protocol sessions are dumped correctly (not just WireGuard)
}

#@help __wireguard_help0
# @command wireguard help
# @summary Show WireGuard command help
# @group   wireguard
# @returns help text
# @example vpn-switch wireguard help
#@end
__wireguard_help0() {
  # Backward compatibility: delegate to new pattern "help wireguard"
  echo "\"\$VPN_SWITCH_CONTEXT_SCRIPT\" help wireguard"
}

patch_wireguard_config() {
  local source_config="$1"
  local dest_config="$2"

  # Phase-based approach: Strip existing DNS hooks (DNS handled by DNS phase)
  # Simply remove PostUp/PostDown lines that contain resolvconf
  awk '
    # Skip PostUp/PostDown lines that contain resolvconf (DNS hooks)
    /^PostUp.*resolvconf/ { next }
    /^PostDown.*resolvconf/ { next }

    # Print all other lines
    { print }
  ' "$source_config" > "$dest_config"

  $MODIFY_FILE_PERMS 0640 "$dest_config"
}

get_wireguard_remotes() {
  local config_file="$1"

  awk '/^\[Peer\]/,/^$/ {
    if ($1 == "Endpoint") {
      # Extract IP from "IP:port"
      split($3, parts, ":")
      print parts[1]
    }
  }' "$config_file"
}

scan_wireguard_links() {
  local wg_dir="$VPN_SWITCH_BASE/wireguard"

  # Find all symlinks that are NOT config files (i.e., protocol-level aliases)
  for item in "$wg_dir"/*; do
    # Skip if no items found
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    # Skip directories (categories)
    [ -d "$item" ] && continue

    # Skip if not a symlink
    [ ! -L "$item" ] && continue

    # Skip items with newlines (cannot output safely)
    has_newline_in_path "$item" && continue

    local item_name=$(basename -- "$item")

    # Skip .conf files (those are listed in configs section)
    case "$item_name" in
      *.conf) continue ;;
    esac

    # Show symlink with target
    local target=$(readlink "$item")
    echo "wireguard/$item_name -> $target"
  done | sort
}

scan_wireguard_categories() {
  local wg_dir="$VPN_SWITCH_BASE/wireguard"

  # Find all subdirectories, add hierarchy prefix and "/" suffix
  for item in "$wg_dir"/*; do
    # Skip if not a directory
    [ ! -d "$item" ] && continue

    # Skip items with newlines (cannot output safely)
    has_newline_in_path "$item" && continue

    local item_name=$(basename -- "$item")
    echo "wireguard/$item_name/"
  done | sort
}

get_wireguard_expiry_status() {
  local config_file="$1"

  if [ ! -f "$config_file" ]; then
    echo ""
    return
  fi

  # VPN provider WireGuard configs expire 1 year after creation
  # Use file birth time (creation time) as baseline
  local file_ctime
  local estimated_expiry
  local current_time
  local days_left

  # Get file creation time (birth time)
  file_ctime=$($CMD_STAT_CTIME "$config_file" 2>>"$LOG_FILE" || echo "0")

  if [ "$file_ctime" = "0" ] || [ "$file_ctime" = "-" ]; then
    # Birth time not available, fall back to modification time
    file_ctime=$($CMD_STAT_MTIME "$config_file" 2>>"$LOG_FILE" || echo "0")
  fi

  if [ "$file_ctime" = "0" ]; then
    echo "[? unknown]"
    return
  fi

  # Add 1 year (365 days * 24 hours * 3600 seconds) to file creation time
  estimated_expiry=$((file_ctime + 31536000))
  current_time=$(date +%s)

  # Calculate days difference
  days_left=$(( (estimated_expiry - current_time) / 86400 ))

  # Format output with status indicators
  if [ "$days_left" -lt 0 ]; then
    # Expired
    echo "[✗ expired: ${days_left#-}d ago]"
  elif [ "$days_left" -le 30 ]; then
    # Expiring soon (within 30 days)
    echo "[⚠ expiring: ${days_left}d]"
  else
    # Valid (more than 30 days)
    echo "[✓ valid: ${days_left}d]"
  fi
}

scan_wireguard_configs() {
  local wg_dir="$VPN_SWITCH_BASE/wireguard"

  # Find all .conf files (both regular files and symlinks ending in .conf)
  for item in "$wg_dir"/*.conf; do
    # Skip if glob didn't match
    [ ! -e "$item" ] && [ ! -L "$item" ] && continue

    # Skip items with newlines (cannot output safely)
    has_newline_in_path "$item" && continue

    local item_name=$(basename -- "$item")
    echo "wireguard/$item_name"
  done | sort
}

scan_category_links() {
  local category="$1"
  local category_dir="$VPN_SWITCH_BASE/wireguard/$category"

  # Find all items in category, add hierarchy prefix
  # Note: Categories contain symlinks, not actual files
  for item in "$category_dir"/*; do
    # Skip if glob didn't match or not a symlink
    [ ! -L "$item" ] && continue

    # Skip items with newlines (cannot output safely)
    has_newline_in_path "$item" && continue

    local item_name=$(basename -- "$item")
    echo "wireguard/$category/$item_name"
  done | sort
}

