[Interface]
# Bouncing = 0
# NetShield = 2
# Moderate NAT = off
# NAT-PMP (Port Forwarding) = off
# VPN Accelerator = on
PrivateKey = EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE=
Address = 10.2.0.2/32
DNS = 10.2.0.1

[Peer]
# TEST-CH#1
PublicKey = FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF=
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = 192.0.2.3:51820